### ISSUE TITLE
meta_factory func calculates arity wrong when first argument matches type

### ISSUE THREAD

**Issue by EamonKavanagh** [skypjack/entt#1001]
Version: 3.11

When setting up reflection, I've found that registering a function for a type with the first argument being of the same type, the resulting function sets the arity property incorrectly.

Example:

```cpp
struct Foo {
  int x;
}

bool bar(Foo& foo) {
  std::cout << "bar called" << std::endl; // never executed
  return true;
}

entt::meta<Foo>().func<&bar>("bar"_hs);

auto bar_func = entt::resolve<Foo>().func("bar"_hs);
Foo foo_value;
entt::meta_any meta_any_foo_value(foo_value);
bar_func .invoke({}, meta_any_foo_value.as_ref());
```

When stepping through the code, the underlying method seems to be skipped because `sz != arity()` [here](https://github.com/skypjack/entt/blob/3ef61fe0146660bd5b25d143e666c8385084bb37/src/entt/meta/meta.hpp#L961). I haven't been able to figure out why `arity` is calculated incorrectly.

What I have found is that if I replace the `Foo` argument in `bar` with any other type (and update `foo_value`) the function executes. I've also noticed that if I add an additional parameter in `bar` before `Foo` (and call `invoke` appropriately) the function executes. When

**Comment by skypjack** [comment]
> When setting up reflection, I've found that registering a function for a type with the first argument being of the same type, the resulting function sets the arity property incorrectly.

What is wrong here is the expectation, not the result. The meta world and the C++ world are very different beasts after all.
Keep in mind that the arity is that of the meta function and **NOT** that of the underlying function. Try to abstract from what you know about what you are wiring up now.
In the meta land, your function is nothing more than a non-const non-static member function of your meta type. You invoke it by passing a `this` and no arguments, as in:
```cpp
bar_func .invoke(meta_any_foo_value.as_ref());
```
Exactly as if it were defined in the C++ land as:
```cpp
struct Foo {
  bool bar() { ... }
  int x;
}
```
In meta, you don't have _free functions_. You only have meta types and meta functions. If you defined your function as:
```cpp
bool bar(const Foo &) { ... }
```
Then you would have had a non-static (because it wants a `this`) const (because of the `const Foo &`) meta function.
Do you see the patter now? If you expect the arity to be that of the C++ function, then you will hardly always find a match.

**Comment by EamonKavanagh** [comment]
Thanks for the detailed explanation! That definitely makes sense and after taking a closer look at the invoke API I can see how that would work.

Just want to add that I found this a bit confusing for two points in case others run into similar issues:

1. I previously used version 3.8 where my initial example did work. In the 3.10 changelog, is "meta_type::invoke also searches into the base types for a candidate function" the relevant change?
2. For a multi-argument meta_func, changing the argument order changes the arity.

**Comment by skypjack** [comment]
Yeah, there was an issue in older version of EnTT. It's very likely that v3.8 contained it too.
As for the second point, consider that a free function is considered as non-static meta function **only** if the first argument is that of the meta type to which it belongs. That is why switching args changes the arity. Roughly speaking, the function becomes a static one and what was a hidden `this` value before is now a proper function argument.

**Comment by EamonKavanagh** [comment]
That makes sense, thanks again!

**Comment by skypjack** [comment]
You're welcome 👍

**Comment by EamonKavanagh** [comment]
One minor correction:

`bar_func.invoke(meta_any_foo_value.as_ref())` should be `bar_func.invoke(meta_any_foo_value)` (not passed as a reference). Passing it as a reference causes invoke to not work.
