### ISSUE TITLE
Crash when using plugin's and EnTT dispatcher

### ISSUE THREAD

**Issue by Milerius** [skypjack/entt#103]
Hello !

I have a lot of progress with EnTT lately, and also on my engine. I arrived at the moment when I'm doing plugins (dll's) and it seems that I have a huge problem with the destruction of the program at the dispatcher level.

Here is my stacktrace:
https://hastebin.com/axirojaluy.rb

I'm not sure what I'm going to say, but it seems that taking a dispatcher by reference and then connect events through the plugin is a huge problem, indeed the plugin is destroyed before the dispatcher, which I remember only has a reference on the dispatcher. It seems that the crash is places at the level of vector destruction:
```cpp
std::vector<std::unique_ptr<BaseSignalWrapper>> wrappers;
````

there is the header from one of my plugins:
```cpp
//
// Created by roman Sztergbaum on 18/06/2018.
//

#pragma once

#include <SFML/Graphics.hpp>
#include <shiva/ecs/system.hpp>
#include <shiva/sfml/event/set_render_window.hpp>

namespace shiva::plugins
{
    class input_system : public shiva::ecs::pre_update_system<input_system>
    {
    public:
        void receive(const shiva::sfml::event::set_render_window &evt)
        {
            win_ = evt.win;
        }

        ~input_system() noexcept override = default;

        input_system(shiva::entt::dispatcher &dispatcher, shiva::entt::entity_registry &registry,
                     const float &fixed_delta_time) noexcept :
            system(dispatcher, registry, fixed_delta_time)
        {
            dispatcher_.sink<shiva::sfml::event::set_render_window>().connect(this);
        }

        static std::unique_ptr<shiva::ecs::base_system> system_creator(entt::dispatcher &dispatcher,
                                                                       entt::entity_registry &registry,
                                                                       const float &fixed_delta_time) noexcept;
        void update() noexcept final;

    public:
        reflect_class(input_system)

        static constexpr auto reflected_functions() noexcept
        {
            return meta::makeMap(reflect_function(&input_system::update));
        }

        static constexpr auto reflected_members() noexcept
        {
            return meta::makeMap();
        }

    private:
        sf::RenderWindow *win_{nullptr};
    };
}
````

as you can see i'm just connecting a new kind of event `shiva::sfml::event::set_render_window`

loading of the dll's:
```cpp
    auto functor = [this](auto &&dlls) {
                system_ptr ptr = dlls(this->dispatcher_, this->ett_registry_, this->timestep_.get_fixed_delta_time());
                add_system_(std::move(ptr), ptr->get_system_type_RTTI()).im_a_plugin();
            };

            plugins_registry_.apply_on_each_symbols(functor);
````

there is also an image when the crash occur:
<img width="1076" alt="capture d ecran 2018-06-18 a 20 51 33" src="https://user-images.githubusercontent.com/21139416/41555935-7fe8371a-7339-11e8-9799-ba1b92ad31a2.png">

I think that during the destruction of the dispatcher he tries to do something with the pointer of the class that was connected, but this pointer does not exist any more because the plugin was destroyed before the dispatcher, which seems to me all logical for me.
But as I said I'm not sure, I also try to make a disconnect of the event in the destructor classes that serve as plugins. This did not remove the crash.

Compiler:
clang version 6.0.0 (tags/RELEASE_600/final)
Target: x86_64-apple-darwin17.4.0
Thread model: posix
InstalledDir: /usr/local/opt/llvm/bin

Os:
macOs High Sierra 10.13.3

Library use for the management of the dll: 
Boost.DLL

If you need any more information i will be very hapy to help you on this issue !

you can find the matrices of my modules here:
http://confluence.slyris.eu/display/SHIV/Modules

Project url:
https://github.com/Milerius/shiva

EDIT: i found this very interesting 
<img width="1680" alt="capture d ecran 2018-06-18 a 21 37 21" src="https://user-images.githubusercontent.com/21139416/41558129-26f1a4f0-7340-11e8-9a42-61f3d45762d8.png">
<img width="1680" alt="capture d ecran 2018-06-18 a 21 37 42" src="https://user-images.githubusercontent.com/21139416/41558130-270a6daa-7340-11e8-9d20-8d8dc197015c.png">

i found a __value__ which seem's to be empty 
I register 5 type of event and the following one is missing at the destruction:

```cpp
struct set_render_window
    {
        set_render_window(sf::RenderWindow &win_) noexcept : win(&win_)
        {
        }

        sf::RenderWindow *win;
    };
````

I can now say with affirmation the following thing: if I first triggered the event from the main program that load the dll's no problem, on the other hand if the event was for the first time register / trigger in a DLL's it seems that the unique_ptr is corrupted and the __value__ of the unique_ptr is invalid, which causes a crash to its destruction.

I register for the first time `set_render_window` in a dll's and i triggered it only in the dll's. For all other event's they are register or trigger atleast one time from the main programm, and they are all valid in the vector of unique_ptr

I think that one of the solutions would be to be able to say at the destruction of the plugin through the dispatcher: "withdraw from the vector wrappers"

<img width="1033" alt="capture d ecran 2018-06-18 a 21 53 05" src="https://user-images.githubusercontent.com/21139416/41558737-174dd7d8-7342-11e8-8a77-69f9b752a8f5.png">

as you can see during the destruction of this plugin's the __value__ is not corrupted !
if we can withdraw from this vector at the moment, it's will solve the problem !

I know it's not very RAII like approach, only with plugins and dll's in c++ it's more of a feature that's close to c than c++ and program-dll's synchronization is always a problem. Is it possible to get the BaseSignalWrapper from the event? if so I think that doing an erase / remove_if will solve this issue.

**Comment by Milerius** [comment]
```cpp

    template<typename Event>
    void remove_wrapper() {
        const auto type = event_family::type<Event>();
        wrappers.erase(std::remove_if(std::begin(wrappers), std::end(wrappers), [this, type](auto &&ptr)
        {
            return ptr == this->wrappers[type];
        }), std::end(wrappers));
    }
````
usage:
```cpp
   dispatcher_.remove_wrapper<shiva::sfml::event::set_render_window>();
````
this snippet of code
solve this problem

**Comment by skypjack** [comment]
This isn't properly an issue of `EnTT`. Instead, it is due to the way you are dealing with the DLL and to how `EnTT` works under the hood.  
Moreover, be aware that the solution you proposed doesn't actually solve anything, because the same problem can still popup somewhere else at runtime and crash your application. It is as if you were pruning a tree and starting to cut the twigs.

`EnTT` makes use of type-erasure techniques internally, so as to avoid giving lists of types all around when classes are instantiated.  
This is why you can create a registry as:
```
entt::Registry<std::uint32_t> registry;
```
Instead of the more annoying and error prone:
```
entt::Registry<std::uint32_t, AComponent, AnotherComponent, ..., MyLastComponent> registry;
```
However, this comes at a cost: almost all the classes that _type-erases_ something make also allocations.  
This is a fact. Consider this:
```
registry.assign<AComponent>(registry.create());
```
The registry knew anything about `AComponent` before this line, so it cannot handle properly your component. How does it work around it? If it's the first time the registry sees a type, it creates internally (allocation) a dedicated pool, then it asks to the pool to register the entity (allocation) and the component (allocation).

So far, so good. It isn't a problem for itself and the much you use a registry the lower the number of allocations in time. Making `EnTT` allocator-aware should also improve the whole thing.

The `Dispatcher` class works exactly the same way. It creates (allocation) a dedicated pool for the events and eventually it allocates or reallocates when you push in events and listeners.  
The problem in your cases arises from the fact that you cross the boundaries between the executable and the DLL with an object that is created by the former and performs allocations when used by the latter. Why does it perform allocations? You found it, right? You are showing it for the first time a type of event, therefore it makes a `new` internally on the other side of the boundary.  
Everything then goes as expected: you discard the DLL, therefore the memory is free'd but the unique ptr doesn't know it, it tries once more to destroy an object that no longer exists and boom: double free and crash, that's all.  
Be aware that the same thing could happen if you decide to use the registry within a DLL to create an entity!! And this is only an example, there are plenty of risky operations for you out there. Unfortunately your solution just considers one case.  
Better solutions are:
* Share the dynamic storage (the heap) between the two actors, executable and DLL: it's quite obvious that they are currently using separated heap for some reasons.
* Make `EnTT` allocator-aware: in this case, the `Dispatcher` as well as the registry and all the other classes get memory from an allocator that invokes `new` only from a side of the boundary, so discarding the DLL won't break anything.
* Inversion of control: change a bit the design and arrange you code so as to be able to avoid allocations from both the sides of the boundary. It shouldn't be much difficult.
* ...

If you have any other doubt, feel free to ask.  
I'll close this issue in 24/48 hours because there is nothing to do on `EnTT` but to continue with the planned features up to the allocator-aware version of the library.  
Unfortunately, let the users purge memory eventually allocated from the wrong side of a boundary is a massive change that would turn the whole API in an ugly set of _purge this_ and _purge that_ methods. I cannot consider this _a long term solution_ and it's too much work for a short term solution.

**Comment by Milerius** [comment]
Hey thank you for your answer ! 

You proposed 3 possible solutions:
> Share the dynamic storage (the heap) between the two actors, executable and DLL: it's quite obvious that they are currently using separated heap for some reasons.

I do not think this solution is possible or I have absolutely no idea how it could be possible? In the idea I imagine maybe the plugin should take a reference on an allocator in its constructor from the main program, in this case it could be that the allocation to perform via this allocator would be added only to the heap of the program principal, only I do not know at all how to do that and maybe I should find out.

> Make EnTT allocator-aware: in this case, the Dispatcher as well as the registry and all the other classes get memory from an allocator that invokes new only from a side of the boundary, so discarding the DLL won't break anything.

I guess it goes with what I said above, a custom allocator may be able to solve the problem, I still think that at the moment it is difficult to do plugin handling with EnTT, I will answer in same time to the 3rd proposal that concerned my code. I can not prevent allocations from one dimension as another by what I need to runtime polymorphism. Indeed the plugins are systems of the ECS which obviously as you can guess uses the type_erasure / crtp idiom behind the hood. So I need allocation to be considered as a base_system.

I do not think my approach is really good in the sense that I'm doing a normal process of plugin management. I have a main program that has a system_manager, which itself has a registry of plugins and can load libraries. Which gives us something like:
Main Program -> system_manager -> load_plugins (on success plugins becomes base_system).

Knowing that most people who make plugins, stocking often in a container, I have trouble how it would do without polymorphism and without allocation to manage its plugins in general.

I understood that if the memory was allocated from the current object that is actually a DLL, it would pose a problem of multiple heaps. In this case I think that the solution of the allocation aware would be the most suitable, but I still need to see some examples for you to illustrate this aspect.

**Comment by skypjack** [comment]
I'm not saying your design is inherently wrong, sorry if I used the wrong terms. I'm just saying that it doesn't fit well with the way `EnTT` currently manages its memory.

>I do not think this solution is possible or I have absolutely no idea how it could be possible

As far as I remember, the problem arises when you executable and your dll links to different runtime. You can try searching _allocation exe dll boundary_ on the web. Probably there exist solutions, but I'm not _Windows'ed_ enough to know them. I'm sorry.

Of course, custom allocators will solve the problem. It's something on which I'd like to work during the summer, but I cannot set any schedule. I'm doing all of this in my free time after all!! :-)  

>I still think that at the moment it is difficult to do plugin handling with EnTT

In general, it's difficult to do plugin handling with all those tools that allocate at runtime if you can't provide your own allocator that literally _works across boundaries_. At least, it's difficult unless you rely on much complex techniques like inversion of control or signalling from inside.

That being said, if your problem is only with the dispatcher, try to avoid passing it to the DLL. If you can get away with submitting only the sinks you know are required by the system (I see, probably you don't know it) or passing a function that the system can invoke with the member functions to connect (the caller can easily deduce the type of event from the member function in this case), you're done.  
I know that it's much easier to say - _ehi, system, this is the dispatcher, do whatever you want with it_. However, we have a problem, so we must try to find a different solution. :-)

>Knowing that most people who make plugins, stocking often in a container, I have trouble how it would do without polymorphism and without allocation to manage its plugins in general.

The problem isn't that your plugin or your system does allocate. You can create the system wherever you want and allocate memory for whatever you want ob both the sides of the boundary.  
The problem is that when it comes to using a `Dispatcher` class that you created in your executable within a DLL, a (let me say) _cross boundary allocation_ takes place and it will crash for sure sooner or later.

Another problem that I see is that your plugins are systems. If you pass a whole registry to those classes during an `update` and they can both create entities and components, it could happen that also the registry (or its pools of components) allocates under the hood and this would lead exactly to the same result: crashes. On the other side, it's safe to iterate entities and components and update them in a DLL.

I've not a clear idea of how your systems are designed, but probably a solution exists to the problem and likely the we can reduce the impact to a minimum.  
Count me if you want to discuss about it.

**Comment by Milerius** [comment]
Anyway, it seems that I will wait for the arrival of the custom allocators in EnTT, and do other part of my engine in the meantime, all this problem concerns only my part on the plugins, either I can already use EnTT in my header-only systems and my systems that go through scripting, but I'd really like once this feature is present to finish all the plugins part for the users of my engine.

**Comment by skypjack** [comment]
Not sure I'll use `pmr::`, but I think it would be fine for your case. It's a matter of setting the right memory resource and get rid of allocations.

**Comment by Milerius** [comment]
I will wait for EnTT custom allocator

**Comment by skypjack** [comment]
Ok, as you prefer. The good thing is that we have quite a clear idea of what is the problem. So, you have enough information to try to work around it in the meantime if you find the time to do that. ;-)
