### ISSUE TITLE
Store an entity without creating it in a registry

### ISSUE THREAD

**Issue by samfromcadott** [skypjack/entt#1048]
I'm working on a game and I want to be able to define entity types in TOML files.

I would load these files at startup and create entities from them without instantiating them in world. When spawning entities, I would copy the saved entity into the active registry and set the position.

Is there anything like this possible with EnTT?

**Comment by skypjack** [comment]
What do you mean with _store an entity without creating it in a registry_? Where do you want to store it?
If you can provide the required data structures or use plain storage classes, then go with it. Otherwise, you can use a prototype registry from which you can copy an entity on demand into the main registry.
There are plenty of solutions and possible approaches. It's mostly a matter of tastes.
