### ISSUE TITLE
Unable to use valgrind due to assertion fail

### ISSUE THREAD

**Issue by plave0** [skypjack/entt#1064]
When running memcheck, I get the following error:
```
.../entt.hpp:15332: entt::basic_sparse_set::size_type entt::basic_sparse_set<>::index(const entt::basic_sparse_set::entity_type) const [Entity = entt::entity]: Assertion `contains(entt)' failed.
```

The same assertion fails when trying to use callgrind.

**Comment by skypjack** [comment]
I mean, it's an assertion. It's something EnTT does to prevent misuses.
You should try to track it down and understand what causes it.
The alternative is to disable assertions **BUT** it likely means UB, so 🤷‍♂️ I wouldn't suggest it.
In any case, this issue is invalid. As it stands, the error is clearly at the call site and I can't help without a repro. I'm sorry.

**Comment by plave0** [comment]
I am aware that the question was quite vague, but I was hoping it might be a known issue. 
Anyhow, @skypjack thank you for your suggestion and your time.
