### ISSUE TITLE
registry.create() returning entt::entity of id greater than entt::null?

### ISSUE THREAD

**Issue by michellelor** [skypjack/entt#1073]
After destroying created entities and creating new ones, registry.create() returns ids that are greater than entt::null. Is this normal?

**Comment by skypjack** [comment]
It doesn't. Identifiers are split in two parts, the entity and the version. `entt::null` _means_ 0xFFFF for all bits of the entity part.
When you destroy an identifier, the version is increased while the entity remains the same. This is what you're observing. In any case the resulting entity is greater than `entt::null` (also because `entt::null` is the maximum value allowed for the entity part, so this cannot happen by construction 🤷‍♂️).
Use `entt::to_integral` to _convert_ an identifier to its integral value and `entt::to_entity` or `entt::to_version` to _extract_ and verify its parts.

**Comment by michellelor** [comment]
thank you!
