### ISSUE TITLE
std::allocator deprecated in C++17

### ISSUE THREAD

**Issue by speedym** [skypjack/entt#1075]
When including signal/fwd.hpp, on the Android platform, I'm seeing the following warnings in EnTT code which complicate using -Werror -Wall in our project. Additionally, it is producing a lot of repeating compile output warning / error text which is polluting the build output, it repeats for each file which includes signal/fwd.hpp.

```
C/C++: xxx/3rdparty/entt/src/entt/entity/../signal/fwd.hpp:14:36: warning: 'allocator<void>' is deprecated [-Wdeprecated-declarations]
C/C++: template<typename, typename = std::allocator<void>>
C/C++:                                    ^
C/C++: xxx/Library/Android/sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/include/c++/v1/memory:717:28: note: 'allocator<void>' has been explicitly marked deprecated here
C/C++: class _LIBCPP_TEMPLATE_VIS _LIBCPP_DEPRECATED_IN_CXX17 allocator<void>
C/C++:                            ^
C/C++: xxx/Library/Android/sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/include/c++/v1/__config:1001:39: note: expanded from macro '_LIBCPP_DEPRECATED_IN_CXX17'
C/C++: #  define _LIBCPP_DEPRECATED_IN_CXX17 _LIBCPP_DEPRECATED
C/C++:                                       ^
C/C++: xxx/Library/Android/sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/include/c++/v1/__config:978:48: note: expanded from macro '_LIBCPP_DEPRECATED'
C/C++: #    define _LIBCPP_DEPRECATED __attribute__ ((deprecated))
```

**Comment by skypjack** [comment]
> I assume you meant std::allocator<T> isn't deprecated, but std::allocator<void> is as per https://en.cppreference.com/w/cpp/memory/allocator, right?

No. I meant that `std::allocator<void>` isn't deprecated. You misread what the link (and the standard) says.
C++17 deprecates (and C++20 removes) the explicit specialization for `std::allocator<void>` because it's no longer required. However, you can still specialize `std::allocator` with `void` and it _just works_™️ without any explicit specialization in the standard (because of `allocator_traits`, its rebinding techniques and bla bla bla, all things available since C++11 and also used in EnTT).
In the meantime, clang shipped a broken version of its compiler that triggers a warning because of its own specialization of `std::allocator<void>` (see [here](https://reviews.llvm.org/D104323) for some details). It got fixed in more recent versions but 🤷‍♂️ probably it is not in the one you're using I guess? Very likely from what I see.

So, again, I can't really fix a wrong warning by an older version of a compiler if that requires me to change how the library is implemented.
On the other side, you can either update the compiler or suppress the warning in a bunch of ways (disable it as a whole, [use a pragma](https://clang.llvm.org/docs/UsersManual.html#controlling-diagnostics-via-pragmas) to suppress it as needed when including EnTT, and so on).

**Comment by thomaspeer** [comment]
> > I assume you meant std::allocator isn't deprecated, but std::allocator is as per https://en.cppreference.com/w/cpp/memory/allocator, right?
> 
> No. I meant that `std::allocator<void>` isn't deprecated. You misread what the link (and the standard) says. C++17 deprecates (and C++20 removes) the explicit specialization for `std::allocator<void>` because it's no longer required. However, you can still specialize `std::allocator` with `void` and it _just works_ ™️ without any explicit specialization in the standard (because of `allocator_traits`, its rebinding techniques and bla bla bla, all things available since C++11 and also used in EnTT).
Ah indeed, thanks for the clarification.

>  In the meantime, clang shipped a broken version of its compiler that triggers a warning because of its own specialization of `std::allocator<void>` (see [here](https://reviews.llvm.org/D104323) for some details). It got fixed in more recent versions but 🤷‍♂️ probably it is not in the one you're using I guess? Very likely from what I see. So, again, I can't really fix a wrong warning by an older version of a compiler if that requires me to change how the library is implemented. On the other side, you can either update the compiler or suppress the warning in a bunch of ways (disable it as a whole, [use a pragma](https://clang.llvm.org/docs/UsersManual.html#controlling-diagnostics-via-pragmas) to suppress it as needed when including EnTT, and so on).

I believe updating the compiler should do the trick, we will let you know whichever worked best for others to see.

Thanks

**Comment by skypjack** [comment]
You're welcome. 👍

**Comment by skypjack** [comment]
Just out of curiosity, what version of clang are you using? This can help future readers too.

**Comment by thomaspeer** [comment]
We were using the `NDK r25` which uses `clang 14.x`

**Comment by skypjack** [comment]
Oh, nvm, it's libcxx probably and not clang directly. My fault.

**Comment by speedym** [comment]
In the good news, I can confirm that with NDK r26.0.10792818 (featuring clang 17) I am not seeing the bug, while with NDK r25.18937393 (featuring clang 14) the issue is present.

Regarding clang vs libc++, yeah, I would also say it's much more likely to have been a libc++ issue. I assume it has also been upgraded in NDK r26 which fixed the issue for us. 

I'll close the issue with this comment, because I think we have a good understanding of it, and the steps needed to be done to fix it. @skypjack Thank you for your insightful replies. 🙏

**Comment by skypjack** [comment]
You're welcome. Feel free to reach out if I can help further. 👍
