### ISSUE TITLE
Can't emplace component derived from std::vector

### ISSUE THREAD

**Issue by jjcasmar** [skypjack/entt#1149]
I have a component which derives from std::vector. When I try to add that component to an entity, it doesn't compile.

```
#include <entt/entt.hpp>
#include <vector>

struct S : public std::vector<int>{};

int main()
{
    entt::registry registry;
    auto e = registry.create();
    auto &c = registry.emplace<S>(e);

    return 0;
}
```

This simple code fails to compile with 
```
/opt/compiler-explorer/libs/entt/v3.12.2/src/entt/container/../core/memory.hpp:185:31: error: static assertion failed due to requirement 'std::is_constructible_v<S, const S &, const std::allocator<S> &>': Ill-formed request
```

However, I can make the vector an attribute of the `struct S` and then works fine. 

Is this something expected? Why can't I emplace a struct deriving from std::vector?

https://godbolt.org/z/dcb3YbGWa

**Comment by skypjack** [comment]
First of all, **DO NOT** inherit from classes in the `std::` namespace.
That said, it doesn't work because your type is badly defined:
```cpp
struct S: public std::vector<int> {
    using std::vector<int>::vector;
};
```
https://godbolt.org/z/rve7q1jPf

**Comment by jjcasmar** [comment]
I dont really understand why I need to specify I am using std::vector<int>::vector ctors. Do you have any link where I can read about it?

**Comment by skypjack** [comment]
Unfortunately, that's trickier than this.
At first glance (but get this with a grain of salt, I'm at work and cannot spend much on this), it boils down to uses-allocator construction.
Static traits return true because the class supports it but you don't export the ctors and therefore it fails when it comes to constructing an object.
Typical corner cases of the language, a bit like when you ask the compiler if a vector of `unique_ptr`s is copyable.

**Comment by jjcasmar** [comment]
Fair enough. Thanks!
