### ISSUE TITLE
Include assertion message in underlying `assert` call

### ISSUE THREAD

**Issue by ChrisThrasher** [skypjack/entt#1163]
https://github.com/skypjack/entt/blob/93f7d516f21e5f63422df983c02827ab1c8e050e/src/entt/config/config.h#L45-L48

`ENTT_ASSERT` is implemented such that the error message is dropped. This is fine enough if you're reading the source code but it means that when the assertion actually fires, the error message is not present in the console output. I propose the following modest change:

```diff
diff --git a/src/entt/config/config.h b/src/entt/config/config.h
index 80a33057..4a14c7db 100644
--- a/src/entt/config/config.h
+++ b/src/entt/config/config.h
@@ -44,7 +44,7 @@
 #    define ENTT_ASSERT(condition, msg) (void(0))
 #elif !defined ENTT_ASSERT
 #    include <cassert>
-#    define ENTT_ASSERT(condition, msg) assert(condition)
+#    define ENTT_ASSERT(condition, msg) assert(condition && msg)
 #endif
 
 #ifdef ENTT_DISABLE_ASSERT
```

This does not change the runtime behavior of the assertion whatsoever but what it does do is ensure that the console output includes the string literal. This gives users more information about what actually went wrong.

**Comment by skypjack** [comment]
I'm completely ok with it, that's a good point actually. Feel free to put it in PR or leave this issue open and I'll do it.
Cannot do it right away because I've to pack my stuff and go on vacation before my wife decides to divorce. 😅 
In any case, the change is not so urgent that it can't wait for my return, so we've plenty of time to fix it. 👍

**Comment by ChrisThrasher** [comment]
See https://github.com/skypjack/entt/pull/1164
