### ISSUE TITLE
Proper use of Continuous Loader for client-server sync

### ISSUE THREAD

**Issue by sina-** [skypjack/entt#136]
Hey, 
This has been my design:
1) When a client connects send the full snapshot of the registry using a call to snapshot() with appropriate list of components
```
entt::DefaultRegistry registry;

template<class Archive, class ...ArchiveComponents>
void snapshot(Archive &archive) {
    registry.snapshot().entities(archive).template component<ArchiveComponents...>(archive);
}
```
and on the client side restore the registry with the same list of components using a ContinuousLoader:
```
entt::DefaultRegistry registry;
entt::ContinuousLoader<entt::DefaultRegistry::entity_type> loader(registry);

template<class Archive, class... ArchiveComponents>
void restore(Archive &archive) {
    loader.entities(archive).template component<ArchiveComponents...>(archive);
}
```

2) Every server tick whenever components are updated tag those entities with an empty component that
signals the need for sync:
```
struct NeedsSync{};
registry.accommodate<NeedsSync>(entity);
```
and later send those to the client by taking snapshot of the components for any entity that has been updated:
```
template<class Archive, class ...ArchiveComponents>
void snapshotDelta(Archive &archive) {
  auto view = registry.view<components::NeedsSync>();
  if (!view.empty()) {
    registry.snapshot().template component<ArchiveComponents...>(archive, view.cbegin(), view.cend());
  }
}
```
after the send remove the component:
```
registry.reset<NeedsSync>();
```
and on the client restore them with the same list of components as the server
```
template<class Archive, class... ArchiveComponents, class... Type, class... Member>
void restoreDelta(Archive &archive, Member Type::*... member) {
  loader.template component<ArchiveComponents...>(archive, member...).orphans().shrink(); 
}
```

The problem is that restoreDelta() kills any entity that is not in the delta snapshot. I feel
I am doing something fundamentally wrong, what would be the correct way to do this?

**Comment by skypjack** [comment]
Not sure I got what you're doing (I'm out of home, I read this from mobile), but it looks like you're doing something wrong in your second bullet.

You should either send also the set of living entities each tick or avoid to invoke `shrink` client side.  
The idea behind the loader is that you send a full snapshot each time and therefore you can shrink entities that no longer have a counterpart. However, it seems to me that this isn't your case. You send only parts of the entities each time (but the first one) and the loader cannot know the others are still alive.

**Comment by sina-** [comment]
I get the same result even without `shrink`. Sending full snapshot every tick is quite expensive. How would that actually work? My thinking is that I should sent full snapshot once and every tick I just send the delta, things that have changed in the registry, to reduce the amount of data sent over network.

**Comment by skypjack** [comment]
Oh, I see. The continuous loader resets the components locally before to load the new set. The reason is the same above mentioned: it's meant to satisfy different usage patterns than your.  
On the other side, you're not sending all the instances of a given component C each tick, right? It won't work any time soon this way without changes, I'm sorry.

**Comment by sina-** [comment]
Perhaps that's what I'm doing wrong, or understood wrong. I'm trying to avoid sending all the instances of a component, and only send the ones that have changed. Lets look at it from a different angle, since this library is meant to be used in a game engine, how would you sync the registries in a client and server? 
Won't you use the snapshot? How would you restore that snapshot client side?

**Comment by sina-** [comment]
Well if I send the entire snapshot, then why would I use ContinuousLoader? Why not just do a `registry.reset()` and then `registry.restore()` the entire thing?

**Comment by skypjack** [comment]
No, wait, I mean a single component anyway. The entire set for a single component, not for the whole registry. Sorry if it wasn't clear.

**Comment by skypjack** [comment]
Btw, if the question was _can I do it without snapshot_? The answer is _more or less, yes_.  
Snapshot stuff was created initially to generate full snapshots of a registry (ie up to destroyed entities, that is something you cannot know otherwise). Moreover, it's meant to reconstruct something by keeping intact entity identifiers and versions, again something you cannot do easily otherwise. But it has drawbacks, first of all the fact that it moves around entire sets (that was fine for the sole snapshot loader but I see it could be annoying with the continuous loader).

If you aren't interested in this kind of things, snapshot is not the tool to use. As I said, I'm going to deprecate it anyway because I want to replace it with much powerful tools, so don't expect changes on that part but for bug fixing.

Here the choices are:

* I stick to the usage pattern of snapshot and use it.
* I don't want to follow its rules, I can export things and send them to a client anyway somehow.
* New cool stuff? Interesting, I'll wait for that, I'm not in a rush.

**Comment by vblanco20-1** [comment]
Given that its on the topic, is it logical to use snapshot to copy all the state of a few components you care about into another registry? I was looking to pipeline my game engine and i got everything but a way to separate the state of the game update vs the render update (need to copy all the render related components to a new registry)

**Comment by skypjack** [comment]
> is it logical to use snapshot to copy all the state of a few components you care about into another registry?

@vblanco20-1 More than calling it _logical_, I'd say that it could work. :smile:

**Comment by sina-** [comment]
@skypjack thanks a lot for the help and clarification. Yeah it seems I can't really use snapshots for client-server sync as it is now without trying to work around it. Although without doing a `shrink` my solution should have worked, but for some reason it didn't, maybe I will look a bit closer and try to find out why my entities die when I restore a partial snapshot with ContinuousLoader without `shrink`. 

As for the options, I think I'll wait for your new shinny snapshot replacement :P

**Comment by skypjack** [comment]
You're welcome!! :-)
Is C++17 an option for you? I plan to release most of them only for C++17 actually.

---

I invite you also to join us on gitter to discuss about EnTT and to make more questions in future. There are skilled people in the channel.  
Moreover, I invite you to star the project if you didn't do it yet.

Thanks for using EnTT!!

**Comment by sina-** [comment]
Yep, I'm on C++17. Thanks for making EnTT :)
