### ISSUE TITLE
add registry.view() const member

### ISSUE THREAD

**Issue by pgruenbacher** [skypjack/entt#149]
```
    template<typename... Component>
    entt::view<Entity, Component...> view() {
        (assure<Component>(), ...);
        return { &pool<Component>()... };
    }

    template<typename... Component>
    const entt::view<Entity, Component...> view() const {
        (assure<Component>(), ...);
        return { &pool<Component>()... };
    }
```

so i can have const Registry& being passed around and creating const views from it... const views seems supported from what I can tell

**Comment by pgruenbacher** [comment]
hm nvm my request is more complicated than I thought, I mistakenly had thought my change had fixed my issue. It'd still be nice to have const Registry& that i can pass to read-only systems that can make read-only views, but shrug, i could just update my systems to accept read-only views.

**Comment by skypjack** [comment]
Unfortunately, it's not that easy to do what you are asking for. It's far, far easier to pass const views around than letting the registry create const views.  
This is because of how all the views are defined. They require non const references to the pools to be able to get the job done. However, if you define a const member function in the registry to return a const view, you cannot initialize views with non const references. It would require to change the definition of the views themselves and to separate each of them in two classes: a base one that cast away constness from the pools and offers anyway only const member functions, plus a derived class that gets the non const references to the pools from the base class and offers non const member functions.

Results: const cast all around, twice the number of classes to maintain, quite an ugly codebase to work with and so on.

I tried it in the past, but I preferred not to introduce such a method. I'm just fine now with systems that accepts const views when required and with a clean codebase to work with and to extend.

**Comment by pgruenbacher** [comment]
yea I agree. const views are a better pattern anyways.

**Comment by skypjack** [comment]
I did it finally. See #152 for more details. :smile:
