### ISSUE TITLE
[Dispatcher]: seem's totally broken

### ISSUE THREAD

**Issue by Milerius** [skypjack/entt#154]
Hello i have not used entt since 2.5.0, just updated today and the dispatcher seems completely broken for `this` argument:

```cpp
/home/milerius/Documents/essaie/shiva/vendor/entt/src/entt/signal/sigh.hpp: In instantiation of ‘void entt::sink<Ret(Args ...)>::connect(Class*) [with Class = shiva::ecs::system_manager; Ret = void; Args = {const shiva::event::start_game&}]’:
/home/milerius/Documents/essaie/shiva/modules/ecs/shiva/ecs/system_manager.hpp:337:64:   required from here
/home/milerius/Documents/essaie/shiva/vendor/entt/src/entt/signal/sigh.hpp:187:33: error: no matching function for call to ‘entt::sink<void(const shiva::event::start_game&)>::connect<(& shiva::ecs::system_manager::receive)>(shiva::ecs::system_manager*&)’
         connect<&Class::receive>(instance);
```

```cpp
 dispatcher_.sink<shiva::event::start_game>().connect(this);
      dispatcher_.sink<shiva::event::quit_game>().connect(this);
      dispatcher_.sink<shiva::event::add_base_system>().connect(this);
      dispatcher_.sink<shiva::event::enable_system>().connect(this);
      dispatcher_.sink<shiva::event::disable_system>().connect(this);
```
```cpp
void system_manager::receive([[maybe_unused]] const shiva::event::quit_game &evt)
    {
      log_->debug("quit_game event received");
      shiva::ranges::for_each(systems_, [](auto &&vec) {
          shiva::ranges::for_each(vec, [](auto &&sys) {
              sys->disable();
          });
      });
    }

    void system_manager::receive([[maybe_unused]] const shiva::event::start_game &evt)
    {
      timestep_.start();
      start_ = clock::now();
    }

    void system_manager::receive(const shiva::event::add_base_system &evt)
    {
      auto sys_type = evt.system_ptr->get_system_type_RTTI();
      [[maybe_unused]] auto &system = add_system_(
          std::move(const_cast<shiva::event::add_base_system &>(evt).system_ptr),
          sys_type);
      if (evt.prioritize) {
        prioritize_system(system.get_name(), evt.system_name, sys_type);
      }
    }

    void system_manager::receive(const shiva::event::enable_system &evt)
    {
      auto system_ptr = this->get_system_by_name(evt.system_name, evt.sys_type);
      if (system_ptr)
        system_ptr->enable();
    }

    void system_manager::receive(const shiva::event::disable_system &evt)
    {
      auto system_ptr = this->get_system_by_name(evt.system_name, evt.sys_type);
      if (system_ptr)
        system_ptr->disable();
    }
```

You didn't test in your unit test with this as instance connector!
Seem's to be a huge regression from my side, i didn't change one line of my code since 2.5.0

**Comment by skypjack** [comment]
Tests contain something to verify it. Even though they don't use `this`, they use a pointer to an instance of an object. Both go through the same path.  
Your error is due to the fact that the C++17 version uses an `auto` template parameter to get the pointer to member. So, no longer this:
```
template<Ret(Class:: *Member)(Args...), typename Class>
```
You've this instead:
```
template<auto Member, typename Class>
```

Pros are evident. Being `noexcept` part of a function type as well as `const`, it handles everything transparently. Moreover, functions don't have anymore to have a fixed signature. They are all fine as long as they are invokable with the given arguments.  
In other terms, for a signature `void(int)` you can use a function type `void(double)` for your member and it works like a charm in any case.

Cons is that overload are no longer resolved silently under the hood and you must specify explicitly the one to use.

Fortunately, we can work around cons. On the other side, I didn't find another approach that has the same cons. Therefore I went ahead with the `auto` template parameter. That's all.  
To resolve the overload you can either `static_cast` or use `entt::overload` (see `core/utility.hpp`).
