### ISSUE TITLE
Get Owner of Component

### ISSUE THREAD

**Issue by carlfindahl** [skypjack/entt#164]
Assuming that I only have a reference to a component available, would there be any way for that component to get the entity it belongs to, and through that access other components? The best solution I've come up with so far is iterating all entities with the component until the one I want appears, but perhaps I've overlooked a better way of doing this that already exists. Couldn't find anything in the wiki or in other issues.

```C++
template<typename ComponentType>
uint32_t getOwner(const ComponentType& component)
{   
    auto view = registry.view<ComponentType>();
    for (auto e : view)
    {
        if (&view.get(e) == &component)
        {
            return e;
        }
    }

    /* It should never come here as all components logically should have an owner */
    return entt::null;
}
```
I'm not sure if this is something you want to have as a part of the library at all, but I had a use for it, so thought I'd ask! Thanks a lot for your great work!

**Comment by Kerndog73** [comment]
There is no mapping from the component to the entity ID. If you only have the address of the component you're looking for, the only way to get the entity ID is to iterate.

However, it is recommended that instead of holding onto component references, you hold onto entity IDs. There is a fast mapping from entity ID to component.

```C++
instances[reverse[entity & traits_type::entity_mask]]
```

A bitwise `&` and two array lookups. It's fast! Holding onto a reference to the component isn't much faster than storing the entity ID.

Holding onto a reference means that you run the risk of having a dangling reference. When you assign a component to an entity, a `std::vector` will be resized and potentially reallocated, leaving you with a dangling reference. An entity ID doesn't suffer from this problem.

**Comment by skypjack** [comment]
>would there be any way for that component to get the entity it belongs to, and through that access other components?

There is a trick to do that actually but 1) you didn't star the project, so I won't tell you :smile: 2) @Kerndog73 pointed out the right problem.

>Assuming that I only have a reference to a component available

You should never ever store aside references or pointers to components, they aren't guaranteed to be consistent in time. Use entity identifiers instead.  
Keep in mind that `EnTT` does reallocate elements in the pools when needed in order to give you fast iterations and some nice-to-have features like a pointer to a packed array of components.

>I'm not sure if this is something you want to have as a part of the library at all, but I had a use for it

Before to tell you how to do that, may I ask you what's your use case?

**Comment by carlfindahl** [comment]
>  1) you didn't star the project, so I won't tell you

Well I fixed that, as this definitely deserves one!

Storing the entity ID seems like the better options now that it has been pointed out. @Kerndog73 is `instances` and `entity_mask` part of the library? 

> Before to tell you how to do that, may I ask you what's your use case?

All right, at the moment some of my components have some member-functions (they are all structs), but I use member functions to bind functionality to LUA, so anyone scripting can't change just anything on components. And some of those functions trigger events that  contain data about which entity fired it, which is the reason I had to find a way to get the entity from within a component. This is my first project using a proper ECS, so it might not be perfectly idiomatic, but it gets the job done. Within C++ I just access members directly, and it's a non-issue.

Thank you very much for swift replies and some great tips on how to better use the library!

**Comment by skypjack** [comment]
You're welcome!! Feel free also to join us on gitter if you want to discuss your doubts with other users.  
I confirm that I'd use the entity identifier if I was you, because you don't know if the component is going to be moved during its lifetime.  
Moreover, identifiers contain a version and you can test them at any time to know if they are still valid or have been destroyed/recycled in the meantime. :+1: 

I'm closing the issue as invalid. Feel free to reopen it if you think you didn't get a proper answer.

Enjoy `EnTT`. :+1:
