### ISSUE TITLE
Using registry.view with the same parameters inside two different files causes weird behavior

### ISSUE THREAD

**Issue by nfwGytautas** [skypjack/entt#173]
So I was trying to make a batching system for rendering with EnTT however I ran into a weird bug.

ECS::Registry is just `using Registry = entt::registry<Internal::entt_ENTITY_type>;`
Where `using entt_ENTITY_type = std::uint32_t;`

So I wrote this code and it works without flaws when it is the only one using .

**Transform component contains 3 vectors for position, rotation, scale**
**MeshFilter component contains another vector of meshes that the entity uses**

Renderer.h

```
void Render(ECS::Registry& aRegistry)
{
	aRegistry.view<Components::Transform, Components::MeshFilter>().each([&](const auto, auto &transform, auto &meshFilter) {
		//Some render code
	});
}

```

However when I add another file/system

BatchManager.h

```
void Update(ECS::Registry& aRegistry, float aDelta)
{
	aRegistry.view<Components::Transform, Components::MeshFilter>().each([&](const auto, auto &transform, auto &meshFilter) {
		//Some batching code
	});
}
```

Suddenly neither of them works.
But if I comment out one of them suddenly the other starts working

_NOTE: This is a dll, however both systems are controlled by the engine and user doesn't use them.
But I saw in the wiki that I should add this,_

```
namespace entt {
    template class __declspec(dllexport) family<struct internal_registry_component_family>;
    template class __declspec(dllexport) family<struct internal_registry_handler_family>;
}

```  

_I did and got these errors when writing it after including_ 

```
Error: C2071 public: static unsigned __int64 const entt::family<entt::internal_registry_component_family>::type<Triton::Components::Transform>': 
illegal storage class	entt\src\entt\entity\registry.hpp 165	
```

_Writing it before include gave ~100 errors_

Maybe I read the documentation wrong but I can't figure out what is causing this behavior.
Thanks for  your help.

**Comment by skypjack** [comment]
Are you on Windows?

**Comment by skypjack** [comment]
`EnTT` isn't meant with shared objects in mind. It uses some inline variables from C++17 internally and unfortunately they don't work as expected on Windows because of how libraries are linked on such a platform. Everything works like a charm on most of the other platforms instead.  
To sum up: if you pass a registry across boundaries, things can break under certain circumstances. What you're observing is just a symptom of the problem. It's not in the views actually.

To be honest, it's not even that difficult to work around it. It would be enough to provide a way to allow users to replace the `family` class with a custom implementation when it comes to working with shared libraries.  
However it's something still to develop, mainly because I don't need it and therefore I never worked on this. It's in the TODO list, but kind of low priority at the moment. I'm sorry.

Also other solutions exist, like isolating shared libraries from the registry through dedicated classes.  
There are some other issues where the same topic was discussed. You can search them. A guy (the author of `shiva`) solved somehow the problem without changes but I don't remember how he did it.

It's interesting to know that the export stuff doesn't work anymore. I copied it from a discussion I had on an issue. I must admit that I didn't test it in the last... uh, six months?  
If you confirm that it doesn't work, probably it's worth to get rid of that paragraph.

**Comment by skypjack** [comment]
Issues you can read to go a bit further on the topic are #111 #113 #123

**Comment by nfwGytautas** [comment]
Reading the previous issues you came to the same wall that I did when trying to create a very basic ECS, that when dealing with dll passing the same component type increments an identifier. I couldn't figure a way to work around it in my own system, but maybe I will be able to do so in this one.

**Comment by skypjack** [comment]
Yeah, well, if you come up with a good solution to propose, feel free to ping me. We could also integrate it directly into `EnTT`. :+1:

**Comment by skypjack** [comment]
I thought a bit to this. Another possible solution is to use `ident` in place of `family` for identifiers when shared libraries are involved.  
It increases a bit compilation time, because `ident` requires the full list of components at compile time. But it would also solve at once the problem being the identifiers directly built-in with the registry. Moreover, the whole code base wouldn't be affected by this change.

**Comment by nfwGytautas** [comment]
How do I tell EnTT to use `ident` I didn't find in it in 

> Crash Course: entity component system

or do I have to code it in myself?
