### ISSUE TITLE
notification when a tuple of components is added

### ISSUE THREAD

**Issue by trashuj** [skypjack/entt#183]
Hello again,

I would like to add a texture and a position component to display a texture on screen. Now I need to first create the texture, and then display it.

Afaik there are views to list all existing tuple (which i use to draw), connect() to be notified when a component is added,
but nothing to be notified when a tuple is added (ie when an entity has all the required components).

I currently connect()ed with the texture component, but it's kind of limiting since the texture component might be used later with another component (which doesn't involve position component and requires a different process).
I suppose i could track manually if the view content changed, but maybe I missed something and there is a better solution.

thanks a lot in advance!!
Ju

**Comment by Kerndog73** [comment]
To render all entities that have positions and textures:

```C++
reg.view<Position, Texture>().each([] (Position pos, const Texture &tex) {
  // render texture at position
});
```

Why do you need event listeners?

**Comment by trashuj** [comment]
because before rendering it, i need to create it (only once when it's added
ideally)

**Comment by Kerndog73** [comment]
What do the three `it`s refer to in that sentence? 😄

To create an entity that can be rendered:

```C++
auto e = reg.create();
reg.assign<Position>(e, 17, 23);
reg.assign<Texture>(e, "Cool texture.png");
```

What are the event listeners for?

**Comment by skypjack** [comment]
@trashuj I'm on the same line with @Kerndog73 - I'm not getting what's the actual problem to be honest.
Cna you be more specific about your goal? Maybe we are missing something.

**Comment by trashuj** [comment]
thanks a lot for taking the time to reply!
and sorry if i'm unclear :$
"it" refers to the texture.

basically what i need to do is:
- when the texture is added (ie when both components are assigned), create
openGL buffers
- then, in the update loop, render the buffers.

Using the view is perfect to render, but I'd like to know when both
components are added so I can actually create the texture.

Let's imagine for example that i have 2 systems:
one watching texture and position2D components (to display 2d textures)
another watching texture and 3Dmodel components (to display a model
textured)

The texture creation/usage would be different for both, so i need to know
when both are added.
Thus it would be convenient to know when both are added, so i can start the
proper treatment (and then use a view to iterate on my entities and render
them)

**Comment by Kerndog73** [comment]
Create two factory functions. One for 2D textures and one for 3D models. Just do the separate texture and array buffer initialization in the two separate factory functions.

**Comment by skypjack** [comment]
Ok, I got what you want to do. :+1:  
Signals for _patterns_ (multiple components) aren't available, mainly because pools are separated and signals are _per-pool_. To allow users to connect to patterns would require a bit of boilerplate all around.  
That being said, there are three ways you can do that:

1. The way suggested by @Kerndog73 .

2. Wait until reactive systems are introduced. :-) They are already in the TODO file and do more or less what you're looking for among the other things. However, I've not an eta for them yet.

3. Attach the same listener to construction and destruction sinks of the two components and check if the entity has what you want before to _do things_. This is close to how groups work under the hood (well, they do that in an optimized way, but the idea is the same).

**Comment by trashuj** [comment]
Thanks a lot !! :D

I actually like idea #3, it's not that bad.

@Indi I'm not sure i get your idea.
"how" to create is not really the issue here, but "when" to create is.

**Comment by skypjack** [comment]
Usually iterations are along critical paths, creation/destruction is not. You won't notice an extra `if` there.  
The fact is that it's tricky to allow signals for _patterns_ and you can always work around the need. Therefore I don't thinks it's worth it to add them.  
My two cents obviously. :+1: 

I'm closing the issue because there is nothing to do in `EnTT` for this, but feel free to continue discussing here if you've any other doubt.

**Comment by vblanco20-1** [comment]
There is a way i already use myself for this case.
Dont use 2 components, use 3
Position, Renderer, and "GL State" or similar

You have a view that searches for Position, Renderer, and Not "GL State". This is the system that initializes your opengl state of the renderer.

Then you have a system that searches for Position, Renderer, and Gl_State, and use that to render

```cpp
//pseudocode
struct Sprite{
string TextureName;
rect TextureRect;
}
struct Position{
vec2 pos
}
struct Sprite_GPUState{
GLUINT textureID;
GLUINT vertexBuffer;
}

void RenderingSystem(entt::registry& Registry){

auto firstview = registry.view<Position,Sprite>(<Sprite_GPUState>  );
for(auto entity : firstview)
{
registry.assign<Sprite_GPUState>(entity, CreateSpriteForEntity(entity) );
}

auto renderview= registry.view<Position,Sprite,Sprite_GPUState>(  );
for(auto entity : renderview)
{
render stuff
}

}
```

**Comment by trashuj** [comment]
thanks that looks interesting!
can we filter out/exclude components from views though?

**Comment by Kerndog73** [comment]
@trashuj You can use groups to do that.

```C++
auto group = registry.group<Position, Sprite>(entt::exclude<Sprite_GPUState>);
```

Groups are kind of like views but implemented a bit differently. See the [wiki](https://github.com/skypjack/entt/wiki/Crash-Course:-entity-component-system#groups) for details.

**Comment by trashuj** [comment]
Thanks!
Since i read " a given component can belong only to one group, so users
have to define groups carefully to get the best out of them", I ruled out
groups altogether since i want to be able to reuse components in different
systems.

**Comment by skypjack** [comment]
@trashuj it doesn't mean you can't use a type with multiple groups. As an example:
```cpp
auto g1 = registry.group<A>(get<B>);
