### ISSUE TITLE
Why is it bad to store a view? 

### ISSUE THREAD

**Issue by Dimrok** [skypjack/entt#187]
Hi,

I want to ask you for a clarification about views. It's mentioned in the code documentation 

> As a rule of thumb, storing a view should never be an option.

However, the main documentation states that:

> Views and Groups
> [...]
> Briefly, they are a good tool to enforce single responsibility. A system that has access to a registry can create and destroy entities, as well as assign and remove components. On the other side, a system that has access to a view or a group can only iterate entities and their components, then read or update the data members of the latter. 

How a system can have access to a view and only a view if it can't store it? Also why shouldn't I store a view? The documentation only mentions that creating a view is quick and cheap but not why storing a view is bad.

I see solutions but they are less obvious than just storing an instance of a view.

To give a better context, let's imagine an `AudioSystem` in an entity-based environment. I don't want that system to be able to create/remove entities. If I can't store a view, the right solution is to pass a lambda (e.g. `[&registry] { return registry.view<CanProduceSound>(); }` over a view (e.g. `entt::view<CanProduceSound>&&`)?

Thanks.

**Comment by skypjack** [comment]
>How a system can have access to a view and only a view if it can't store it?

How can a system have access to a view to store aside? A system can receive the view as a parameter of an hypothetical `update` function, as well as an argument to the constructor. No need to ask for the registry.

>The documentation only mentions that creating a view is quick and cheap but not why storing a view is bad.

For what concerns runtime views, the documentation says (emphasis mine):

>Runtime view are extremely cheap to construct and should not be stored around in any case. They should be used immediately after creation and then they should be thrown away. **The reasons for this go far beyond the scope of this document**.

Shortly, it could happen that the underlying data structures required for the view don't exist yet when a registry generates the view itself. Because of that, the view is somehow _broken_ and will behave as if it's empty at each invocation. There is no way to literally _fix it_ once the ownership is transferred. Therefore, all what you can do is to throw it away.  
Of course, there is a workaround for that (not mentioned in the documentation). Moreover, runtime views are beasts rarely used and in different contexts.

From what concerns compile-time views, the current implementation allows you to store them aside actually. However, I cannot guarantee they won't bind to (let me say) _unstable_ underlying data structures of the registry in future (mainly things that can move around and thus invalidate pointers). It's unlikely to happen to be honest, but who knows?  
Because of that, mine is an advice for as _safe use_ of a view now and forever, but feel free to not follow it. Most likely you'll never ever have problems, don't worry.

---

That being said, I invite you to join the gitter channel if you have other questions like this one. There are smart developers that can really help you there. Also, don't forget to star the project if you like and use it. I hope it fits with your requirements.

If you received your answer, please close the issue. Otherwise feel free to continue the discussion.

**Comment by Kerndog73** [comment]
Conceptually, a system is just behavior so I declare systems like this:

```
void playSounds(entt::registry &reg, AudioContext &ctx) {
  // Create a view, iterate CanProduceSound components, play sounds
}
```

That's my two cents. It doesn't really answer your question though!

**Comment by skypjack** [comment]
Yeah @Kerndog73 I use to have free functions as systems too. However, sometimes they ask directly for a view as a parameter and I submit the registry through the `as_view` utility to satisfy the requirement. This way I'm guaranteed that the system won't create entities and components any time soon.

**Comment by Kerndog73** [comment]
@skypjack Oh, using `as_view` seems like a really smart idea. You can avoid having to type out the list of components in the calling code. Genius! Although, you still have the component list in two places (header and implementation).

I like the idea of ensuring that a system can only iterate components but I'm not really a fan of enforcing **which** particular components can be iterated.

**Comment by Dimrok** [comment]
Thanks for both your answers, I was to focus on having my hypothetical system to own the view but I can certainly pass it when needed (or use a free function).

> That being said, I invite you to join the gitter channel

I was looking for a Slack or a gitter but it wasn't mentioned in the README. I should have look by myself. 

> If you received your answer, please close the issue. Otherwise feel free to continue the discussion.

Answer received, sir!

**Comment by skypjack** [comment]
>I was looking for a Slack or a gitter but it wasn't mentioned in the README. I should have look by myself.

Oh, I'm sorry. There is the gitter badge on the top of the readme file but probably people don't see it. You're just confirming this. I'll add a dedicated section to mention the channels to use to contact me. Thanks for pointing it out. :+1:
