### ISSUE TITLE
errors on Conan entt/3.x.y-WIP@skypjack/stable

### ISSUE THREAD

**Issue by loic-lopez** [skypjack/entt#189]
Hello, 

I have used this sample code from : [leinnan.github.io](https://leinnan.github.io/blog/conan-adventuressfml-and-entt-in-c.html)

i use Entt with conan and these errors appears:

```
error: static_assert failed
    static_assert(sizeof...(Component) > 1);


error: no member named 'each' in 'entt::view<unsigned int>'
    registry.view().each([dt](const auto, auto &pos, auto &vel) {


error: declaration of variable 'registry' with deduced type 'entt::registry' requires an initializer
```

Thanks for reply.

**Comment by Kerndog73** [comment]
The first two errors are because you you didn't pass the component types to `registry::view`. The example you found is broken. I suspect the `< >` were being parsed as HTML so they disappeared. See the wiki and the README for working examples. Also see the [EnTT in Action](https://github.com/skypjack/entt/wiki/EnTT-in-Action) section for projects an articles about EnTT.

To fix the first two errors, try `registry.view<position, velocity>()`. For the third error, try `entt::registry<> registry;`.

**Comment by skypjack** [comment]
The errors are in the blog post you linked. @Kerndog73 correctly pointed out the solutions. Ask the author to fix them. Thanks.
