### ISSUE TITLE
processes' destructor is not called when aborted

### ISSUE THREAD

**Issue by trashuj** [skypjack/entt#211]
quick test:
```cpp
class SystemTest : public entt::process<SystemTest, unsigned int>
{
public:
	SystemTest()
	{
		LOG("constructor");
	}
	virtual ~SystemTest()
	{
		LOG("destructor");
	}
};
```
then in code:
```cpp
entt::scheduler<std::uint32_t> scheduler_;
scheduler_.attach<SystemTest>();
scheduler_.abort(true);
scheduler_.update(1); // needed?
```

note that the destructor of `SystemTest` is not called when aborting the process,
but only when the scheduler is destroyed.

**Comment by Kerndog73** [comment]
I think this might be expected behaviour.

When you attach a process to the scheduler, it is in an `UNINITIALIZED` state ([268](https://github.com/skypjack/entt/blob/master/src/entt/process/process.hpp#L268)). A process is only aborted if it is alive ([186](https://github.com/skypjack/entt/blob/master/src/entt/process/process.hpp#L186)). A process transitions into a `RUNNING` state then you tick it ([234](https://github.com/skypjack/entt/blob/master/src/entt/process/process.hpp#L234)).

This means that you must tick your process to initialize it before you can abort it. Here's a test:

```C++
#include <iostream>
#include <entt/process/scheduler.hpp>

class Test : public entt::process<Test, unsigned> {
public:
  Test() {
    std::cout << "Test()\n";
  }
  ~Test() {
    std::cout << "~Test()\n";
  }
};

int main() {
  {
    entt::scheduler<unsigned> sch;
    sch.attach<Test>();
    std::cout << "Attached\n";
    // try commenting this line
    sch.update(1);
    std::cout << "Updated\n";
    sch.abort(true);
    std::cout << "Aborted\n";
    sch.update(1);
    std::cout << "Updated\n";
  }
  std::cout << "Destroyed\n";
}
```

And it's output:

```
Test()
Attached
Updated
Aborted
~Test()
Updated
Destroyed
```

Maybe we should allow aborting uninitialized processes? I don't see the harm. All that would be required is changing [this line](https://github.com/skypjack/entt/blob/master/src/entt/process/process.hpp#L186).

**Comment by skypjack** [comment]
I see, thanks @Kerndog73  
Probably the best choice is to tick processes as soon as they join the running queue of a scheduler. Top level processes would get ticked and therefore exist the uninitialized state as soon as they are registered. Children would be implicitly ticked when they replace their parents instead.  
This would solve also another problem, that is that the first tick is currently a no-op that just initializes pending processes. As an user, if I register a process I want probably to see it up and running immediately during the next tick and not two ticks later on.

**Comment by skypjack** [comment]
Uhm @Kerndog73 no, I was wrong, the problem I mentioned doesn't exist.  
Processes fall through uninitialized and running state during the first tick actually.
This is probably what makes things weird and it means that the last tick of a parent and the first tick of a child happens during the same update. At a first glance, this is wrong.  
Yeah, probably the best is to break the switch statement and to invoke `tick` implicitly to initialize processes. This should solve both the problems at once.

**Comment by skypjack** [comment]
@trashuj branch `wip` contains a hopefully correct version that gets processes out of the uninitialized state when they join the running queue of a scheduler.  
I've also removed the `void *` from the `init` function because it wasn't consistent (it wasn't so even before this change, I've just cleaned it up a bit). Doc have been updated as well.

Let me know if it works as expected before I merge everything on `master`. Thanks.

**Comment by trashuj** [comment]
I would actually rather not tick/update when attaching the process.
in my case i attach them all during init phase, and update them all during update (when all init is done)

**Comment by skypjack** [comment]
They are just initialized when you attach them to the scheduler. Their update function isn't invoked.  
This is consistent with what you said:
>i attach them all during init phase, and update them all during update (when all init is done)

Attach during init phase ==> `init` is invoked (if present).  
Update during update ==> `update` is invoked.

**Comment by trashuj** [comment]
ah sorry, i thought you wanted to change this.
i tried wip, so it works only when i update the scheduler after the abort.
i suppose that's the expected behavior :)

**Comment by skypjack** [comment]
Yeah. `abort` put the process in an `ABORTED` state, but you've to tick it to the mark the same as `FINISHED` and have it pop out the running queue. This is expected.
Can I merge it on `master`? Is the issue solved?

**Comment by trashuj** [comment]
yes it seems all right to me :) THANKS!
