### ISSUE TITLE
3.0 status? safe to use for new project?

### ISSUE THREAD

**Issue by Deins** [skypjack/entt#222]
I want to use entt for my hobby project. How safe is to use latest v3 version, or how many breaking api changes are planned etc? Or is there known broken things in current v3 version. I don't mind doing small refactoring as I and entt advance, but I  also don't want to waste to much time unnecessarily if using v2 and migrating after v3 release is easier.

Thanks in advance :)

**Comment by skypjack** [comment]
I'm glad you decided to use `EnTT`. If your project is going to be an open source one, ping me to put it in the wiki when _ready_. :+1:  
Feel free also to join the gitter channel if you have questions or want to discuss your doubts with other users.

Of course, `master` is stable and there aren't breaking changes planned so far. In any case, I'll change the major and/or minor version if they should come. In general and as a side note, I prefer to change the major version of my projects when I switch to a new revision of the standard or when I drastically change the internals and the API. For (let me say) _small_ braking changes, it's likely that I'll change the minor version and document them in details.  

`EnTT` is actually ready to cut a `v3`. Please, keep open the issue so that it will remind me to do that the next week. :+1:

**Comment by Milerius** [comment]
Don't forget to update the Conan package at the same time @skypjack

**Comment by skypjack** [comment]
Good point @Milerius updated the test file for conan. :+1:

**Comment by skypjack** [comment]
I'm writing the release note for `EnTT` v3. It's... huge!  
I'll publish it most likely when I'm back home on May, the 2nd. :+1:

**Comment by Milerius** [comment]
Glad to hear

**Comment by skypjack** [comment]
Created tag `v3.0.0`. :+1:
