### ISSUE TITLE
Rationale for service_locator class?

### ISSUE THREAD

**Issue by ColinH** [skypjack/entt#230]
Hi, I'm having a hard time understanding the `service_locator` class since it is effectively a global variable containing a shared pointer to anything, why would I choose a `service_locator` over a global variable of type `inline std::shared_ptr< Service >`?

**Comment by Kerndog73** [comment]
[Service locator pattern](http://gameprogrammingpatterns.com/service-locator.html)

**Comment by ColinH** [comment]
@Kerndog73 I understand the pattern, I'm just wondering why `inline std::shared_ptr< Interface >` isn't a reasonable implementation, i.e. why the shared pointer needs to be wrapped in a class that doesn't do anything.

**Comment by Kerndog73** [comment]
Same answer as before: a layer of abstraction. It's not a `std::shared_ptr` it's a service locator.

**Comment by ColinH** [comment]
My point is that a global shared pointer can also be a "service locator" since it offers the exact same functionality, just without an extra class.

**Comment by skypjack** [comment]
The first reasons that come to my mind.

```
service_locator<audio>::get().mute();
```
Tells me exactly what I'm working with, more than:
```
global_audio.mute();
```

Moreover, the rationale is to allow for future changes without them being breaking ones.  
To be honest, this time I've almost failed, mainly because the weak pointer is directly exposed for laziness. That's it by the way. The handles are really opaque data structures, this one isn't perfect but gets the job done for what I need at the moment.

---

Consider that `EnTT` is a project I develop for free in my free time. So, when I talk about future changes usually I mean - _something I've in mind and I'd like to do tomorrow, but I'll do most likely when I'll have an actual need for it_.

**Comment by ColinH** [comment]
My tendency is to not add complexity until it is actually needed, but API stability is of course also a good goal...

PS: I understand the limits of developing open source libraries in one's free time, it's the same for me.

**Comment by skypjack** [comment]
Yeah, they are the two alternatives. Both are valid actually.  
I usually prefer to develop stub for the stuff I'll add sooner or later so as to minimize impact on _other_ codebases, at least when these stubs are a matter of a few lines of code.
