### ISSUE TITLE
wiki: add parallel for_each sample to Crash Course: ECS 

### ISSUE THREAD

**Issue by The5-1** [skypjack/entt#231]
The chapter on Multi-threading is the only one that does not have an example.
Something like this from Paul would certainly help:
```Cpp
std::for_each(std::execution::par_unseq, multiView.begin(), multiView.end(), [&multiView](entity entity) {
	auto& pos = multiView.get<Position>(ent);
	const  auto& vel = multiView.get<Vel>(ent);
	pos.poistion += glm::normalize(vel.vector);
	});
```

**Comment by skypjack** [comment]
Looks fine.

I'm adding a note for when I'll find the time to edit the wiki.  
It's worth mentioning the (let me say) _issue_ related to the input iterators vs forward iterators that is due to the current revision of the language. Moreover, I'd describe the future plans for iterators (entity only vs _proxy object_ and multi-pass guarantee), mainly because they represent a breaking change in a sense.
