### ISSUE TITLE
Reflection system static memory

### ISSUE THREAD

**Issue by Lawrencemm** [skypjack/entt#252]
I'm interested to learn about the design decision to have the collection of meta types living in what appears to be a global static linked list.

Usually I would frown upon such things, I could be wrong but I would have thought it better to have something like an entt::reflection_registry type or something to hold all the reflected types which you could destroy/recreate at will and potentially have different collections of meta types for the same set of c++ types but for different purposes/with different properties attached.

The system itself appears to be quite elegant, nice and usable.

**Comment by skypjack** [comment]
>I'm interested to learn about the design decision to have the collection of meta types living in what appears to be a global static linked list.

Indeed, you got it right. It's an implicit list of objects. This works out-of-the-box without having to create and keep alive a _meta manager_.  
I thought more than once of adding a sort of _dual mode_ where one can decide between having a static implicit list or a runtime non-static list bound to a specific object. Mainly because static stuff made with inline variables doesn't work well across boundaries on Windows (namely DLLs). However, I don't really need it at the moment and therefore I haven't worked on this feature yet.  
The way it works right now is fine for my purposes, so more will come in future either when I find the time to implement it or when someone decides to sponsor the project and this feature in particular or even when someone decides to make a contribution in this sense. :-)

>The system itself appears to be quite elegant, nice and usable.

I'm glad you like it. Are you using `EnTT` already?

**Comment by Lawrencemm** [comment]
I'm considering using this library for my hopeful game engine project which is in its infancy. Just going through the process of figuring out how to make components out of things now.

**Comment by skypjack** [comment]
Sounds good. I'm glad you like it.  
Feel free to ping me if you have any question or feature request. I also invite you to join the gitter channel if you plan to work with `EnTT`. There are many smart people there and you can find the help you need when you've a question. :+1: 

Any other concern about the meta system?

**Comment by Lawrencemm** [comment]
That about does it, thanks for everything!
