### ISSUE TITLE
Snapshot loader: don't reset registry and add collision policy

### ISSUE THREAD

**Issue by Lawrencemm** [skypjack/entt#268]
I am trying to create "restore points" for my registry. I want to use the loader to _overwrite_ components that already exist.

I'd like to propose removing the call to `reset` in the contructor for the registry.loader, and add a policy for what to do if the registry contains an entity with the same id as one encountered in the snapshot archive.

A few of the policies would be:
assert: raise an assertion fault if an entity id from the archive exists in the registry
overwrite: overwrite components of entities in the registry if they exist in the archive
ignore: ignore components from the snapshot if they already exist in the registry.

I'm open to suggestions for better/simpler ways to achieve what I want.

**Comment by skypjack** [comment]
Snapshot is meant to restore a save point as-is. Removing the reset would create room for inconsistencies (eg the entity could have been recycled and therefore you're rebuilding something that is all the ways wrong).  
The continuous loader takes in consideration also this aspects and overwrite when needed, re-create otherwise.

Not sure the change you propose is an improvement tbh.  
The risk is to make the snapshot loader misleading instead.

What's exactly your use case? Are you sure this isn't an XY-problem?

**Comment by Lawrencemm** [comment]
I guess it is probably as you say an XY problem. I might just maintain a forked version with a small change until I move past this issue in my own code.
