### ISSUE TITLE
Component destructor call

### ISSUE THREAD

**Issue by gpufreak** [skypjack/entt#283]
Hello!
I've got a question regarding something that I've spotted while using the lib, now it's getting me quite some headaches.

Look at this sample:
```cpp
class velocity
{
public:
	velocity(float f1, float f2) : x(f1), y(f2) {}
	~velocity() 
	{
	}
	float x, y;
};


// somewhere below in code
auto ent1 = registry.create();
auto ent2 = registry.create();
registry.assign<velocity>(ent1, 12.0f, 23.0f);
registry.assign<velocity>(ent2, 1.0f, 1.0f);
```

On the second assignment for entity `ent2` the velocity destructor is called for `ent1`. It's a bit weird, maybe I don't understand it, but I was pretty sure that components live independant of each other. Because other systems reference that component, at some point it's cleaned and my app breaks.

Does that mean that I can't hold references to component instances and that for any component I need to use `registry.view<velocity>` ?
Thanks!

P.S. `Entt` is pretty nice and easy to integrate! Keep the good work going!

**Comment by OvermindDL1** [comment]
Think of it this way, what if you put the velocity in a `std::vector` with space for 1 element, then you put in a second, it has to reallocate the size, that's basically what's going on here, it 'grows' as necessary.  Remember, never ever reference the memory location of a component or entity, only keep entity handles around and access it that way.

**Comment by skypjack** [comment]
As @OvermindDL1 correctly pointed out, a pool grows and shrinks when needed. You should retain external handles (namely entity identifiers) rather then  references to components.  
Would you store aside a reference to an element in a vector or would you save its index? Since a vector can reallocate, I would use the latter. `EnTT` offers entity identifiers instead of indexes but the reason for which you should use them and avoid references is more or less the same.

---

As a said note, an upcoming feature is meant to allow different pools when needed and one of them will be designed probably so as to guarantee stable pointers.  
Stay tuned. :wink:

**Comment by gpufreak** [comment]
Okay, that's also what I had in mind.

I was trying to integrate Bullet's MotionState into my engine, to update my transform components when collision or forces happen. I'll try to redesign it.

Thanks for the quick answer! 💪

**Comment by skypjack** [comment]
You're welcome. Thank you for using `EnTT`.  
Feel free to ask if you need help or join the gitter channel (link in the README) if you have any question. :wink:
