### ISSUE TITLE
Bazel Support

### ISSUE THREAD

**Issue by zaucy** [skypjack/entt#287]
Would the maintainers here be interested in supporting [Bazel](https://bazel.build/)? I have forked this repository here [bazelregistry/entt](https://github.com/bazelregistry/entt), but it would be great to have support on the official repository.

The fork I created is a work in progress and I wrote up several issues over there that I will eventually get to. If the consensus is positive I'd be willing to help in any bazel related issues that arise here in the future.

**Comment by skypjack** [comment]
Hi @zaucy 

Thanks for your interest in the project.
I must admit I've never used Bazel but I've no reasons not to support it, especially if someone is willing to help with that. :wink:

Just a couple of questions:

* I guess the answer is _yes_ here. I'm asking just to be sure: is it possible to keep it in the project along with cmake and the others, so that it won't be a breaking change?

* Would you consider to close the issues currently open on your side before to merge it upstream?

I'd like it to be fully working before the merge.

**Comment by zaucy** [comment]
> is it possible to keep it in the project along with cmake and the others, so that it won't be a breaking change?

Yep that is not a problem!

> Would you consider to close the issues currently open on your side before to merge it upstream?

Absolutely! I fully intend to fix the issues I have made on the fork before even making a pull request. ^^

**Comment by skypjack** [comment]
So, why not! Go on. :wink:

Do you prefer to keep this issue open until it's done, so as to track your progresses?  
Otherwise feel free to close it and make a PR whenever you're ready.

I'm at your disposal for any question. :+1:

**Comment by zaucy** [comment]
I'm okay either way. How about we close it once the PR (https://github.com/skypjack/entt/pull/291) has been merged :)

**Comment by skypjack** [comment]
My only concern is: does it make sense at all to compile also tests with bazel?
So far, put aside the cmake build system (the original one for this project), all the other packaging tools or similar have been integrated so as to be able to include and use `EnTT`, never to compile tests.
Roughly speaking, this is because it would multiply for N the effort every time we add a test.

**Comment by zaucy** [comment]
I'm not against removing them from my PR. In reality in order for someone to use entt with bazel they do not need the test BUILD files. I was only adding them in to have full _contributor_ support for bazel.

I can maintain a fork with the tests still in for myself since I've been migrating away from cmake in my own projects. That's no problem for me.

> Roughly speaking, this is because it would multiply for N the effort every time we add a test.

It wouldn't be terrible if bazel was behind on tests since running the tests wouldn't be a normal thing for developers consuming entt to do. It would also only be behind when a new cpp file gets added or there is some new external dependency.

**Comment by skypjack** [comment]
>I was only adding them in to have full contributor support for bazel.

This makes sense actually. I'll leave them there and get rid of those files in future if they'll become a problem. :+1:

**Comment by skypjack** [comment]
@zaucy Can you confirm that the `wip` branch works for you and all tests pass also with your changes to support bazel? In this case, I can merge your PR directly without further changes and everything will work also with VS2019. :tada:

**Comment by zaucy** [comment]
After merging wip into my local bazel support branch all the tests pass on windows! Awesome!

![image](https://user-images.githubusercontent.com/1284289/63308937-a8df9f80-c2a9-11e9-8bd9-81be8e9d1059.png)

**Comment by skypjack** [comment]
I've merged the PR but I've realized that it doesn't generated the documentation.
It's not a big problem to be honest, but probably a nice to have feature for bazel users.

**Comment by skypjack** [comment]
That said, merged on `wip` and updated the README file to mention `Bazel`.
If nobody pops up asking for changes, I'll merge it on `master` tomorrow. Feel free to open other PRs to update the bazel stuff and do not forget that you promised to maintain it!! :-)

>How about we close it once the PR (#291) has been merged :)

I'm closing this issue. Thank you for the PR and for the help. :+1:
