### ISSUE TITLE
Iterate over subclasses?

### ISSUE THREAD

**Issue by codecnotsupported** [skypjack/entt#304]
Would it be possible to without naming each subclass, to iterate over the inherited variables or call the overridden functions?

For example:

```
#include <iostream>
#include "entt/entt.hpp"

class MainClass{
    public:
    int z = 0;
    virtual void f() = 0;
};

class SubClassType1 : public MainClass{
    public:
    int y = 1;
    void f() override {
        std::cout << "Called SubClassType1 virtual function and z+y= " << z+y;
    }
};

class SubClassType2 : public MainClass{
    public:
    int x = 2;
    void f() override {
        std::cout << "Called SubClassType2 virtual function and x+z= " << z+x;
    }
};

int main()
{
   entt::registry Registry;
   Registry.assign<SubClassType1>(Registry.create());
   Registry.assign<SubClassType2>(Registry.create());
   //   Registry.assign<SubClassTypeX>(Registry.create());
   // Pseudo code: 
   Registry.view<MainClass>().each([](MainClass aMainClass) {
    aMainClass.f();
    });
    return 0;
}
```

**Comment by skypjack** [comment]
Indeed no. ECS is mostly about getting rid of hierarchies in the simulation, it wouldn't make sense to allow this and I don't even know how it can be done to be honest. However, there are plenty of techniques to obtain exactly the same result by means of the components.

**Comment by codecnotsupported** [comment]
I kind of was expecting that, so how would it be implemented using EnTT?

**Comment by skypjack** [comment]
Well, the idiomatic _ECS way_ would be to put your logic in separate systems and use different components to trigger different behaviors.  
Alternatively, you can use type erasure, pointers to functions and eventually decayed lambdas to store the behavior directly on your components, so as to have only one system that runs this opaque functions (static polymorphism instead of runtime polymorphism).  
Another option I wouldn't recommend but that could work is using a variant.  
Yet another approach is to store in your components opaque pointers and meta types, then use the latter to work with the former.

And so on. There are several approaches to get there.  
I'm not a fan of putting the logic in the components though and I'd recommend to use different types and multiple systems here.

That said, as far as I know it could also be an XY-problem.  
It's hard to say what's the best solution for your case without knowing the details of the problem you're trying to solve.  
If you feel like discussing with other users, try to join the gitter channel and drop your questions there. :wink:

**Comment by codecnotsupported** [comment]
Sounds like it's now a project specific design issue. (In my case: trying to combine ImGui & EnTT)
Well, I got my answer, closing issue. (I'll probably discuss it on gitter later like you suggested)
Thanks.

**Comment by skypjack** [comment]
You're welcome. I want to let you know that there is online an example of integration between ImGui and EnTT. I think the link is also in the wiki. It may be of inspiration probably. :+1:
