### ISSUE TITLE
Instancing an entity into a registry with entity type E from an entity in a different registry with entity type F does not work.

### ISSUE THREAD

**Issue by chrispetkau** [skypjack/entt#315]
I'd like to store my entity prototypes in a separate registry from my game entities. I want to use a different enum class and underlying_type for the prototype entity type for clarity and type-safety. However, instancing an entity from a prototype when the registries do not operate against the same entity type does not work.

**Comment by chrispetkau** [comment]
That's correct: I want to clone a complete prototype entity from entt::registry<ProtoEntity> into entt::registry<Entity>, where ProtoEntity and Entity are two different enum classes. I want all components copied without having to specify them.

**Comment by skypjack** [comment]
Ok, so, maybe it's possible **but** with a limitation.
Because the types are both different and erased, we cannot construct pools in the target registry if you don't specify the components. Therefore you must trigger the creation of the pools once before start cloning.
With this condition satisfied, maybe there exists a way.

Is it too stringent or does it sounds like a good compromised?

**Comment by chrispetkau** [comment]
What would triggering the creation of the pools look like? target_registry.create_pools<AllComponents...>() where AllComponents is an explicit list of all possible components? Or target_registry.create_pools(prototype_registry)? I don't mind adding in an extra call to synchronize the target_registry with the prototype_registry and deferring pool construction to this point.

New prototypes, and hence new component types, may be added to the prototype registry after target_registry pool creation. I would want to be able create the new necessary pools prior to spawning the new prototypes.

**Comment by skypjack** [comment]
Ok, I started a reworking that has many benefits. One of them will be the possibility to migrate entities and component between registries that have different types for the identifiers.  
You won't have to prepare the pools nor the target registry **but** it will work only as long as the underlying types for the identifiers are the same. I think this is common if not desirable in general and definitely acceptable as a limit.

I cannot set a deadline because I'm doing this in my free time but it shouldn't take much.  
I'll update this issue in any case once done. :+1:

**Comment by skypjack** [comment]
Ok, I stopped the rework because it introduced problems with views and groups.
However, the branch `wip` contains a version of `stomp` that works with foreign registries.
Let me know if you spot any error. Thank you.
