### ISSUE TITLE
Reminder to check group sorting with owning+exclude groups

### ISSUE THREAD

**Issue by pgruenbacher** [skypjack/entt#323]
Per discussion it seems that when sorting group that has owned components and as exclude components get added in, the group / pools enter a state where some of the owned entities have indices outside of the valid length, causing ultimately the discard_if to fail and the group length to not match the view length.

will need to test on 3.1.1 when it comes out to see if issue resolves itself with new iterator changes and such.

**Comment by skypjack** [comment]
Yeah, reproduced. I've already a fix, I'm writing a test to avoid the same error in future.
Fortunately, the problem is only on `master` and not in official release. It's due to recent changes.
Long story short, I went too far with an optimization when I developed the allocation-less sort functionality.

Thank you very much for the support and for pointing this out!!!
The patch will land on `master` most likely tomorrow. :+1:

**Comment by skypjack** [comment]
As a side note, I've added a test to `group.cpp` for `group::sort` but I'd like to add also a specific test in `sparse_set.cpp` for `sparse_set::arrange`.  
That was the source of the problem mentioned above but I'm still trying to figure out a proper test to reproduce the error without the exclusion list.
