### ISSUE TITLE
Snapshot Loader Feature: Add auto update for entities stored in maps (key & value)

### ISSUE THREAD

**Issue by szunhammer** [skypjack/entt#334]
Right now, the update method in snapshot.hpp fails to handle std::map as an input type correctly. There is an implementation for containers though. I had a look, and it's possible to provide the same convenience for std::map/std::map-like types, too.

I have implemented an extension for this update method and with your permission I could create a PR.

**Comment by skypjack** [comment]
You don't need my permission to create a PR. You need my permission to merge it upstream though. :)

---

If you plan to open a PR, I'll write here what I would write as a comment to the PR otherwise.

Please, submit only PRs that introduce both new code **and** some tests for it.  
I won't accept a PR that either reduces the code coverage or that introduces new features without enough tests to guarantee backward compatibility.

Thank you for understanding and contributing. :+1: :wink:
