### ISSUE TITLE
allow for prop in factory to accept std::pair

### ISSUE THREAD

**Issue by pgruenbacher** [skypjack/entt#341]
Unless my thinking is wrong, if I want to do something like 
entt::meta<Type>().type("Name"_hs).prop(button("test"))

i'd have a funciton 
constexpr std::pair<hashed_string, string> button(string) { return { hash(string), string} }

and would need EnTT prop method to accept std::pair

    template<typename Key, typename Value>
    auto prop(std::pair<Key, Value>&& pair) {
      return prop(pair.first, pair.second);
    }

this would be ultimately to allow for function properties so that I wouldn't have to rewrite "button"_hs property hash keys for every property

**Comment by pgruenbacher** [comment]
I do like the new meta api, its more intuitive and readable.

**Comment by skypjack** [comment]
>I do like the new meta api, its more intuitive and readable.

I'm glad to hear this. Thank you!!
By the way, I was actually working to support _`std::get<N>`-table_ properties, which will also solve this problem. :+1: 
Soon on `master`.

**Comment by skypjack** [comment]
@Innokentiy-Alaytsev 

Wouldn't the form suggested by @pgruenbacher be enough to support what you called _annotations_?
```
entt::meta().type("Name"_hs).prop(button("test"));
```
Actually, there is no need to pass the function as a template parameter. Am I wrong?

**Comment by Innokentiy-Alaytsev** [comment]
One of the features of the original POC implementation is the support of
annotation composition, i.e. annotations can return any number of other
annotations (together with any number of properties). It serves the purpose
of describing concepts defined by a set of properties.

This, simpler approach may work, especially with property lists from my PR
(after I rework it as we discussed). The composition part... Well, the user
will have to do it by hand somehow (macros?). Otherwise support for passing
a list of properties in a form of a tuple us required and it introduces
ambiguity and I've (we've?) been there with my POC, not fun (ambiguity is
not fun, implementing the feature was kinda fun).

пт, 18 окт. 2019 г., 18:53 Michele Caini notifications@github.com:

**Comment by skypjack** [comment]
@Innokentiy-Alaytsev Right. Good point. One step at a time. :+1:
