### ISSUE TITLE
Signature change question

### ISSUE THREAD

**Issue by arlyon** [skypjack/entt#369]
Hi,

This is more of a "how can I do this better" question. I just went from 3.1.1 -> 3.2.1 and it went mostly smoothly with one exception, and I was hoping I could get some insight as to what is going on under the hood. The signature to some of my functions have changed, and I'm keen to know why. I've only been using cpp for a few months so excuse my ignorance. Is the `entt::exclude_t` required here?

```cpp
// 3.1.1
glm::vec3 rule1(entt::basic_view<entt::entity, position, velocity, fish> &sortedFish, entt::entity &ourEntity) {
    // do stuff
}

// 3.2.1
glm::vec3 rule1(entt::basic_view<entt::entity, entt::exclude_t<>, position, velocity, fish> &sortedFish, entt::entity &ourEntity) {
    // do stuff
}
```

Thanks!

**Comment by skypjack** [comment]
HI, v3.1.1 didn't have support for exclusion lists on views while v3.2.1 added it.
In other terms, you can now do this:
```
auto view = registry.view<A, B>(entt::exclude<C>);
```
The view will return all entities that have both `A` and `B` but don't have `C`.
This is the reason for which that `entt::exclude_t<>` appeared in your signature.

Because you use `entt::entity`, you can use `entt::view` rather than `entt::basic_view` (see `fwd.hpp` for the forward declarations):
```
entt::view<entt::exclude_t<>, position, velocity, fish>
```

There isn't much more you can do there. To support exclusion lists, the _types_ of the excluded components are required and thus part of the view type. Because of how parameter packs work in C++, we need to enclose one of them in a type list, in this case `entt::exclude_t`. This has the drawback that an empty type list is still required when no types are excluded.

Let me know if it's not clear enough.

**Comment by arlyon** [comment]
Hey, thanks for the clear explanation. Must have missed that in the changelogs.

**Comment by skypjack** [comment]
Probably not as clear as it should be but it's part of the changelog for v3.2.0:
>Views support exclusion lists (eg registry.view<T>(exclude<U>)).

Anyway, you did the right thing by asking. :wink:
