### ISSUE TITLE
entt::null and Serialisation

### ISSUE THREAD

**Issue by alanjfs** [skypjack/entt#375]
Hi all,

This isn't a bug report, but documentation or discussion of a quirk I found in the case of using `entt::entity` and `entt::null` for creating relationships between entities, such as parent/child or constraint targets, and later serialising those relationships.

**Example**

```cpp
struct Parent {
  entt::entity entity { entt::null };
};

auto parent = registry.create();
auto child = registry.create();
registry.assign<Parent>(child, parent);
```

Now when you serialise this component..

```cpp
json_document["Parent"]["entity"] = static_cast<std::uint32_t>(parent.entity);
```

..there's no telling whether the value refers to `entt::null` or the `parent` entity, as they both result in a value of `0`, the parent being the first entity created.

**Solution 1**

Spontaneously, I would have considered solving this by not using `entt::entity` directly, but by using another component. Like a `GUID` component, carrying a unique ID. But the advantage to using the `entt::entity` value is that it is directly usable during lookup of that entity.

```cpp
auto& sc = registry.get<SomeComponent>(parent.entity);
```

Which would then become something along the lines of..

```cpp
auto parent = registry.get<Parent>(child).entity;
SomeComponent* scPtr;
registry.view<GUID, SomeComponent>().each(auto entity, const auto& guid, const auto&) {
  if (guid.value == parent) {
    scPtr = registry.try_get<SomeComponent>(entity);
  }
});
sc = *scPtr;
```

**Solution 2**

So instead I have this in the constructor of wherever I'm storing my registry, as a one-off.

```cpp
entt::registry registry;
auto temp = registry.create();
registry.destroy(temp);
```

This reserves the value `0` such that no valid entity can use it (I think?), resulting in `entt::null` being the only entity that results in that value.

I'm not 100% sure how recycling of IDs work here, so maybe its worth keeping the entity, and not destroying it?

```cpp
auto temp = registry.create();
// registry.destroy(temp);
```

Anyway, let me know if there's another way to tackle this, but so far it's worked well. So well in fact that I was thinking maybe it's worth reserving `0` permanently in EnTT? That is, let no entity occupy this number?

**Comment by skypjack** [comment]
Wait. I think there is an error in the reasoning though.
`entt::null` isn't 0. Actually for a 32b identifier it's 0x000FFFFF, where the initial 000 part is the version.
Maybe the problem is somewhere else? It looks like your `parent` is default initialized (with the meaning this has in C++) rather then _null-initialized_ (with the meaning this has in `EnTT`).

**Comment by alanjfs** [comment]
> It looks like your parent is default initialized

It is? :O Isn't this initialising it to `entt::null`?

```cpp
struct Parent {
  entt::entity entity { entt::null };
};
```

> entt::null isn't 0

This is odd. Could this be a platform/VS2019 thing? I tested this on Linux and Clang and wasn't able to `static_cast<unsigned int>(entt::null)` whereas that's what I'm doing on Windows. I'll investigate this a little closer.

**Comment by skypjack** [comment]
Interesting. Please keep me up-to-date. I've never experienced something like this.
I'm looking forward to your ping. Thanks for investigating.

**Comment by skypjack** [comment]
Oh, btw you've also `entt::to_integer(entity)` to cast the entity to its underlying type.
The _right form_ in C++ is `static_cast<std::underlying_type_t<entt::entity>>(entity)` instead, since `entt::entity` is an enum and `std::underlying_type_t` is meant to _extract_ its underlying type in a safer manner. :+1:

**Comment by Lawrencemm** [comment]
I think it's worth considering an alternative to the direct (de)serialisation of entity identifiers.

Given the identifier-reusing nature of `EnTT`'s registry, it is easy to have a registry that assigns a different id to an serialised entity upon deserialisation.

I think a better approach is to have a "name" component and use that in place of the identifier when serialising references to other entities.

**Comment by skypjack** [comment]
@Lawrencemm technically speaking, you don't need a _name component_. You can use the entity for that. Just put it in a map so as to bind the _old_ entity to the new one.

**Comment by Lawrencemm** [comment]
Makes sense. Is that what you're actually doing @alanjfs?

**Comment by skypjack** [comment]
@alanjfs 

Just to be sure, I've added [this](https://github.com/skypjack/entt/blob/experimental/test/entt/entity/entity.cpp#L15) test:
```cpp
ASSERT_FALSE(entt::entity{} == entt::null);
```
I don't use `ASSERT_NE` because it's odd and it doesn't necessarily invoke `operator==`.
By the way, this confirms that the assumption above is somehow wrong and your issue is due to something different.
It's hard to find the reason from the few info I have though. I'm sorry.

**Comment by alanjfs** [comment]
> Makes sense. Is that what you're actually doing @alanjfs?

I'm serialising to text that looks like this.

**serialised.json**

```json
{
  "schema": "someschema-1.0",
  "entities": {
    "0": {
      "id": 0,
      "components": {
        "Name": {
          "type": "Name",
          "members": {
            "value": "gridShape"
          }
        },
        "Parent": {
          "type": "Parent",
          "members": {
            "entity": 1
          }
        }
      }
    },
    "1": {
      "id": 1,
      "components": {
        "Name": {
          "type": "Name",
          "members": {
            "value": "grid"
          }
        }
      }
    }
  }
}
```

From components that look something like this.

```cpp
using Name = std::string;
struct Parent {
  entt::entity entity { entt::null };
};
```

When I read it in, there are no "old entities", if I understand you guys correctly. It'll read the first one, which references the second by the value of the entity, coming from `static_cast<std::uint32_t>(entity)`.

Somehow, I'm getting a consistent and stable value of `0` for any entity set to `entt::null`, which has worked reliably for months. :S My only issue was that, like in the above example, the first entity ever created - on application startup - is also given a value of 0, which I resolved by simply creating an entity alongside the creation of the registry, and then discarding that. Then the first *actual* entity is given some other non-zero value which works well.

I haven't investigated yet, got a few things piled up to take care of first. But that's about it.

**Comment by alanjfs** [comment]
> it is easy to have a registry that assigns a different id to an serialised entity upon deserialisation.

That's true, and is fine. The deserialiasation looks something like this.

```cpp
std::map DESERIALISED_ENTITIES_SO_FAR;

void deserialise(...) {
  for (auto [key, value] : document) {
     auto entity = registry.create();
     std::uint32_t id = jentity["id"].GetUint();
     DESERIALISED_ENTITIES_SO_FAR[id] = entity;

     if (value.has_member("Name")) registry.assign<Name>(deserialise_name(value));
     if (value.has_member("Parent")) registry.assign<Parent>(deserialise_parent(value));
  }  
}
```

Where `deserialise_parent` would lookup the "id" from that `std::map` to find the corresponding entity in the actual registry.

**Comment by skypjack** [comment]
@alanjfs 

I'm interested in this thing you're observing since I can't really reproduce it. If it's a corner case of which I'm not aware, it would be useful to document it in fact.
I've added a test to guarantee that `entt::null` **isn't** equivalent to `entt::entity{0}`. I'm looking forward to your tests but no pressure at all, take you time and thank you for caring!

As a side note, many went with an approach similar to the one you described before `entt::null` became a thing. That is, just create entity 0 and forget about it, so as to be able to use 0 as if it were `null`. Since it was a _waste_, I decided to reserve a different identifier for `entt::null` and this is why I'm pretty sure it's not 0 actually.

**Comment by alanjfs** [comment]
I've had another look at this, and I think I've narrowed down what's happening. There are two connected issues, related to the `Parent` struct using `entt::null` as a default value for the variable `entity` of type `entt::entity`.

1. When **serialising**, it isn't actually serialising `entt::null`, but the variable `entity` which is given a non-existent, but consistent value of `1048575` from `entt::null` which becomes the written value in my file.
2. When **deserialising**, the value `1048575` is fetched from a `std::unordered_map<std::uint32_t, entt::entity>` containing all entities deserialised so far. As it doesn't exist, it hasn't been deserialised which should have thrown an error. But I was retrieving the value using `std::unordered_map[]` rather than `::at()` which created a new `entt::entity` and returned that.

Such that next time I serialised, I would serialise this new entity, which is given a value of 0. That also helps explain why I wasn't able to cast a `entt::null` to an integer directly, since it never was.

With that in mind, I think it's probably still reasonable to exclude the value `0` from anything created via `registry.create()` such that any explicitly created `entt::entity` is invalid per default. Also, where is the value `1048575` coming from? And shouldn't it also be 0?

I was able to reproduce that value with this.

```cpp
entt::entity test{ entt::null };
// 1048575
```

![image](https://user-images.githubusercontent.com/47274066/71572050-47d89b80-2ad5-11ea-9fbe-0ebae2150b05.png)

**Comment by Innokentiy-Alaytsev** [comment]
`entt::null` has a value where minor 20 bits (entity id) are set and all other bits (version) are not set. It's the greatest value of an entity identifier so it's better suited for "wasting" than `0` due to entity ids being used as indexes into arrays.

A better way of retrieving things from a map is probably `std::unodreder_map::find` - it returns an iterator pointing to an entity if an entity is in map or `end` in the opposite case. Unlike `at` it does not rely on exceptions for communicating the absence of the requested entity.

**Comment by alanjfs** [comment]
> Oh, btw you've also entt::to_integer(entity) to cast the entity to its underlying type.
The right form in C++ is static_cast<std::underlying_type_t<entt::entity>>(entity) instead, since entt::entity is an enum and std::underlying_type_t is meant to extract its underlying type in a safer manner.

I had a look at these options, but can't quite figure out how to use them.

**Original**

```cpp
static std::uint32_t entityToJsonId(entt::entity entity) {
    if (entity == entt::null) return 0;
    return static_cast<std::uint32_t>(entity);
}
```

Here, the return value of the function is `std::uint32_t` which may of course differ from what the `entt::entity` actually is, after having been forced into it by the `static_cast`.

But if I do:

**After**

```cpp
static ??? entityToJsonId(entt::entity entity) {
    if (entity == entt::null) return 0;
    return static_cast<std::underlying_type_t<entt::entity>>(entity);
}
```

Then I could replace `???` with `std::underlying_type_t<entt::entity>`, but at some point I'm writing this value out to JSON and need to know the final type.

```cpp
json.Uint(entityToJsonId(entity));
```

As I'm explicitly telling EnTT to use `std::uint32_t` for entities, it seems to me safe(r) to use this type explicitly rather than implicitly, would you disagree?

> A better way of retrieving things from a map is probably std::unodreder_map::find

Oh, interesting. I hadn't considered that it using exceptions was a bad thing. I would have thought `find` to perform a kind of search (i.e. to be slow) as opposed to `at` which I would have guessed does just a hash lookup. Will experiment, thanks @Innokentiy-Alaytsev

**Comment by alanjfs** [comment]
> It's the greatest value of an entity identifier so it's better suited for "wasting" than 0 due to entity ids being used as indexes into arrays.

Is ~1 million IDs the maximum amount of entities for a `std::uint32_t`? :O That's not enough, are you guys using 64-bit for this?

**Comment by Kerndog73** [comment]
Instead of encoding `entt::null` as an integer, you could encode it as `null` in JSON.

**Comment by alanjfs** [comment]
@Kerndog73 That's a good idea, thanks!

**Comment by Innokentiy-Alaytsev** [comment]
AFAIK, the `std::unordered_map::find` member function will perform the same
hash lookup as `at` or `operator []`. The `std::find` may be slow as it's a
generic algorithm and may perform a linear search.

According to docs, 1kk entities is more than enough for most typical
use-cases. If you need more entities then there's some define for it.

пн, 30 дек. 2019 г., 13:07 Alan Jefferson <notifications@github.com>:

**Comment by skypjack** [comment]
@alanjfs 

>Then I could replace ??? with std::underlying_type_t<entt::entity>, but at some point I'm writing this value out to JSON and need to know the final type.

You can just use `auto` and make the type system deduce everything for you.

>Is ~1 million IDs the maximum amount of entities for a std::uint32_t? :O That's not enough, are you guys using 64-bit for this?

More or less. ~1 million is the maximum amount of entities **still alive** for an `std::uint32_t`. Since `EnTT` recycles identifiers, you can create and destroy billions of entities as long as you've no more than ~1M of them in use at the same time.
Of course, I use `std::uint32_t`, mainly because I've never had more than 200k entities alive at the same time. It seems to me already an indecent amount of stuff to be honest. However, you can use `std::uint64_t` if ~1M isn't enough and you'll have 2^40 entities in this case.

>Instead of encoding entt::null as an integer, you could encode it as null in JSON.

@Kerndog73 chapeau.

>1kk entities

@Innokentiy-Alaytsev _1kk_ ... love it. :smile:

**Comment by alanjfs** [comment]
> You can just use auto and make the type system deduce everything for you.

Auto only goes so far. :) On writing to disk, I either need to write a int, unsigned int, or a `null`, or any other kind of type is being used. In the case of rapidjson, there's a dedicated call per output type, e.g. `Uint(some_value)`.

> skypjack closed this in 8d67bb7 2 days ago

That's fair, but there is still the issue of a manually created `entt::entity my_entity;` which would be given the same id as the first created `registry.create()`. That can be a problem when used in this particular way of `std::map<jsonid, entity> my_map[non_existent_id]`.

I would recommend either:

1. Making the first entity `1` instead or and `0`, such that 0 is always invalid, or..
2. Making `entt::entity my_entity` get the same value as if it was initialised with `entt::null`, e.g. 1048575, that way `0` is still always invalid and any manually created entity is invalid too, which I think is (always?) expected.

**Comment by skypjack** [comment]
>skypjack closed this in 8d67bb7 2 days ago

Oops, sorry, reopened. It wasn't meant to be _close #N_ but just a reference to the issue, my fault.

>manually created `entt::entity my_entity;` which would be given the same id as the first created `registry.create()`. [...] I would recommend either:

The two solutions are either tricky or just unfeasible (enum classes cannot have a default constructor).
The fact is that `my_map[non_existent_id]` is conceptually as broken as it can be when used in combination with fundamental types since all their values can be _valid_ and a zero-initialized instance isn't exactly what you want in most cases.

This is in a sense a _broken_ design of the map, even though I see it was probably the only viable solution to make `operator[]` work somehow.
You should use `find` instead:
```
if(auto it = my_map.find(non_existent_id); it == my_map.end()) {
    // ... insert or do whatever makes sense here
} else {
    const auto entity = *it;
    // let's use the entity...
}
```
That's all.

**Comment by alanjfs** [comment]
> You should use find instead:

I know, this isn't a problem for me anymore. The reason I opened this issue was to avoid it happening to someone else in the future, in a way that doesn't come at a cost to the library or those that use it properly.

In this case, *if* the default was 0 and 0 was invalid, existing users wouldn't be affected, nor would performance, and future users would be notified of their error instead of working with what looks to be a valid entity, when in fact it is not. Win-win. It's one of them subtle bugs that can get hard to debug (e.g. you may have one already, and not know about it).

Whether that's something you should protect against is up to you; I can see it both ways. Using it the way I did was improper and it's possible it won't happen to anyone else.

**Comment by skypjack** [comment]
Using 0 as default makes the codebase a little more complicated and is probably error-prone since currently everything in `EnTT` expects identifiers start at 0.
The best bet for the library is currently to document what you mentioned and let it be since an easy, _C++_-ish solution exists.

**Comment by alanjfs** [comment]
Not asking to reopen, just adding that as I ventured onto a new project, this issue bites me several times daily.

```cpp
// Somewhere in your project
auto some_entity = registry.create();

// Elsewhere in your project
struct SomeData {
  entt::entity entity;
};

SomeData data;
registry.valid(data.entity);  // Yes
```

And that's not right.

For my future self and anyone reading this, here's the magic bullet that makes all uninitialised entities invalid.

```cpp
entt::registry registry;
registry.destroy(registry.create());  // Make index 0 invalid
```

Add this directly following the creation of the registry, and thank me later.

**Comment by skypjack** [comment]
I must admit I'm tempted to make the zero entity the null one or at least to make an attempt at changing it...

**Comment by Kerndog73** [comment]
You could write `entt::entity entity = entt::null;` in that case but I see your point. If the zero entity can't be made the null entity then the next best thing is probably giving entities a default constructor. That would ruin the elegance of using an enum but I think usability is more important.

**Comment by OvermindDL1** [comment]
Just a +1 for making the null entity the index=0 entity.  I've been porting entt to another language for the purposes of learning that language (and entt is a nicely complicated library with complicated type handling and so forth) and I removed the null entity altogether and just made index 0 be null and it just feels so much nicer especially in a lot of the internal code.  I'd highly recommend it.

**Comment by skypjack** [comment]
>so much nicer especially in a lot of the internal code

@OvermindDL1 how is it nicer in the internal code? At a first glance, it requires a bunch of `+1` and `-1` here and there to make things work. Am I missing something?

> I've been porting entt to another language for the purposes of learning that language

You know that we are going to ask you **ALL** the details now that you mentioned it, right? :smile:

**Comment by OvermindDL1** [comment]
> how is it nicer in the internal code? At a first glance, it requires a bunch of +1 and -1 here and there to make things work. Am I missing something?

Well first of all I make my registry always have 1 entity that is allocated and immediately destroyed upon allocation, this is index 0, my `null` entity.

0 is still a valid entity as far as any code is concerned, it's just never active.

So far I haven't had to put +/-1's anywhere though at least.  I'm still in middling development for it.  I've been skipping the occasional pieces as they haven't seemed difficult enough for me to develop and mostly been porting the more "interesting" code and cases.  I'm not necessarily intending to finish it but I might, and I might use it, we'll see.  ^.^;

> You know that we are going to ask you ALL the details now that you mentioned it, right?

Lol, It's Rust that I'm porting it to.  I've been a C/C++ programmer for 30 years at this point and Rust is really the first language I've found that I really think can replace it.  I've made a good variety of fairly simple programs in it so far and contributed to some projects, and so lately I've been tackling some of the more advanced C++ libraries I've used to see how well they convert.  I.E. I'm just doing what I can to try to master the language (not really that hard honestly, it's very similar to C++ in some really important ways, though replacing advanced turing-complete templates with macro's is certainly different).  It's not public by any stretch (it's basically "learning" code after all), but if anyone is actually curious I could pry it out of my rust_playground project into it's own thing sometime and put it on github.

I'm mostly focusing on a faithful translation, though as is obvious with the null entity type I've taken a few stylistic changes that just seem to fit better with everything I've been writing, mostly to see how it feels to do it.

I have to say I love Rust's built-in documentation system, this is the first one that I've been honestly trying to learn it too and it's amazing.  You can even have doctests (normal test code but part of the documentation, so it always gets tested and is always up to date so no worry about the documentation getting out of sync).

The biggest change I've made compared to entt so far isn't even the null type, but rather the entity type.  Instead of using your style `entity_traits` and so forth I went with a trait (which when used in a generic way in rust gets compiled as efficiently as full inline code, no virtual dispatch).  This means I can have many different registries with many different entity types all in the same program without issue.  I have the `Entity` trait implemented for `u16`/`u32`/`u64` by default (to match entt's) but you could easily define it for any type, I've thought about making a `uuid` type entity just as a test (it certainly wouldn't be as efficient as the integral versions at all, but it would be a fun demonstration).  For comparison, here's my `Entity` trait at the moment:
```rust
pub trait Entity: PartialEq + Copy {
        /// The actual container type of this entity date, it should be Copy, and thus cheap to Copy.
        type StorageType;

        /// The type returned to hold the version, smaller than the StorageType in general.
        type VersionType;
        /// Constructs an Entity Handle using the given ID and a 0 version
        fn new(id: usize) -> Self;
        //      fn to_integral(self) -> Self::StorageType;
        /// Return true if this entity is index 0
        fn is_null(self) -> bool;
        /// Returns the index of this entity
        fn idx(self) -> usize;
        /// Sets the index of this entity
        fn set_idx(&mut self, idx: usize) -> &mut Self;
        /// Returns the version of this entity, generally a number but it could potentially be something else, like a UUID
        fn version(self) -> Self::VersionType;
        /// Sets the index as well as increments the version in a single call
        fn bump_version_with_idx(&mut self, idx: usize);
}
```
As you can see from your `entity_traits` and such things I've made a few decision changes in this.  I still have the storage and version types (renamed for my own clarity) but I moved all entity handling functions into these types.  I've only defined what I need so far to work with entities but I'm debating on exporting these or not, I'm leaning to not (rather make a new public trait just for `is_null` and `idx` and so forth maybe, I'll cross that later).

But `new` will construct a new one, I've defined by convention that a `0` id/index must be the null entity for this.  I've been going back and forth on adding a `new` constructor with no argument that just returns the null type regardless for maybe user-code use, but that can be worked on later.

But usage is pretty normal, just do `let mut registry = enrs::entity::registry::BasicRegistry::<u32>::new();` (or rather `use enrs::entity::registry::BasicRegistry;` at the top of your file and then `let mut registry = BasicRegistry::<u32>::new();` more normally) and start using it.  The type argument just needs to have an `Entity` trait implementation for it is all.

**Comment by skypjack** [comment]
I guess you missed the fact that `entt::entity` is a class enum now and you can define your own types to have different registries with different identifiers around. :)

**Comment by OvermindDL1** [comment]
> I guess you missed the fact that entt::entity is a class enum now

It wasn't that case on the branch of code I was working on.  ^.^

Hmm, it is?  https://github.com/skypjack/entt/blob/master/src/entt/entity/entity.hpp#L33 still shows the `entt_traits` that I initally worked off of?

> and you can define your own types to have different registries with different identifiers around. :)

Yep that's built in to this style as well, same thing with no worry about passing the wrong entities to the wrong registry when using a custom type wrapper.  ^.^

Ah, and I think I initially looked at https://github.com/skypjack/entt/blob/master/src/entt/config/config.h#L30 the `ENTT_ID_TYPE` definition a bit wrong, I initially got it stuck in my head it was the entity size definition, but it looks like it's just the type id type.  I'm currently using Rust's built-in TypeID type to manage all that in each location instead.  My wires got a bit crossed.  ^.^
