### ISSUE TITLE
Anybody using latest entt (or at least V3+) on Nintendo Switch

### ISSUE THREAD

**Issue by kariem2k** [skypjack/entt#382]
Hi Guys,

Entt is great. I am impressed by many of its design decisions. 

I want to use it on a project, targeting Nintendo Switch in the near future. I am at the prototyping stage. Does anybody use latest versions entt in any Nintendo Switch project?

Thanks

**Comment by skypjack** [comment]
Hi @kariem2k 

Afaik you'll be using clang with the Switch, so your question boils down to: what version of clang is targeted by this console?
I've not the answer at the moment. If you know that, I can easily tell you if it works fine with the upstream version of EnTT.

It goes without saying that you've all my support to release a game based on EnTT for the Switch, so feel free to ping me whenever you want. :wink:

**Comment by kariem2k** [comment]
Thank you very much @skypjack for your fast reply. I think they support C++17 https://youtu.be/9_7exO60EA8?t=196. They have partial support of the standard library so I am not sure what do they support exactly.

**Comment by skypjack** [comment]
Oh, well, `EnTT` uses the vector class, some type traits and the unique pointer. These kind of things are usually supported everywhere.
Partial support of the standard library often means that it doesn't contain things like the `pmr::` namespace or the parallel stuff. It's unlikely something like `std::tuple` or `std::move` is missing.
Since `EnTT` v3 requires C++17 and If it **is** an option for the Switch, I'd go with the upstream version without problems. All what is used from the standard library can easily be replaced in case but my guess is that most likely it won't be a problem. :+1:

**Comment by kariem2k** [comment]
Thank you very much @skypjack

**Comment by skypjack** [comment]
You're welcome, feel free to ping me whenever you need and keep us up-to-date if you decide to proceed! I'm really curious now. :heart_eyes:

**Comment by pacojq** [comment]
Hi!
I'm also prototyping a game for Switch with entt. @kariem2k did you manage to have it compiling?
I was afraid it was a VS solution setup problem, but I've tried to compile it in smaller, single-file projects, and I'm not being able to get a successful build.

**Comment by skypjack** [comment]
Well, let's say that Minecraft is also released for Switch and it uses EnTT, therefore I'm pretty sure that the problem is in the configuration (or maybe the compiler version?). 🙂

**Comment by pacojq** [comment]
Most of the issues come from `std` types. After looking at the code for standard library support in the SDK, I think the compiler version might be the problem here.
I'll continue investigating 👌
