### ISSUE TITLE
In which cases would sorting a full-owning group cause an assertion to fail?

### ISSUE THREAD

**Issue by Qix-** [skypjack/entt#387]
Apologies for so many tickets 🙃 

I have a full-owning group of components called `global_transform_group` that holds a three-component tuple of components. I also have a nested group called `global_render_group` that has the same three components, along with an additional render-related component.

With any more than 1 entity belonging to those groups (0 works fine, too), I either get an assertion failure when calling `global_transform_group.sort()` or `false` when calling `global_transform_group.sortable()`.

The documentation seems to contradict itself:

> Sorting owned components is no longer allowed once the group has been created. However, full-owning groups can be sorted by means of their sort member functions. Sorting a full-owning group affects all its instances.

Which, at least to me, starts by saying you cannot sort, but then goes on to say that full-owning groups _can_ sort, which leaves me a bit confused 😅 

So, in which circumstances can I sort a full-owning group? Should I eliminate the nested group and just use a single full-owning group with all four components?

It's worth mentioning I'm using a custom sort function.

**Comment by skypjack** [comment]
When you use groups, you can sort only the most restrictive ones, that is the one with the higher number of rules.
From your example:
```
auto global_transform_group = registry.group<A, B, C>();
auto global_render_group = registry.group<A, B, C, D>();
```
This is allowed, they are nested groups. In this case, `global_render_group` is more restrictive because it sets more constraints on the entities that want to enter it. Therefore, it will be fully contained within `global_transform_group` by construction.
Now, consider what would happen if you sorted `global_transform_group`. Since it's _larger_ that `global_render_group`, the elements contained by the latter could be moved around and exit it during the sort. This isn't an option of course.
What happens if you sort `global_render_group`? Since it's fully contained within `global_transform_group`, it doesn't matter how it's elements are arranged, they cannot exit the _outer_ group in any case.
Therefore, it's allowed to sort `global_render_group` and this is the reason for which `global_render_group.sortable()` returns true while `global_transform_group` isn't sortable.

---

If you want to sort both, you can't make all them full-owning group.
There doesn't exist an architecture that allows you to sort stuff and reaches the maximum performance at the same time. Long story short, this is because we need to arrange things in a specific way to get the best from the data and you cannot shuffle them for your purposes.
If sorting is more important than iterating 1M entities in 0.005ms rather 0.006ms (I guess so), you can define the two groups as partially owning ones in such a way that they don't overlap on owned components. In this case, both will be sortable.

**Comment by Qix-** [comment]
Right okay, that makes much more sense :D Thank you~!
