### ISSUE TITLE
Suggestion: Thread Safe component pool initialization

### ISSUE THREAD

**Issue by NixAJ** [skypjack/entt#388]
It would be quite nice to have an option to enable Thread Safety when the registry initializes its component pools.

Basically as we talked about on the gitter, when you loop over your view for the first time, it will most likely (at least in my case) be the first time that the registry sees a given component type, therefore it has to initialize the pool for that specific type, however as it is right now, this isn't thread safe, and while there are plenty of work arounds, I think it would be nice to have an option to enable this.

At the end of the day using a mutex to make it thread safe isn't really a performance concern as this is a one time setup thing that would happen only on the very first iteration of a view that has a component that the registry haven't seen before, it would "hide" away a lot of otherwise "Setup" code that the programmer would have to do in order to either prepare the registry like using "Register::prepare" or running all views single threaded for the first iteration.

**Comment by skypjack** [comment]
Does `prepare` work as an alternative to using mutexes?
The main problems I see are 1) another include, 2) a macro to enable/disable the mutex, 3) the fact that it cannot be made the default.

Many libraries force you to _announce_ the types before using them. Either by means of an explicit parameter list to the _registry class_ or as a series of calls to some functions.
Using `prepare` to _setup_ the pool isn't different after all. On the other side, the _common case_ is much cleaner.
Another option is to use a single-threaded, warm-up tick. Not sure it's a viable solution in your case though.

**Comment by NixAJ** [comment]
At the end of the day this is a matter of convenience, I' definitely prefer a macro to enable/disable thread safe initialization, especially because while calling prepare is viable, it adds to the complexity whenever a new component is added, you'd have to remember to add them to the prepare list, and I don't think it'd be uncommon to have a hundred components or more in a project, so essentially you just have a incredibly long prepare function which would be sort of inconvenient.

**Comment by skypjack** [comment]
I looked into this issue and decided not to proceed. I'm sorry.

To put it simply, this isn't as easy as it seems at a first glance. A _simple macro_ isn't enough. It _asks_ for many uses all around the codebase to make thread safe things that aren't so inherently otherwise.
This would introduce a maintenance burden for a feature that shouldn't be part of the library from my point of view. As you said, it's easy to get around it and there exist several approaches for that. My advice is that users should pick their preferred solution rather than relying on something imposed by a library.

The main concern is that a macro would enable it for all types while usually I've this _problem_ only for a bunch of them.
Therefore, I prefer to manage it externally in a way that fits with my application rather than having something built-in that is both annoying to maintain and potentially a problem in terms of performance.
