### ISSUE TITLE
Documentation incorrect for "Observe changes"

### ISSUE THREAD

**Issue by PeteHuf** [skypjack/entt#402]
The documentation states that to observe a component being added, your observing function should follow the pattern:
`void(entt::registry &, entt::entity);`

I find that I should actually be
`void(entt::entity, entt::registry &, position&);`

**Comment by Kerndog73** [comment]
The signature changed recently. The wiki reflects the current master branch rather than the latest 3.2.2 release. 

The component was removed from the signature because the reference can become invalid in some situations. For example, if a listener was to sort a pool or remove a component, then another listener would get an invalid reference. The solution is to just get the component directly from the registry. See #386.

In the process of finding solutions for #385, a new feature was added to signals which allowed member functions to be attached without a bound instance. See [the changes to the wiki](https://github.com/skypjack/entt/commit/c8671d1c2b65a4f1767438a71d1c8454997d64d8). The parameter order was changed (putting the registry first) to fully take advantage of this feature to make the syntax for [dependencies](https://github.com/skypjack/entt/wiki/Crash-Course:-entity-component-system#dependencies) a little shorter.

**Comment by PeteHuf** [comment]
Cool! I'll update to the latest version. Thanks for the quick response.

**Comment by skypjack** [comment]
Hi, the documentation for the last stable version is [here](https://skypjack.github.io/entt/).
It contains also the [pages that were in the wiki](https://skypjack.github.io/entt/pages.html) at the time.
As @Kerndog73 pointed out correctly, the wiki on GH contains stuff for the current `master` instead.
