### ISSUE TITLE
meta: copy constructor of function argument is required but not used

### ISSUE THREAD

**Issue by Kerndog73** [skypjack/entt#415]
A function will fail to register if any of its arguments are not copy constructible even though the copy constructor is not used.

```C++
#include <iostream>
#include <entt/meta/factory.hpp>

struct Noisy {
  Noisy() noexcept {
    std::cout << "Default ctor\n";
  }
  explicit Noisy(const int data) noexcept
    : data{data} {
    std::cout << "Data ctor (" << data << ")\n";
  }
  Noisy(const Noisy &other) noexcept
    : data{other.data} {
    std::cout << "Copy ctor\n";
  }
  Noisy(Noisy &&other) noexcept
    : data{other.data} {
    std::cout << "Move ctor\n";
  }
  Noisy &operator=(const Noisy &other) noexcept {
    data = other.data;
    std::cout << "Copy assign\n";
    return *this;
  }
  Noisy &operator=(Noisy &&other) noexcept {
    data = other.data;
    std::cout << "Move assign\n";
    return *this;
  }
  ~Noisy() {
    std::cout << "Dtor\n";
  }

  int data = 0;
};

void takeNoisyConstRef(const Noisy &n) {
  std::cout << "Got " << n.data << '\n';
}

int main() {
  entt::meta<Noisy>()
    .func<&takeNoisyConstRef>("take"_hs);

  if (entt::meta_type type = entt::resolve<Noisy>()) {
    if (entt::meta_func func = type.func("take"_hs)) {
      if (entt::meta_any ret = func.invoke({}, Noisy{73})) {
        std::cout << "OK\n";
      }
    }
  }
}
```

This has slightly different output in 3.2.2 and master but in either case, **the copy constructor is not used.**

```
// 3.2.2
Data ctor (73)
Got 73
Dtor
OK

// master
Data ctor (73)
Move ctor
Got 73
Dtor
Dtor
OK
```

If I comment out the copy constructor, the function doesn't register. We run into a [static_assert](https://github.com/skypjack/entt/blob/0dfd2aa714e7bc6d457dd011091d37645dd76506/src/entt/meta/meta.hpp#L352). If this was real code, I could just use a pointer instead of a reference so this is no big deal. This was previously discussed in #336.

**Comment by skypjack** [comment]
Oh, wait. This _works as intended_ in a sense.

The meta system is designed to let the user decide what to do and when to do it rather than adopting a fixed policy all the times. So, you can decide when you want to pass an actual object by copy or by reference as an argument (by wrapping it in a `std::ref`), as well as a a `meta_any` (by dereferencing it like `*any`). Similarly, you can decide when you want to _capture_ a return value that is a reference by copy or by value (with the `entt::as_alias_t` type used on registration).

In this case, it doesn't matter if you're not actually copying the object. Because you pass it directly to the function, you're telling to the underlying `meta_any` that you want it to _copy_ the value and create a detached instance to pass down the tube. In this case, _copy_ doesn't mean that it invokes the copy-constructor. Actually, since it's a temporary, the move constructor is used by the `meta_any` contains a copy now and must be copyable for itself, thus the copy constructor of the underlying type must exist.
As a side note, remember that internally we convert literally everything to `meta_any` because we need an opaque way to pass back and forth values. Otherwise we wouldn't use a reflection system if compile-time types were _known_.

To work around the issue, you should just pass the value by reference:
```
if (Noisy noisy{73}; entt::meta_any ret = func.invoke({}, std::ref(noisy))) {
    // ...
}
```
In this case, you're constructing an aliased `meta_any` that won't make any copy of the underlying object and therefore doesn't need it to be copy-constructible.

**Comment by Kerndog73** [comment]
I just realised that the function in the example fails to register in 3.2.2 but doesn't fail in master. So I deleted a big chunk of this comment!

---

Using a reference wrapper (and calling with `std::ref`) causes the call to fail at runtime **(but on 3.2.2 it works)**.

```C++
void f(std::reference_wrapper<std::unique_ptr<int>>);
```

Using a const reference wrapper fails at the call site because [this constructor](https://github.com/skypjack/entt/blob/0dfd2aa714e7bc6d457dd011091d37645dd76506/src/entt/meta/meta.hpp#L321) takes a non-const pointer. We run into that constructor when using `std::cref`. If we use `std::ref` instead, the call fails because the types don't match. This seems odd because you can call a function taking a const ref with `std::ref` but not a const reference wrapper.

```C++
void f(std::reference_wrapper<const std::unique_ptr<int>>);
```

Are these two behaviours bugs or features? I honestly don't know! 😀

**Comment by skypjack** [comment]
>Are these two behaviours bugs or features? I honestly don't know! 😀

Me neither! :smile:

When you cross the boundary of a reflection system is hard as heck to make the whole type system of C++ work nicely.

The main _problem_ here is that `meta_any` stores internally a non-const `void *`.
Whether you use a `const_cast` to get rid of constness for a constant reference wrapper or use a `const void *` internally, you lost the information on the constness of the original type and one can invoke a `cast<T>` to get a non-const reference to whatever type is shipped by the wrapper. This quickly becomes a way to pass const objects as non-const ones to meta functions.
We could store aside a boolean value and check it at runtime within `cast` but imho it doesn't worth it and can be annoying due to its runtime nature.

Similarly, since `meta_any` uses the reference wrapper as a _special token_, functions that require it as an argument won't work any time soon because it's wiped out when crossing the boundary.
In my opinion it's not a big problem though, mainly because the reference wrapper **isn't** meant to be used as an argument to a function in C++. You can do that ofc but there is no advantage on using a plain reference. Instead, their purpose is primarily to store references (as in _non-nullable pointers_) in containers, something that would be _impossible_ otherwise.

Probably these are corner cases that just don't fit well with the current features but I'm open to suggestions.
I see it would be great to have something _perfect_ but I'm perfectly fine with this kind of _limitations_ if they make it possible to have some features like aliasing. I'm pretty sure I won't try to attach a function that accepts a reference wrapper as an argument anyway while I like quite a lot the fact that I can avoid literally all copies back and forth with a proper configuration.

**Comment by Kerndog73** [comment]
Makes sense.
