### ISSUE TITLE
Documentation for entt::tag?

### ISSUE THREAD

**Issue by bjadamson** [skypjack/entt#419]
Hi, I can't find the documentation for entt::tag. I'm sure I'm blind, but could you point me to it? I found this reference [here](https://github.com/skypjack/entt/blob/master/docs/md/entity.md#tags), but it does't explain what a entt::tag is, or how to use it.

Thanks!

**Comment by OvermindDL1** [comment]
It's basically a ZST, so only when you want to know whether it exists for an entity or not, no data.

**Comment by Kerndog73** [comment]
The easiest way to understand `entt::tag` is probably to look at [its definition](https://github.com/skypjack/entt/blob/0dfd2aa714e7bc6d457dd011091d37645dd76506/src/entt/entity/helper.hpp#L165) which I'll repeat below.

```C++
template <std::uint32_t Value>
using tag = std::integral_constant<std::uint32_t, Value>;
```
Tags are used in ECS when you want to label things. They're an alternative to enums with some performance benefits (though that depends on how you use them). The example from the docs is repeated below:

```C++
registry.assign<entt::tag<"enemy"_hs>>(entity);
```

This is an alternative to defining the tag yourself.

```C++
struct Enemy {};
registry.assign<Enemy>(entity);
```

If you wanted to move all the enemies to the right then you could do this:

```C++
// One or the other
auto view = registry.view<Position, entt::tag<"enemy"_hs>>();
auto view = registry.view<Position, Enemy>();
// using less instead of each to omit empty components
view.less([](auto pos) {
  pos.x += 10;
});
```

This is much faster than if you used an enum.

I personally prefer to define empty types rather than use `entt::tag` because if you misspell the name of a struct, the compiler has your back. If you write `entt::tag<"enemy"_hs>` in one place and `entt::tag<"Enemy"_hs>` somewhere else then it could be difficult to notice that something has gone wrong. Also, I find that `entt::tag` is a bit more verbose than writing the name of a struct.

**Comment by skypjack** [comment]
Yeah, it's just a misplaced shortcut for `std::integral_constant` where the integral type is `ENTT_ID_TYPE`.
I'm moving it under `core/type_traits.hpp` because actually it's not strictly related to hashed strings. For example, you can easily use it with enums.
Nothing special though.

**Comment by bjadamson** [comment]
Ok, that makes sense. I think, IDK I'll think on it though. :)
