### ISSUE TITLE
msvc warnings

### ISSUE THREAD

**Issue by huwpascoe** [skypjack/entt#424]
```
Warning	C26439	This kind of function may not throw. Declare it 'noexcept' (f.6).		src\entt\meta\meta.hpp	403	
Warning	C26495	Variable 'entt::basic_registry<enum entt::entity>::pool_data::type_id' is uninitialized. Always initialize a member variable (type.6).		src\entt\entity\registry.hpp	118	
Warning	C26495	Variable 'entt::basic_registry<enum entt::entity>::pool_data::stamp' is uninitialized. Always initialize a member variable (type.6).		src\entt\entity\registry.hpp	118	
Warning	C26495	Variable 'entt::basic_registry<enum entt::entity>::pool_data::remove' is uninitialized. Always initialize a member variable (type.6).		src\entt\entity\registry.hpp	118	
Warning	C26495	Variable 'entt::basic_registry<enum entt::entity>::pool_data::assure' is uninitialized. Always initialize a member variable (type.6).		src\entt\entity\registry.hpp	118	
```

**Comment by skypjack** [comment]
I've suppressed the warnings on the registry. On the other side, the one for `meta_any` is a false positive.

`meta_any` works with raw storage (literally a bunch of bytes) in which it constructs objects using a placement new.
The move constructor may or may not invoke the move constructor for the underlying object and therefore the `noexcept`-ness of the `swap` is conditionally valid. However, since one of the functions it uses is erased (in particular `steal_fn`), we lose the information about is `noexcept`-ness. Because of this, the move constructor cannot be declared as 'noexcept` as well.

I've no idea on how to suppress it but making the move constructor `noexcept` would be wrong.
