### ISSUE TITLE
Unexpected behaviour when iterating a view

### ISSUE THREAD

**Issue by Omegastick** [skypjack/entt#427]
Sorry if I'm massively misunderstanding here, but I'm getting some quite unexpected behaviour from running the following code (part of my test suite, but I've put together a Minimal Reproducible Example):

```cpp
#include <iostream>

#include <entt/entt.hpp>

struct Parent
{
    unsigned int children = 0;
    entt::entity first = entt::null;
};

struct Child
{
    entt::entity parent = entt::null;
    entt::entity next = entt::null;
};

int main()
{
    entt::registry registry;

    const auto parent_entity = registry.create();
    const auto child_entity_1 = registry.create();
    const auto child_entity_2 = registry.create();

    auto &parent_component = registry.assign<Parent>(parent_entity);
    auto &child_component_1 = registry.assign<Child>(child_entity_1);
    auto &child_component_2 = registry.assign<Child>(child_entity_2);

    parent_component.children = 2;
    parent_component.first = child_entity_1;

    child_component_1.next = child_entity_2;
    child_component_1.parent = parent_entity;
    child_component_2.parent = parent_entity;

    registry.view<Child>().each([&](const auto entity, const auto &child) {
        if (!registry.valid(child.parent))
        {
            registry.destroy(entity);
        }
    });

    std::cout << registry.valid(child_entity_1) << "\n";
    std::cout << registry.valid(child_entity_2) << "\n";
    std::cout << registry.valid(parent_entity) << "\n";
}
```

Output:
```
1
1
0
```

During the `registry.view<Child>().each()` call, first `child_entity_1` is visited, but then `parent_entity` is visited (even though it doesn't have a `Child` component!). This results in `parent_entity` being destroyed. `child_entity_2` is never visited.

Am I misunderstanding something concept here? I was under the impression that all the entities with a `Child` component should be visited, and since they all have a valid parent entity they shouldn't be destroyed.

**Comment by skypjack** [comment]
You're doing a common mistake in C++, it has nothing to do with `EnTT`.
Imagine this:
```
std::vector<int> vec{};
auto &ref = vec.emplate_back(1);
vec.emplate_back(2);
```
Is `ref` still valid after the last line? It's not guaranteed, it may be or may be not invalidated. This depends on the fact that the vector reallocated, thus invalidating the reference.

You've exactly the same issue here:
```
auto &child_component_1 = registry.assign<Child>(child_entity_1);
auto &child_component_2 = registry.assign<Child>(child_entity_2);
```
Is `child_component_1` still valid after the second line? If it's not, then you've an UB when you modify it and this means that everything could happen.
Pools of components are just containers. They can reallocate as any other container.

The following version works as expected:
```
int main()
{
    entt::registry registry;

    const auto parent_entity = registry.create();
    const auto child_entity_1 = registry.create();
    const auto child_entity_2 = registry.create();

    registry.assign<Parent>(parent_entity, 2, child_entity_1);
    registry.assign<Child>(child_entity_1, parent_entity, child_entity_2);
    registry.assign<Child>(child_entity_2, parent_entity);

    registry.view<Child>().each([&](const auto entity, const auto &child) {
        if (!registry.valid(child.parent))
        {
            registry.destroy(entity);
        }
    });

    std::cout << registry.valid(child_entity_1) << "\n";
    std::cout << registry.valid(child_entity_2) << "\n";
    std::cout << registry.valid(parent_entity) << "\n";
}
```

If you don't want to pass arguments on construction, then:
* Initialize your components before creating new ones to avoid using potentially dangling pointers.
* Get (as in `registry::get<T>(entity)`) the component when you want to use it, so that you are guaranteed that the returned reference is a valid one.

**Comment by Omegastick** [comment]
Ah thanks, that's my bad then. Thanks a lot for the help. I had forgotten that the EnTT registry is basically a collection of vectors under the hood.

**Comment by skypjack** [comment]
Yup. It's a collection of pools and you can specialize them but at the end of the day all them are dynamic containers in a way or the other, so this issue is pretty common. :+1:
