### ISSUE TITLE
API for removing all components from an entity

### ISSUE THREAD

**Issue by DonKult** [skypjack/entt#446]
Hi,
lets say I have an entity I want to reload without modifying other entities which refer to this one by id. For this I would first like to strip all components from the entity but that already poses a problem:

Knowing what `registry.clear()` vs `registry.clear<Component>()` does I thought `registry.remove(entity)` might do it – turns out it doesn't, it is a no-op instead. `registry.visit(entity, [](auto const component){…})` might have worked if I could have figured out a way of doing the equivalent of `registry.remove<component>(entity)` with a `component` only known at runtime. All this runtime machinery seems rather powerful, but sadly I couldn't find too much documentation on how to make that actually work in practice. What seems to work is `registry.destroy(entity); assert(entity == registry.create(entity));`, but is that the way it should be done? I feel kinda uneasy about it for some reason. I had no qualms if that API were `registry.destroy(entity); assert(entity == registry.recycle(entity))` instead so I know its a baseless fear, but still. I can also not remove the feeling of a previous and by now probably ancient version having a `registry.clear(entity)` for this propose, but I haven't dug into history to checked. 

So this is as much a question of how this should be done nowadays as it is a request to fix and/or at least document the pitfalls a user might encounter along the way. Thanks!

**Comment by skypjack** [comment]
>All this runtime machinery seems rather powerful, but sadly I couldn't find too much documentation on how to make that actually work in practice.

Because it entered `EnTT` with the last release and only in the form of the `visit` so far.
More will come but it's a completely new part that must be designed carefully to avoid problems.

>Knowing what registry.clear() vs registry.clear<Component>() does I thought registry.remove(entity) might do it – turns out it doesn't, it is a no-op instead.

Actually it does not but it may be an interesting feature. Why not?

>What seems to work is registry.destroy(entity); assert(entity == registry.create(entity));, but is that the way it should be done?

When you destroy an entity, all its components are removed **and** its version is increased. Then it enters the list of available entities. It's a LIFO implicit list actually, that's why the same entity is returned if you do a `create` immediately after.

>I can also not remove the feeling of a previous and by now probably ancient version having a registry.clear(entity) for this propose, but I haven't dug into history to checked.

Oh... it did exist? Then is has been removed accidentally. Another good reason to put it back in place.
I didn't even remember it. Usually either I destroy entities or remove specific components.
That's probably why I didn't notice the error. I apologize. Is this the case then?

**Comment by DonKult** [comment]
for the record, I wasn't criticizing the design or anything, I was "just" seeing three wildly different potential directions I could explore while trying to (re)learn EnTT. I am fine with either as the "canonical path" and just though if there is one it should be implemented and/or documented.

If `remove()` vs `remove<>()` is the way to go I am happy to supply a patch, if it's `visit()` I am fine with waiting a little longer and helping documenting the eventual solution and if its the `destroy, create` dance I guess I will try coming up with documentation and a testcase. Or there is a fourth (fifth, sixth, …) way I do not know – or at the other side of the spectrum: A reason that should not be done at all.

**Comment by skypjack** [comment]
>I wasn't criticizing the design or anything

I'm fine with criticisms though, especially if they help to improve the library. Don't worry. :wink:

>If remove() vs remove<>() is the way to go I am happy to supply a patch, if it's visit() I am fine with waiting a little longer and helping documenting the eventual solution and if its the destroy, create dance I guess I will try coming up with documentation and a testcase. Or there is a fourth (fifth, sixth, …) way I do not know – or at the other side of the spectrum: A reason that should not be done at all.

I never had this requirement and this is probably the reason for which I missed this point.
Since `remove` receives a parameter pack, I think the `sizeof...(Component) == 0` case is a good candidate for doing what you pointed out. Isn't it?
`visit` is another beast and perhaps I'll extend it to create a parallel API that works with runtime component identifiers but there is no reason not to have the same functionality on both sides.

**Comment by skypjack** [comment]
I'm adding a function named `remove_all` to address this. I'm pushing it on `experimental`.

**Comment by samaursa** [comment]
Is this still experimental? It's quite a useful function to 'reset' an Entity without losing its ID.

In fact, I would love to have `remove_all<entt::exclude<Comp>>(...)` as well so that I can remove all but the component(s) I want to keep.

**Comment by skypjack** [comment]
@samaursa with the last version, `remove_all` translates to something similar:
```cpp
for(auto [id, storage]: registry.storage()) {
    storage.remove(entt);
}
```
As for _excluding_ one or more types from the list, you can check them as:
```cpp
for(auto [id, storage]: registry.storage()) {
    if(storage.type() != entt::type_id<Comp>()) {
        storage.remove(entt);
    }
}
```
Does it make sense?

**Comment by samaursa** [comment]
@skypjack thanks! it would be great to see that last function in the registry's API

**Comment by skypjack** [comment]
Mmm 🤔 maybe an utility file? I don't like to add functions to a class API when they don't really need to access the internals of the class itself.

**Comment by samaursa** [comment]
@skypjack yes, that would work (is there a utility file already with other utilities or would this be the first?)

**Comment by samaursa** [comment]
@skypjack it's not a big deal for personal projects, however optically it matters when trying to convince a larger team. I find that having functionality like this increases confidence in the library as it optically looks like a more 'complete' package.

Just to be clear, `entt` is already _quite_ complete. Since you asked why I cared about it I thought I would elaborate :)

**Comment by skypjack** [comment]
No, I see the reasons and I agree with you 100%. I meant why you care about if the file exists already or not. 😅 
As for the implementation of this feature, can I ask you to open a dedicate issue? It helps to keep track of it and to not forget about it too. 🙂 
Thanks in advance.

**Comment by samaursa** [comment]
Ah yes, the file I don't care about.

Sure, I will open a dedicated issue.
