### ISSUE TITLE
Event dispatcher thread safety

### ISSUE THREAD

**Issue by ZaMaZaN4iK** [skypjack/entt#473]
Hi!
At first - thank you for such awesome library! It helps me a lot!

I have some question about event dispatcher thread safety. I've read whole available documentation and wiki and found thread-safety notes for `entt::registry` (it isn't thread-safe - that's ok).

What about other classes like event dispatcher? Can I use one instance of event dispatcher from multiple threads?

What is my situation: I have multiple threads, which want to sent some signals to the main thread. Should I create separate dispatcher for every thread or I can share one dispatcher?

Thank you!

**Comment by skypjack** [comment]
In general, `EnTT` does not guarantee thread safety in any case but most of the times you can easily work with its data structures without even caring about it.
For example, if your threads aim to send different signals, they use different pools under the hood and will never interfere with each other. In all other cases, you've to provide your own access mechanism to guarantee thread safety.
The reason behind this is obvious: we, as users, are the only ones that can get the best out of how we use these objects, A built-in mechanism to make it fully thread safe would be a performance penalty in 99% of cases and it doesn't worth it imho.

I'm closing the issue since we have already discussed this on gitter too (it's you, right?). Feel free to reopen in case. :+1:
