### ISSUE TITLE
registry.get_or_assign does not change component

### ISSUE THREAD

**Issue by Eforen** [skypjack/entt#485]
Correct me if I am wrong but when this code is run

```cpp
int dx = 1;
int dy = 2;
registry.assign_or_replace<cMove>(player, 0, 0);
auto mover = registry.get_or_assign<cMove>(player);
mover.x = mover.x + dx;
mover.y = mover.y + dy;
auto check = registry.get_or_assign<cMove>(player);
```
Shouldn't check be `x = 1` and `y=2`? 
what I get is `x=0` and `y=0`

**Comment by skypjack** [comment]
`get_or_assign` returns a reference as many of the other member functions. Let's look at your snippet:
```
auto mover = registry.get_or_assign<cMove>(player);
```
You're making a copy of the returned instance here, then you modify the copy rather than the component within the registry.
Change the line above with the following one:
```
auto &mover = registry.get_or_assign<cMove>(player);
```
This should solve your issue.

**Comment by skypjack** [comment]
I assume that was the error. I'm closing the issue. Feel free to reopen it if your problem isn't solved.

**Comment by Eforen** [comment]
Thank you I am fairly sure it was indeed a I need more sleep error. (I just got back into C++ after a long time in languages that for you) I will confirm this soon and post result in the hopes this can help out someone else.
