### ISSUE TITLE
std::hash is not specialized for entt::hashed_string

### ISSUE THREAD

**Issue by Scarabytes** [skypjack/entt#492]
Hi there,

as far as I can tell, there is no specialization of `std::hash` for `entt::hashed_string`, making the simple construction of an `std::unordered_map<hashed_string, T>` impossible without defining a custom hash functor. Is this an oversight or intended? And if it is the latter, why?

Thanks in advance,
Scarabytes

**Comment by Innokentiy-Alaytsev** [comment]
Hello!

Note, that `entt::hashed_string` doesn't store the string data - it only references it. I don't know if it's important for your use case or not. I would just use `entt::hashed_string::value()` as a key in the dictionary.

**Comment by skypjack** [comment]
It's intended actually. `hashed_string` _converts_ to `entt::id_type`, that is, an integral type.
So, you should rather use `std::unordered_map<entt::id_type, T>` and generate the integral representation both at compile-time or runtime according with your needs.

@Innokentiy-Alaytsev 
>doesn't store the string data
Probably the time is come to undertake also this part but it would mean `strcmp` or similar. Not sure I want that all over since in 90% of cases I don't even need to use the string once hashed.

**Comment by Scarabytes** [comment]
Alright, thanks for the clarification!
