### ISSUE TITLE
Allow readonly data registration in meta

### ISSUE THREAD

**Issue by Vennor** [skypjack/entt#496]
This issue is a result of a short discussion on Discord.

Currently it's not possible to register a readonly `data` node in meta when using a pointer to member or any other value. It's _kind of_ possible when using the setter and getter overload of `data` but requires passing a null operation as the setter.

In my case, where I use a templated null operation function with variable parameters, the code looks like this.

```cpp
.data<&NullOp<ResourceHandle&,
        std::invoke_result_t<decltype(&ResourceHandle::GetIndex), ResourceHandle&>>,
    &ResourceHandle::GetIndex>("index"_hs);
```

I think that library support for readonly `data` would be beneficial. It's also possible in other reflection libraries like rttr or refl-cpp.

Below are some of my ideas of how the interface could look like, but ultimately any other way is fine as long as it's brief and explicit enough.

```cpp
// Setter and getter
.data<nullptr, &ResourceHandle::GetIndex>("index"_hs);
.data<&ResourceHandle::GetIndex>("index"_hs);
.data_readonly<&ResourceHandle::GetIndex>("index"_hs);

// Value
.data<&ResourceHandle::index>("index"_hs, entt::readonly_t);
.data_readonly<&ResourceHandle::index>("index"_hs);
```

**Comment by skypjack** [comment]
I'm experimenting with this one:
```cpp
.data<nullptr, &ResourceHandle::GetIndex>("index"_hs);
```
So far, all tests pass. It can also be used to attach non-const data members as read-only. For example:
```cpp
struct clazz {
    int value{4};
};

entt::meta<clazz>().data<nullptr, &clazz::value>("value"_hs);
```
In this case, setting the value always results in a failure. That is:
```cpp
clazz instance{};
assert(!entt::resolve<clazz>().data("value"_hs).set(instance, 42));
```
I like the `nullptr` approach more because it doesn't require to add an ugly `data_readonly` function for that. On the other hand, the _getter_-only overload isn't viable because it would conflict with another definition of `data`.

**Comment by Vennor** [comment]
I agree about the `data_readonly` function but then again the `data<nullptr, &clazz::value>` syntax looks kind of out of place when paired with a field pointer instead of a function. It's natural when using `nullptr` to assume that a valid value can be used too. What'd be the valid value in this case?

**Comment by Innokentiy-Alaytsev** [comment]
What about something like this:
```c++
namespace entt {
    struct no_setter_t{};

    static auto constexpr no_setter = static_cast< no_setter_t* > (nullptr);
}

entt::meta< Type >()
    .data< entt::no_setter, &Type::Getter >();
```

**Comment by skypjack** [comment]
Currently and for large part, you can see `.data<&clazz::member>` as an alias for `.data<&clazz::member, &clazz::member>`.
This means that it's even possible to use a member as a getter and another member as a setter for the sam _meta variable_. Functions are just another player in this game.
Therefore, `.data<nullptr, &clazz::value>` seems a logical consequence to me. The first should just do that if the member is const, in the second case you can force a _meta-constness_ by not setting the setter.

Of course, I'm working to clean-up the multiple overloads in meta and to make this full-featured since is has some flaws at the moment imho. :+1:

**Comment by skypjack** [comment]
See branch `experimental`. Null setters are supported and I made explicit the fact that `data<&clazz::member>` is an alias for `data<&clazz::member, &clazz::member>`.
The sole difference is that in the first case constness is intercepted and treated correctly while with the second case you can _force_ a const meta data member associated to a non-const data member from the C++ class.

**Comment by skypjack** [comment]
And I've also indecently reduced the amount of code in that part! :smile:

**Comment by Vennor** [comment]
Oh, I didn't know it's an alias. Now it makes sense. Thanks. :)
