### ISSUE TITLE
iterators order

### ISSUE THREAD

**Issue by dbacchet** [skypjack/entt#5]
Hi Michele, great project. I've been using ECS for medium/large scale simulations for a while and this library has a great potential, being fast, small and easily embeddable.

I spent some time experimenting with EnTT and the only thing that feels strange is the default order in which the entities are returned in a view.
The `begin()` and `end()` iterators refer respectively to the end and beginning of the container vector, and the `++it` operator goes backward.

I understand that the order of the entities/components can change at runtime, especially with the (very appropriate) swap-with-last on remove, but I believe that having iterators that reflect as much as possible the order used by the user and behaving as close as possible as the standard iterator makes the system easier to understand.

Any particular reason for the actual order (except for not storing the actual number of entities in the View)?

I can provide a patch or open a pull request if you believe that the modification makes sense.
Thanks!
Davide

**Comment by skypjack** [comment]
I'm glad you like the project. I hope it works fine for you.  
Let me try to explain the reasons behind the iterators order and why users should not care about that.

First of all, when you use a pure ECS approach, your systems shouldn't be affected by the order of the entities. All what you want is the set of entities that have specific properties (components) to perform an action on them. They come from who knows where and why within the rest of the codebase, so how could you guess that the order is _wrong_?

That being said, the actual reason is mainly due to a feature of my project: it gives you the chance to add or remove entities while iterating without invalidating iterators.  
Let's imagine we iterate in order now:

* You add an entity, it goes to the end of the list. Anyway the entity shouldn't be returned during the current iteration, for it takes its part in the game starting from the next iteration. How would you skip it when reaching the end? Would you put it in a secondary list users should merge explicitly at the end of the loop (for EnTT cannot say what's the right time to merge it)? Performance hit. Would you put it in a skip list adding an `if` within the iterator to know when it's time to _stop_ returning entities? Performance hit. What about the end iterator then? I cannot even imagine how to correctly handle it.

* You remove an entity, the last one is picked up to replace it. Isn't it out-of-order now? Moreover, how do you keep track of the fact that the next `++` should not perform an increment and stay in place instead? You can use an `if`: performance hit. You can invalidate iterators: you don't have anymore an interesting feature. What about the end iterator then? It's no longer valid being it two steps past the end. Loops risk to become a hell.

Everything is solved by iterating backwards. Pretty simple, isn't it? :-)

If you want to open a PR I'd be glad to discuss it with you, as long as it doesn't affect any of the current features of EnTT. Otherwise I'll reject it.  
Have you any practical idea about how to implement it? If you want to discuss it here before to implement it, so that you don't spend time if it breaks things, I'm at your disposal.  
On the other side, if you are convinced now that backwards iteration is quite good, well... I'm happy when I've the chance to talk about design choices. Thank you for the question. ;-)

**Comment by dbacchet** [comment]
question answered :).
I didn't get the fact that iterators were not invalidated in case entities are added or removed.
Pretty handy and definitely worth the price of having a custom iteration order. Thanks!

Even with this approach there is another problem though; your assumption is valid only if there are no parent/child relations between entities.

the following code (tested with c5fb1a1) shows the problem:
```c++
struct Data {
    double val = 0.0;
    std::int32_t child = -1;
};

struct Dummy {
    int dummy = 0;
};

using ECS = entt::DefaultRegistry<Data, Dummy>; // Dummy is needed because having a single component triggers the static assert @ registry.hpp:213:5

int main(int argc, char *argv[]) {
    ECS ecs;
    // create entities with children
    std::vector<std::uint32_t> entities(6);
    for(auto i = 0; i < entities.size(); ++i) {
        auto entity = ecs.create();
        entities[i] = entity;
        auto &data = ecs.assign<Data>(entity, double(i), -1);
        if (i>3)
            data.child = entities[i-3];
    }

    std::cout << "Iterate without destroying entities" << std::endl;
    for(auto entity: ecs.view<Data>()) {
        auto &data = ecs.get<Data>(entity);
        std::cout << "entity id: " << entity << " [val: " << data.val << ", child: " << data.child << std::endl;
    }
    std::cout << "Iterate and destroy all entities with children" << std::endl;
    for(auto entity: ecs.view<Data>()) {
        auto &data = ecs.get<Data>(entity);
        std::cout << "entity id: " << entity << " [val: " << data.val << ", child: " << data.child << std::endl;
        // remove all entities with children
        if (data.child>=0) {
            ecs.destroy(data.child);
            ecs.destroy(entity);
        }
    }

    return 0;
}
```
that produces the output:
```
Iterate without destroying entities
entity id: 5 [val: 5, child: 2
entity id: 4 [val: 4, child: 1
entity id: 3 [val: 3, child: -1
entity id: 2 [val: 2, child: -1
entity id: 1 [val: 1, child: -1
entity id: 0 [val: 0, child: -1
Iterate and destroy all entities with children
entity id: 5 [val: 5, child: 2
entity id: 4 [val: 4, child: 1
entity id: 3 [val: 3, child: -1
entity id: 4 [val: 4, child: 1
entity id: 3 [val: 3, child: -1
entity id: 0 [val: 0, child: -1
```
The iterators are technically speaking valid, but, as you see, entities '4' and '3' are iterated twice.
Any way to tell if an entity has already been processed or in general is valid?
thanks!

**Comment by skypjack** [comment]
>// Dummy is needed because having a single component triggers the static assert @ registry.hpp:213:5

Yeah, using an ECS for a single component doesn't make much sense and I put an assert to remember that to the users. :-)  
I'll look into your example and be back with a response as soon as possible.

**Comment by skypjack** [comment]
Oh, ok, I got it. That's because you are moving around an already visited item in front of the iterator for it's referenced as child of the current entity. This cannot be solved even if you iterate the other way around (simply swap the parent-child relationship and the problem will still be there).  

How can one solve it? Well, probably as I said in the previous comment. The underlying system could put aside the entities to be deleted/added and handle all of them as at once at the end of the iteration. The problem is that only the users know when the iterations end, therefore they should invoke a method explicitly. Drawback is that they also get a performance hit and an extra allocation for nothing in all those cases where you don't have any parent-child relationship.

My two cents: it's worth documenting it and let it be.  
From my point of view I'd prefer getting the best in terms of performance out of an ECS and be in charge of managing those situations where I've parent-child relationships. As an example, an user can iterate over the entities and order them somehow on a separate thread, then use the custom set until a change is detected (in this case, rebuild it from scratch if needed). In this case, a signalling system could help more than everything else.

What about that?

**Comment by dbacchet** [comment]
Totally agree. My point with the example was to highlight that even the reverse iterator could have problems in situation where you typically have to invalidate the iterator.

About the parent/child relationships, I cannot agree more on the fact that it should be managed by an higher level system (also because in real-life applications most of the time the operations and behaviors are customized and application specific).

Any plan on adding a `valid(entity)` functionality in the registry? A signaling system can be useful but one of the things I like the most in your design is that it doesn't mix object management/bookkeeping with an event system.

Thanks for updating the documentation, now the behavior is clear and consistent!
Closing the issue since the iteration order was only about style and not functionality.

**Comment by skypjack** [comment]
What do you expect exactly from a `valid(entity)` functionality? I mean, there is no reason not to add it. Anyway, `has<Component>(entity)` already does a great job for me, so I can't imagine what's the logic of `valid(entity)`. That's all. If you can give me more details, I'll kindly implement it.

**Comment by dbacchet** [comment]
forget. I'll implement it on top of the registry.

**Comment by skypjack** [comment]
Well, if it's​ useful and it doesn't bring performance hit or extra space, we can safely move it within EnTT. I'm at your disposal and... Just curious now. :-)
