### ISSUE TITLE
Use the [[nodiscard]] attribute

### ISSUE THREAD

**Issue by Kerndog73** [skypjack/entt#501]
The [`[[nodiscard]]`](https://en.cppreference.com/w/cpp/language/attributes/nodiscard) attribute can be used to find mistakes in user code (often very minor mistakes like creating an entity and then throwing it away without adding components). It's one of those things that I think all good C++ libraries (such as this one) should make use of.

Adding the attribute to all places that it makes sense is a big job. For some functions, it's obvious that they should have the attribute (`const` member functions). However, there are functions with side effects that should probably have the attribute too (like `registry::create`). Implementation details such as `private` or `internal` functions probably don't need the attribute but there's no harm in using it anyway.

The initial work required is quite large but I believe that the benefits outweigh the maintenence burden.

**Comment by skypjack** [comment]
Why should `const` member functions have the attribute in all cases?
I consider `[[nodiscard]]` more like something to use when the return type or computing it has side effects or unexpected costs, not as a tag to attach to most of the functions that has a return type other than `void`.
I don't even think a tool like this should be used to correct errors user side. Mainly because we don't have enough knowledge to know if these are actual errors. As an example, someone reserves entity 0 for _<reasons>_. I can imagine it as:
```
entt::registry registry;
registry.create();
// ...
```
You don't really have to store aside the entity since you know what its identifier is. So you can just ignore the return value.
Should this be considered an error for which to trigger a warning? Should we force users to do this instead: `(void)registry.create();`?

I see the advantages of this attribute but I wouldn't use it all around the codebase though.

**Comment by Kerndog73** [comment]
I see your point. It shouldn't be spammed everywhere. If we consider reserving entity 0 as a valid use-case then `registry::create` should not use the attribute.

**Comment by skypjack** [comment]
A review would be appreciated. :wink:

**Comment by skypjack** [comment]
Ah... apparently VS2017 doesn't like the `[[nodiscard]]` attribute on operators. I'll remove it.
Any other workaround of which you're aware to make it work?

**Comment by Kerndog73** [comment]
I skimmed through all the changes. Looks good! Lot's of functions are `[[nodiscard]]` now. About the MSVC bug, I have no idea about any workarounds.
