### ISSUE TITLE
Meta: allow changing the value of the referenced object when meta_any contains a reference without knowing its type

### ISSUE THREAD

**Issue by Vennor** [skypjack/entt#503]
It's currently possible to create `meta_any` instance that holds a reference, eg. by initializing with `std::ref()` or using `as_ref_t` policy for `meta_data` and `meta_func`.

When one knows the type of the held object it's possible to change the value by using the `cast` function.
```cpp
int foo{2};
meta_any bar{foo}
bar.cast<int>() = 4;

assert(foo == 4); // true
```
On the other hand it's currently not possible to change the value without at least knowing the object's size in bytes in which case ` cast` or `data` can be exploited.

```cpp
int foo{2};
int bar{4};
meta_any qux{std::ref(foo)};
meta_any baz{std::ref(bar)};
qux = baz; // qux now holds an owned non-reference value of 4

assert(foo == bar); // false
```

I'd appreciate having the possibility to change values of the referenced objects in some way. As discussed previously on Discord changing the behavior of `meta_any::operator=` might not be intuitive and break backwards compatibility, so it could be implemented as a function that changes the referenced value in case of references and the held value in case of owned values. Of course this should only happen if both values' `type_id`s match or possibly the right hand value is convertible to the left hand one.

I'm not sure what name would be appropriate here though, but I think it should be something that suggest piercing through the indirection layers. `inject` comes to mind but feels a bit out of place.

**Comment by skypjack** [comment]
I've investigated this request and unfortunately it's not so easy to do what you are asking.
At least, not without creating another erased function that _smells_. The price of this function is also paid by all users and for each instance of `meta_any`, even when the wrapper contains an actual object and therefore wouldn't need support for _overwriting_ the pointed object.

The more I think to it, the less I think `meta_any` is the right place for this functionality.
This class is meant to carry an object from point A to point B without knowing its type and definition. The one that creates the object and the one that consumes it must necessarily know what the actual type is (or to what type they want to convert it). If you want to assign a value of type `T` somewhere along the path, your best bet is `if(auto *ptr = any.try_cast<T>(); ptr) { *ptr = value; }` or similar.
It's not different from `if(!any.try_assign(value)) { ... }` but the price to pay is by far lower than having this functionality built-in.

Bear in mind that the ability to carry references and thus avoid copies is a nice-to-have side effect of the design of this class.
However, its primary use is that of carrying self-contained objects of any type. As with `std::any`, `operator=` _replaces_ the contained object with a new one that has potentially a different type. Even when the types match, there isn't an actual assignment under the hood. Instead, a `meta_any` performs something similar to `this->swap(meta_any{value});`. All this doesn't require the support for _assigning_ values to the contained object, since it's _immutable_ in a sense (until you `cast` or `try_cast` it and edit it through its reference).

I'm sorry but this time I can't really bend the design of this class to make room for this feature.
It would cost too much from my point of view and there exist workaround, so imho it doesn't worth it.

I'm closing the issue. Feel free to reopen it or continue the discussion anyway if you think I haven't explained the reasons well or you've the right idea to get around the costs of this function and make it work. :wink:

**Comment by skypjack** [comment]
I'm reopening this because **maybe** I found a way to do it. That is, not through the the `meta_any` object.
The idea is to use `meta_type` for that:
```
int value = 3;
entt::meta_any any{std::ref(value)};
any.type().set(any, 42);
// here value is 42
```
Obviously, if `any` is not an alias, the value it contains is modified. In other terms, `set` updates the _pointed object_, whatever it is.
This should help to get the container support done too, so... :)

**Comment by skypjack** [comment]
NVM. Same problems, different place. I'm sorry.
