### ISSUE TITLE
Modifying an entity in a view while iterating seems to corrupt the view

### ISSUE THREAD

**Issue by hydrogen18** [skypjack/entt#508]
I have a bunch of code that loops over every entity I have that is moving. My code will try and point the moving entity at the destination entity.

Before it does the "pointing" I check to see if they are close enough. If they are the destination is reach and moving can stop.

So I have this simple code
```
  registry.view<GameEntityPosition, GameEntityMotion, GameEntityMotionTarget>().each([&registry](entt::entity handle, auto & gep, auto & gem, auto const& motionTarget) {
    if (entitiesAreClose(registry, handle, motionTarget.destination)) {

      MotionUtils::removeAllMotionComponents(registry, handle);

      GameEntityOrbitTrack track(EllipseParameters(1100.0f, 1000.0f, 7600.0f));
      GameEntityDynamicOrbitTrack dynamicOrbit(motionTarget.destination);
      registry.emplace<GameEntityOrbitTrack>(handle, track);
      registry.emplace<GameEntityDynamicOrbitTrack>(handle, dynamicOrbit);

      // done - no more movement
      return;
    }
```

The `removeAllMotionComponents` does what you expect

```
void MotionUtils::removeAllMotionComponents(entt::registry & registry, entt::entity handle){
  registry.remove_if_exists<GameEntityMotion>(handle);
  registry.remove_if_exists<GameEntityMotionTarget>(handle);
  registry.remove_if_exists<GameEntityOrbitTrack>(handle);
  registry.remove_if_exists<GameEntityDynamicOrbitTrack>(handle);
}

```

After this is called in the above code I am noticing that my parameter "motionTarget" suddenly points at some other valid instance of GameEntityMotionTarget that my game created. So my game keeps running (does not crash) but my entity is suddenly at the wrong destination.

I replace it with this code

```
  registry.view<GameEntityPosition, GameEntityMotion, GameEntityMotionTarget>().each([&registry](entt::entity handle, auto & gep, auto & gem, auto const& motionTarget) {

    if (entitiesAreClose(registry, handle, motionTarget.destination)) {
      // Force a copy
      auto dst = motionTarget.destination;

      MotionUtils::removeAllMotionComponents(registry, handle);
      GameEntityOrbitTrack track(EllipseParameters(1100.0f, 1000.0f, 7600.0f));
      GameEntityDynamicOrbitTrack dynamicOrbit(dst);
      registry.emplace<GameEntityOrbitTrack>(handle, track);
      registry.emplace<GameEntityDynamicOrbitTrack>(handle, dynamicOrbit);

      // done - no more movement
      return;
    }
```

And everything works as expected. My entity winds up at the right destination. I have made a stack local copy of the `motionTarget.destination` that I care about.

Judging from other issues I have seen reported here, it is "safe" to modify an entity in any way I want while using `.each` from a view. But what I don't know is meant by safe? Do you just mean it won't wind up accessing invalid memory (and crashing, probably). Because in my above code the reference `motionTarget` is basically just a random object somewhere in the registry after I remove `GameEntityMotionTarget` from the entity. As a developer I would not expect that, although I can imagine it is probably just pointing somewhere into an array in memory which has now been moved around after removing the component.

It seems like it is very easy to wind up shooting yourself in the foot by using reference parameters, which are common all C++ code I have worked on. I am pretty sure changing my above code to `GameEntityMotionTarget motionTarget` would fix it by creating a copy when the function is called. Is there somewhere this can be documented?

**Comment by Innokentiy-Alaytsev** [comment]
It is safe to remove components from the current entity during the iteration, but after you do that all the references to the removed components will effectively become dangling. The reason why you have _some_ valid value pointed by the reference to an old value is the result of internal registry mechanics: in order to minimise memory moves the removed component instance is replaced with the last instance in the pool while the size of the pool is decreased.

The solution you've applied is correct in this case: you need a hard copy of the component if you plan to use its value after you remove it from the entity. The option of using a by-value function parameter is correct as well.

**Comment by skypjack** [comment]
This is how contiguous containers work in C++. What happens if you get a reference to the 'back()` element of a vector, then you remove an item in the middle? References are invalidated, they are dangling pointers.
You don't need to make copies though. Just re-arrange the body of your callback in such a way that you use references before invalidate them.
