### ISSUE TITLE
Add range-for compatible registry visit

### ISSUE THREAD

**Issue by Lawrencemm** [skypjack/entt#521]
Similar to #502, add overloads to registry `visit` methods that return range objects usable in a range-for loop.

```
for (auto type_id : registry.visit(entity))
{
    ...
}

for (auto type_id : registry.visit())
{
    ...
}
```

**Comment by skypjack** [comment]
Uhm... In this case we can't really make any optimization for the different approaches. So, I'd prefer to stick with a single method and not duplicate them.
I'm fine with returning an iterable object instead of having a callback based function though. Probably it's even better, since you can break the iteration if needed.
In fact, we could also return an opaque object that offer the possibility to query the type id and returns a `void *` for the variable. Win-win probably. What do you think about?

**Comment by Innokentiy-Alaytsev** [comment]
I'm still not sure about how you'll get the `void*`.

**Comment by skypjack** [comment]
In this case, I think it's easy, since we wrap the context variable directly and erase its type. It would be enough if the base class returned a `void *` and the derived one use a covariant override for the same purpose.

**Comment by Lawrencemm** [comment]
Can you construct an in-place meta_any easily from a type id and a void* ?

**Comment by skypjack** [comment]
Uhm. No, not yet. I don't even know if it's possible.
Probably, the best bet is to add to the meta type a function that does it:
```
auto any = type.from_void(ptr);
```
Why? Because the `meta_any` generates some stuff when needed from the actual type. For example the container proxy.
If you constructed the `meta_any` object without specifying the type, this wouldn't be possible.

**Comment by skypjack** [comment]
A little late but this is available on the `wip` branch (soon upstream). 🙂
