### ISSUE TITLE
Carbon copy entities to another registry

### ISSUE THREAD

**Issue by Lawrencemm** [skypjack/entt#522]
Currently we have the registry `assign` method whose doc string reads `Assigns entities to an empty registry`.

This method reconstructs the chain of destroyed entities.

If we have an existing registry, it should be possible to copy the entities without going through the whole array after copy and recreating the chain.

The first idea for an API that I can think of is an `assign` method that takes an existing registry as an argument so that it can access the existing registry's `destroyed` entity and not have to reconstruct the chain, or even a method on the existing registry to create a copy of itself without any pools, just a carbon copy of the entities.

I understand that `assign` is used at a lower-level for serialisation, and so the optimisation would need a lower-level version of `assign` that doesn't involve an existing registry; still it would be nice to have the clean API of just passing the existing registry without having to extract the destroyed entity and passing it to `assign`.

**Comment by skypjack** [comment]
I think what you suggest can be useful also for serialization purposes, since we wouldn't have to reconstruct the implicit list of destroyed entities anymore.
A possible approach is that of exposing a method that return the seed for this list:
```
const auto seed = registry.destroyed();
```
Then, add an overload of `assign` to _reset_ the same list:
```
other_registry.assign(seed);
```
The full snippet would be something like this:
```
entt::registry other;
other.assign(registry.data(), registry.data() + registry.size());
other.assign(registry.destroyed());
```
This way, we initialize a registry with a raw copy of a packed array, that is the fastest thing we can have. Moreover, this approach would be suitable also for serialization and would make it faster than what it is today.

So, all in all, imho we could pay a small price (two functions) to have an uniform interface that works in all cases, both for registry-to-registry serialization and for offline dumps.

Any comments?

**Comment by Lawrencemm** [comment]
It sounds good.

I don't like how @Innokentiy-Alaytsev has come up with more names than me, so I'm going to suggest a new name: `populate`.

I was actually a bit confused by the current name. It's a bit vague.

**Comment by skypjack** [comment]
:smile: let's see if @Innokentiy-Alaytsev accepts the challenge. :+1:

**Comment by Innokentiy-Alaytsev** [comment]
Nah, I'm not a "challenge person". There's not point in taking part in challenge if you know that you'll lose)

**Comment by oreyg** [comment]
```
entt::registry carbon_copy(entt::registry& source)
{
	entt::registry result;
	result.assign(source.data(), source.data() + source.size());
	result.destroy(source.data() + source.alive(), source.data() + source.size());
	return result;
}
```
No?

**Comment by oreyg** [comment]
Shouldn't it be
```
entt::registry carbon_copy(entt::registry& source)
{
	entt::registry result;
	result.assign(source.data(), source.data() + source.size());
	result.destroy(source.destroyed());
	return result;
}
```
?
