### ISSUE TITLE
Fixing the NOMINMAX C4003 bug

### ISSUE THREAD

**Issue by cugone** [skypjack/entt#530]
As discussed [in the FAQ](https://github.com/skypjack/entt/wiki/Frequently-Asked-Questions#warning-c4003-the-min-the-max-and-the-macro) and [in this issue](https://github.com/skypjack/entt/issues/96), trying to use `std::min` or `std::max` while including `<windows.h>` throws a C4003 error (with `permissive-` enabled.) There is a very simple work around: surround the `std::min` and `std::max` function names with parenthesis.

```
int a = 0;
int b = 1;
a = (std::min)(a, b);
```

The bug is related to the "most vexing parse" problem. Forcing the function name to be evaluated with parenthesis removes the `min` and `max` names from consideration as a macro replacement.

I looked through the single-header implementation of EnTT and there are only a handful of places where `std::min` and `std::max` are used. It would be trivial to add the appropriate changes in less than 5 minutes.

**Comment by skypjack** [comment]
How is it related to the most vexing parse exactly? Afaik it's due to macro definition for min/max pulled in by the Windows' headers.
What you're suggesting is to make the compiler recognize that we want to decay a name to a pointer to function. It works for many reasons but literally no major compiler suggests to do this. It's intrusive and changes somewhat the semantic of the whole thing.
Why should I do this if a solution exists already? I don't see the point to be honest.

**Comment by cugone** [comment]
I misspoke, no it's not MVP-related. Further research shows the use of parenthesis around a function name is designed to prevent macro expansion and is perfectly legal to due so:

https://stackoverflow.com/a/13600837/421178
https://www.geeksforgeeks.org/g-fact-36-function-declaration-with-extra-brackets-in-c/

It works because it is a requirement of the language itself (a holdover from C) regardless of what the compiler suggests to do:
https://softwareengineering.stackexchange.com/a/159848/15252

It does not, however, decay to a pointer.

**Comment by skypjack** [comment]
PR merged on `experimental`. Soon on `master`. Thanks for contributing.
