### ISSUE TITLE
How to save entities and components

### ISSUE THREAD

**Issue by Gelgavish** [skypjack/entt#555]
Hi, this is a very simple question but it's quite critical for my project.
I'm developing a game engine and I want to be able to save scenes and game, for that, I'll have to save the entities and their data, is there a way to do it?'

Thanks in advance! :D

**Comment by codylico** [comment]
[entt::basic_snapshot](https://entt.docsforge.com/master/api/entt/basic_snapshot/)?
it looks like you would need to bring your own `Archive` class, though.

**Comment by Gelgavish** [comment]
> it looks like you would need to bring your own `Archive` class, though.

Yeah, I think I'd, but a built it saving method would be nice to have :)

**Comment by bjadamson** [comment]
It's pretty simple using the cereal library. I find the flexibility of being able to plug in any archive nice!

**Comment by skypjack** [comment]
> I'll have to save the entities and their data

This is possible ofc. You have everything you need to get raw pointers and dimensions for your data from a registry.
It doesn't offer a _built-in_ method to pass a filename and get everything (un)serialized though, for one simple reason: what result do you expect?
All types? In 90% of cases I do it only for a few ones or I remap them (a trivial example is when my data is external resources). Also, what format? JSON? Okay but it's also so inefficient. Something more compact and less readable then? Anything you can edit by hand? What if (I actually do it) I wanted to serialize some things (e.g. a scene) into a human readable format and others into a more compact form to send over the network?
That's why I use and suggest to use external serializers and rely on `T *"` and size pairs. You can memcpy them if you like or iterate these compact arrays and serialize what you need with the _right_ format for your case.

So, the answer to your question is: yes, it's defintely possible but do not expect a magic button to press to get everything serialized in an arbitrary format. I'm sorry. 🙂

**Comment by Gelgavish** [comment]
Ok, so my initial goal was just to store and open the scenes as binary files. So you say I can iterate over an entity's components and store them, and then read them entity by entity?  How can I do such a thing (there's probably a better way to do it that I don't know about).

Thanks for the help! :)

**Comment by skypjack** [comment]
You don't even have to iterate components and entities. You can get the entities for a given type a `registry.data<T>()`. Similarly, you can get their components as `registry.raw<T>()`. Then you've range functionalities to load the same at once (an overload of `emplace` and so on).

**Comment by skypjack** [comment]
I'm closing this since the question has been answered apparently.
Feel free to continue the discussion here if needed or to reopen the issue if there is a good reason for that.
Thank you for asking. 👍

**Comment by Gelgavish** [comment]
Ok, thanks so much again for the help :D

**Comment by Gelgavish** [comment]
Hi, I don't want to waste your time so I'll sum up the issues I had:

- I don't know if I need to save my registry (write it to the binary file)

- When using `registry.data<T>` and `registry.raw<T>`,  how can I get all the components typenames because doing it manually seems pretty weird 

- When I tried to write an `entt::entity` to the file and read it, I got bad results, but it might be just me

If it doesn't bother you, I think that a small and simple code example will explain it better for me.

Anyway, thanks for your patience

**Comment by skypjack** [comment]
@Gelgavish dunno what I can do the for the first point, you should tell me what your requirements are, not the opposite. 🙂 
The type names are implicitly generated by EnTT, unless you assign them explicitly. You can retrieve them through the `type_name` class, see `type_info.hpp`.
Finally, `entt::entity` is an enum class. You can use `entt::to_integral` to cast it to its underlying type (usually `std::uint32_t`). If you can save and read an unsigned integer, then you can save it, don't worry. 😉 

I invite you to join the gitter channel or the discord server if you want a more direct discussion with me and other users (many of which are way more skilled than me).

**Comment by Gelgavish** [comment]
>  dunno what I can do for the first point, you should tell me what your requirements are, not the opposite. 
Oh, my bad, I just want a way to store my scenes/games, I mean by that that I need to store the entities, their components, and potentially the registry (to know the entities - components relations)

> The type names are implicitly generated by EnTT, unless you assign them explicitly. You can retrieve them through the type_name class, see type_info.hpp.
I'm using the single include but don't worry about it, I'll figure that out.

> Finally, entt::entity is an enum class. You can use entt::to_integral to cast it to its underlying type (usually std::uint32_t). If you can save and read an unsigned integer, then you can save it, don't worry. 
I actually managed to store an `entt:entity` as is but I guess your way is better

> I invite you to join the gitter channel or the discord server if you want a more direct discussion with me and other users (many of which are way more skilled than me).
I would love to do that :) how can I join them?

**Comment by skypjack** [comment]
@Gelgavish 

> I would love to do that :) how can I join them?

That's great, since I think it's way better to continue the discussion on these channels if possible! 🙂 
You can find the links on the REAMDE file, but here they are for your convenience:

[![Gitter chat](https://badges.gitter.im/skypjack/entt.png)](https://gitter.im/skypjack/entt) [![Discord channel](https://img.shields.io/discord/707607951396962417?logo=discord)](https://discord.gg/5BjPWBd)
