### ISSUE TITLE
Determine whether entt::meta_sequence_container is dynamic or fixed.

### ISSUE THREAD

**Issue by xissburg** [skypjack/entt#579]
There's currently no proper way to check if a `entt::meta_sequence_container` is dynamic or fixed, i.e. conforms to `internal::dynamic_sequence_container` trait or `internal::fixed_sequence_container`. Perhaps `internal::basic_dynamic_container` and `internal::fixed_sequence_container` could have an `is_dynamic` and/or `is_fixed` function? And then a similar function can be added to `meta_sequence_container::meta_sequence_container_proxy` and finally a function pointer can be added to `meta_sequence_container`. I am not yet very familiar with the code so this is just a guess of what it could be like.

For the time being, @Innokentiy-Alaytsev has suggested a clever hack that goes like this `auto is_dynamic = seq.resize(seq.size());`.

**Comment by skypjack** [comment]
I'm not sure this is the way to go. Imho there is something wrong in a code designed in such a way that we need to _query_ the underlying storage to know its characteristics. It smells of dynamic cast, if you get what I mean. Also, what @Innokentiy-Alaytsev is somewhat clever and probably the right thing to do.
Because of this, I'm closing the issue as _wontfix_. Feel free to continue the discussion though. I'm pretty easy to convince if you've the right arguments. 🙂

**Comment by xissburg** [comment]
In the same way you can query whether the meta type is a sequence container or an associative container, you could also be able to determine whether it's a dynamic or fixed container, and also other useful characteristics it has since there are different types of containers underneath. But for now I don't really think this specifically is very useful, so it might be something to consider in the future in case someone presents a stronger use case.

**Comment by Innokentiy-Alaytsev** [comment]
IMHO, some way of knowing the traits of the underlying type may be useful but in a very narrow area. Runtime-generic code may have expectations about the underlying types in the form of assertions like `is dynamically sized` or `is sequential`. I can't provide you with a realistic example of such code, but such use-case seems realistic to me.

**Comment by skypjack** [comment]
Though, in the case you described you can invoke `resize` and assert on the return type if you expected a resizable container.
This is also my point. If you want to assert on a sort of `is_resizable` method, you can assert directly on `resize`. No reason to add another method that gives you exactly the same information. 🙂 
That's why I asked for a reasonable use case that can justify the new method. I don't really see it at the moment.
