### ISSUE TITLE
Optimize linear search of pools

### ISSUE THREAD

**Issue by cholmquist** [skypjack/entt#596]
We're seeing quite a performance hit in the linear search in the registry::assure() function in version 3.5.2, line 202.
(It seems like the code has been refactored since 3.5.2 (conan version), but I think the problem is still there).

if(const auto it = std::find_if(pools.cbegin(), pools.cend(), [id = type_info<Component>::id()](const auto &pdata) { return id == pdata.type_id; }); it == pools.cend()) {

This code is executed a lot so the linear search has a big impact.
Can the search be replaced with an unordered_map, alternatively keeping the pools sorted and use a binary_search instead?

Thanks
/ Christian

**Comment by skypjack** [comment]
_We_? You can't say _we_ and expect a person not to be curious. 🙂 

Seriously, I agree. That became the default path with v3.5.2 but I immediately regretted it.
You can turn it off with the `ENTT_STANDALONE` definition though. The next release will go back to the old behavior instead.

Long story short, the goal was to make EnTT work out of the box in all cases, also when a dll is in use. That is why that version contains a _secure path_.
However, I think it wasn't a good choice, mainly because I find myself disabling it all the time. The next version will use sequential direct access as it was up to version 3.5.1 and I'll document the methods to make it work across boundaries, as this is simple yet almost unknown.

In fact, the next version will contain **a lot** of changes and new features, this is just one of many. 😄

**Comment by cholmquist** [comment]
Hi,thanks for the quick update! Setting ENTT_STANDALONE fixed the performance issue!

'We' refers to me and my closest colleagues at Ubisoft :) I can't disclose much else at this point.

cheers
/ Christian

**Comment by cholmquist** [comment]
Closing this since setting ENTT_STANDALONE has the desired effect

**Comment by skypjack** [comment]
> thanks for the quick update!

You're welcome. This one was easy. 🙂 

> We' refers to me and my closest colleagues at Ubisoft :) I can't disclose much else at this point.

This is really devilish instead!! 😄 
I'll be waiting patiently for you to reveal more in the future. 😉 
Ping me when it's possible, I'd be **very** glad!!
