### ISSUE TITLE
dll interface type_seq does not work as expected

### ISSUE THREAD

**Issue by Logris** [skypjack/entt#604]
Hi,

I have a base component library (Engine* .dll) which contains the _**entt::registry**_ and is built with the _ENTT_API_EXPORT_ flag
and one or more libraries (plugin _ *. dll) with an extended set of components that can be dynamically loaded

If you build (plugin*. dll) with the _ENTT_API_IMPORT_ flag, 
there will be a link error if I try to create the components defined in plugin.dll, since in Engine*.dll, _entt::type_seq<Plugin :: Component>::value()_ is not called anywhere

If you disable _ENTT_API_IMPORT_, then incorrect _entt::type_seq<T>_ will be generated.

version 3.3.6 worked correctly for me, after updating to 3.6.0 it broke.

**Comment by skypjack** [comment]
With v3.6 you mean `master`, `experimental`, `dev`, ...? Because there is no v3.6 release yet. 🙂 
Also, what's version 3.3.6? There doesn't exist that version, so I dunno exactly to what version you refer, sorry.

**Comment by Logris** [comment]
sorry, version 3.3.2

I am currently using master 3.6.0

**Comment by Logris** [comment]
version v3.5.2 works correctly

**Comment by skypjack** [comment]
Ok, though I don't know how it worked with v3.3.2 to be honest.
The only version that changed something in this sense what v3.5.2 and it introduced a performance hit because of that in case users created views on the fly all the times. Therefore, we decided to rollback those changes.

As far as I know, `ENTT_API_*` works fine if you have the same types on both sides of a boundary or at least such that one side of the boundary uses only a subset of the types used on the other side, otherwise it's expected to result in unresolved symbols.
The `test/lib` dir contains an example of a shared context to which `type_seq` refers to work properly across boundaries in all other cases instead. It uses `cr` under the hood but it's not mandatory, it's just a lib I liked to manage plugins and shared libraries in general.

The new poly storage on which I'm working should introduce yet another tool to work across boundaries without having to specialize `type_seq`, but you've to wait a little for that, since it's still under development.

**Comment by Logris** [comment]
Ok,
Thanks

**Comment by skypjack** [comment]
I invite you to join the `gitter`channel or the `discord` server in case of doubts.
I't pretty easy to make it work in fact, but still. 🙂

**Comment by Logris** [comment]
Thanks, 
I connected to gitter

**Comment by Sonolil** [comment]
I had the same problem. I don't remember which version I had but I changed to v3.5.2 and it worked fine.
