### ISSUE TITLE
Runtime Tag

### ISSUE THREAD

**Issue by FrancoisSestier** [skypjack/entt#607]
In my games the smallest unit is a tile, then chunks 256*256 tiles.
I'd like to have a tag per chunk to be able to retrieve entities with certain components in a particular chunk.

I'd like to do something like that : 

`registry.emplace<ChunkIDTag<chunkID>>>(entity);`

but i don't know how to do it since chunkID would need to be a constexpr.

Any Idea / approach to do what i want to do ?

Is there a way to generate all my tags at compile time ? 

Also found this related issue on stackoverflow https://stackoverflow.com/questions/64866335/entt-creating-new-component-types-at-runtime-or-tagging-a-subgroup-of-entiti

**Comment by skypjack** [comment]
No idea of what version of `EnTT` you are using, so I'll reply for what you can do with the upstream version.
At the moment, you can create your own storage classes and associate them with your chunks. Then you can combine them in a view pack like:
```
for(auto entt: view{chunk} | registry.view<other, components>()) { ... }
```
The first view will drive the iteration and therefore it will work as a filter. A filter by chunk in your case, that is what you want if I get it.
The long term plan is to make it possible to also associate pools to runtime defined names within the registry, but I don't see it as a eky feature in this case. Quite the opposite, since I guess your chunks are loaded and discarded as the user move around, so probably you want to bind the entities to the chunk itself and delete them upon destruction rather than to the registry.

**Comment by FrancoisSestier** [comment]
Thank you very much for answering so fast !

this is exactly what i need ! I'll try to look into that.

Yes i currently load and discard chunk but i will probably need to keep simulating entities in the background even if the user is not looking at it. I'll probably have a thread with it's own registry dedicated to loading each non currently cached chunk and it's entities every N ticks and simulating it.

**Comment by skypjack** [comment]
Oh, look at the range functionalities for that, especially if you want to copy full pools from one registry to another at some point in time.

Also, soon there will be a new _tool_ upstream for working with pools opaquely. So, copying a registry should become something like this:
```
source.visit([&](auto info) {
    auto from = source.storage(info);
    auto to = destination.storage(info);
    to.insert(from.data(), from.raw(), from.size());
});
```
This is out of my mind, the API could change and is fully customizable user side, but it should give you a grasp of what I mean.
It should also work with registries with different types for the entity identifiers. The types are/can be user defined, but the fact that this opaque storage proxy is fully customizable makes it easy to achieve.
