### ISSUE TITLE
Const registry groups no longer work

### ISSUE THREAD

**Issue by dBagrat** [skypjack/entt#626]
After recent commits (last week or month), any groups created from const registry are empty or invalid.
```cpp
auto group = registry.group< CompA, CompB >();
EXPECT_TRUE( !group.empty() );  //Ok
```
but, with the same registry state:
```cpp
const auto& c_reg = registry;
auto group = c_reg.group< const CompA, const CompB >();
EXPECT_TRUE( !group.empty() ); //Fails
```
Same with non-owning or partially-owned groups

//tested on latest MSVC yet

**Comment by skypjack** [comment]
🤔 isn't there a test for it? Really?

**Comment by dBagrat** [comment]
@skypjack ofc! I'll be glad to help ^_^
---
Finally I figured out why your tests are passing!!!
Typically in your tests, you create non-const groups before const ones, which changes the behavior.
```cpp
TEST( NonOwningGroup, AnotherConstGroupTest )
{
    entt::registry registry;
    const auto e0 = registry.create();
    registry.emplace< int >( e0 );
    registry.emplace< char >( e0 );

    //auto group = registry.group( entt::get< int, char > );
    auto cgroup = std::as_const( registry ).group( entt::get< const int, const char > );
    ASSERT_FALSE( cgroup.empty() );
}
```
This one will fail, until you uncomment commented line ;)

**Comment by skypjack** [comment]
Ahaaaaaa. Yeah, so, this is an intricate topic actually.

The registry **must** be const thread safe for _<reasons>_. This is roughly speaking the same guarantee you've from all the containers in the standard library. Though, a registry wasn't const thread safe so far, mainly because pools are lazy initialized.
The upstream version works like this instead:
* `registry::view` and `registry::group`: create pools and return fully initialized views/groups (the easy point 🙂).
* `registry::view const` and `registry::group const`: don't create pools, return _broken_ empty views/groups (that's fine, if the pool doesn't exist, views and groups are empty anyway, but they won't be _fixed_ if stored aside).

Where does your case fall?

You're requesting a group that was never used nor created before from a non-const registry. In this case (and only in this case) the group doesn't even create the _control_ structure to use to keep track of the elements in the group, nor it can _touch_ the pools to _initialize_ the group for the first time.
So, what you obtain is a completely invalid object and this is somewhat expected. 😄 

Now, I see how it is not in fact. Let's try to make a step further.
I've just introduced full support for custom pools. I'm working (on a private branch) to introduce the `multi_storage_tag` aside the already existing `dense_storage_tag` and `empty_storage_tag`.
This will be used to put aside default pools a new set of storage classes that work with _multiple types_. For example, tables but also fully interdependent types and so on. What else? Groups. Groups are a special case of the interdependent types where an entity can have only one of them.
So, groups are about to become a custom pool, the control block is about to disappear and the `group` class will go away as well. With the `multi_storage_tag` and another couple of things, we'll also be able to use groups to speed up views under the hood, though transparently.

So what? So, it doesn't worth it IMHO to invest in something that will be removed with the next release.
That is, the const thread safe registry is nice to have and I'm fine with paying the price for it until groups become a custom pool.

Though, again, I see how having a _broken group_ isn't optimal in the meantime.
My guess is that we could either remove the const `registry::group` overload or assert when the control block doesn't exist.
Users can still _announce_ the group in the meantime and have it work properly from the const overload, until all this is turned into something to configure at component level with custom pools and that's all.

Feedback? Suggestions?

**Comment by dBagrat** [comment]
Ohh.. i see
The problem is, that i pass `const registry&` to every function that shouldn't change any component data (e.g. rendering stuff), and yes, sometimes these groups have not yet been "touched".
I was a little shocked when about half of the render effects disappeared yesterday: D: D

And when i call .group<A,B,C> i expect to get something and not to create the group under the hood. (ofc I understand what's happening and why)
//but it's about logical constness vs "physical"
More thread-safety is awesome, but IMHO current behavior is not very intuitive from a "user" point of view.

Interesting problem actually!
Idk... maybe i should stick with older versions right now, unitl new stuffs are finally done )

**Comment by skypjack** [comment]
> Maybe instead of const overload we can have function named registry.group_if_exist ?

Yeah, I like `group_if_exists` more than `group_unsafe`, mainly because the latter would require to break the thread safe const contract.
Being only for a transitional period and still having the possibility to _announce_ the group to be able to use it from a const registry, it seems to me a good compromise.

> Maybe i should stick with older versions right now, unitl new stuffs are finally done

Dunno, it's up to you. Unless you're using some private function of a groups that isn't available otherwise, I would probably switch to a view in the meantime or _announce_ the group.
Consider that the final model in `EnTT` will be _view-only_, so the former is likely to be the right choice until new stuff is finally done. 😉
