### ISSUE TITLE
Async resource loader support?

### ISSUE THREAD

**Issue by jonesmz** [skypjack/entt#659]
If a resource loader needs to acquire data from disk / the network, the access may take a long time.

The load() function could be set up to return a handle to an incomplete resource, and EnTT wouldn't care. But it seems like there would be room for the resource loader interface to directly model this behavior.

How that would look, i'm unsure. I have vague ideas of a state variable, and a protocol involving the resource loader triggering entt to emit a signal when the load is completed.

**Comment by skypjack** [comment]
A cache isn't ticked nor anything else, so a state variable wouldn't really be considered. Moreover, triggering a signal when the load is completed won't work with concurrent accesses to the cache, where you've multiple readers running in parallel.
Because of how a loader is used by the cache class, you can return an empty handler on first call and trigger an actual load from disk. The next time the resource will be available and thus returned in sync to the caller. This will also get rid of concurrency issues.

**Comment by skypjack** [comment]
I'm closing this issue because the current desing already allow for solutions similar to that mentioned without having to change anything in the library.
Feel free to continue the discussion here if you think this isn't the case. Thanks.

**Comment by derchr** [comment]
> The next time the resource will be available and thus returned in sync to the caller.

How would one need to request access to the resource the second time? Accessing the cache would return the empty handle again, so is it necessary to call load() a second time?

**Comment by skypjack** [comment]
The result depends on the timing I guess @derchr since you triggered an async operation.
However, as long as the 'load` is idempotent, invoking it twice isn't really an issue anyway.
