### ISSUE TITLE
All destruction events should be published before components are destroyed.

### ISSUE THREAD

**Issue by xissburg** [skypjack/entt#668]
There's a difference in behavior when you invoke `registry.destroy(entity)`  or `registry.remove_all(entity)` and `registry.remove<A, B, C, ...>(entity)` which is that in the former, it publishes the destruction event and then destroys the component for each component type the entity has, and in the latter it publishes all destruction events for the given component types and _then_ it destroys each component. I think the former behavior is wrong.

It prevents you from accessing a component A of the same entity in a destruction observer of a component B.
In more detail, when `registry.destroy(entity)` or `registry.remove_all(entity)` are called, this https://github.com/skypjack/entt/blob/18832fcb3765e02e66b033a0cf723683762463c0/src/entt/entity/storage.hpp#L736 is called once for each pool that contains entity.

When `registry.remove<A,B,C,...>(entity)` is called, this is called instead https://github.com/skypjack/entt/blob/18832fcb3765e02e66b033a0cf723683762463c0/src/entt/entity/storage.hpp#L748 which as you can see, publishes all destruction events first, and then destroys each component after.

**Comment by skypjack** [comment]
I'm sorry to say this, but your analysis is wrong. 🙂 EnTT is built on top of independent pools and in all cases pools are managed separately. That is, even when you do `registry.remove<A, B, C, ...>(entity)`, you've a sequence like this:
* Signal for A, remove A.
* Signal for B, remove B.
* Signal for C, remove C.
* ...

It only happens that, in this case, you control the order because of the pack expansion, while in all others (that is, when `remove_all` is involved, since `destroy` invokes it internally) the order is undefined. That's all.

In no case is it that all events are sent before starting to destroy components.

The function you linked for the storage is from a single pool, it has nothing to do with the behavior across different pools.
It sends all events for all entities in a range and a given type T, then it destroys the Ts. Though, this happens for a single pool, a single type, **before** the range is passed to another pool. So, you've exactly the same sequence:
* Signals for A, remove As.
* Signals for B, remove Bs.
* Signals for C, remove Cs.
* ...

This behavior won't change any time soon, for two reasons:
* Emitting all signals before destroying would be more expensive and it's not desired in the vast majority of cases. I don't want to pay for it.
* This behavior would leak in the registry that should recognize if your pools support signals and eventually trigger them. It's even worse actually, because the registry needs this information also during a destroy and the type erasure makes it hard to have it, so we would have to erase a couple of extra functions to get the job done and store them aside in the registry. At the moment, the registry ignores the existence of signals. Even `on_construct` and the like are transparent to this information and only check it upon direct use. You can enable or disable signals for all types or on a per-type basis and everything will keep working fine unless for example you invoke `on_construct` for a type that hasn't signals enables. It would be really a pain if this notion leaked out from our pools instead.

As for your specific problem, you can easily solve it doing this (pseudocode):
```
for(auto [entity, comps...]: registry.view<Types...>().each()) {
    // do something
    registry.emplace<CleanupAndDestroy>(entity); // don't invoke destroy directly here, just mark entities
}
```
Then, let a system do a proper clean up and destroy:
```
auto view = registry.view<CleanupAndDestroy>();

for(auto entity: view) {
    // cleanup, whatever it means
}

registry.destroy(view.begin(), view.end());
```

**Comment by xissburg** [comment]
Thank you so much for the detailed response, you're awesome 🙂

I am angry at myself right now because I misinterpreted this function https://github.com/skypjack/entt/blob/18832fcb3765e02e66b033a0cf723683762463c0/src/entt/entity/storage.hpp#L749 thinking that it was destroying a range of component types and not a range of entities 🤦‍♂️. I was just generally confused as usual.

Still, I wish that could be the destruction behavior but I understand your concerns since most times this is not required and there is a performance and complexity penalty associated with it.

Your solution to this issue could be useful but it requires a special treatment for this kind of entity where this behavior is desired, i.e. I can't simply call `registry.destroy(entity)` on it. I'll rethink my problem and come up with a better solution to work around this limitation.

Thank you 👍

**Comment by skypjack** [comment]
Thecnically speaking, if A depends on B upon destruction, you could specialize the pools for these two types only and do your work before destroying them if the other type exists.
For example, you need A when B is removed, right? During a destroy, you've the registry and the entity passed to the pool. So:
* A could check if B exists and update it or whatever you need to do in this case.
* B could check if A exists and _<read above>_.
This way, it doesn't really matter what type is removed first. There is always a time in which both exist within a `remove` and can be used to do your work.

**Comment by xissburg** [comment]
That's basically what I did now. In `on_destroy_A` I check if B is still in the registry and call `on_destroy_B` manually. In `on_destroy_B` I check if A is still in the registry before proceeding. If it's not there it's because it was destroyed before B, which means `on_destroy_B` was already called manually, otherwise A will be destroyed after (and won't call `on_destroy_B` again because B won't be there when `on_destroy_A` is called next) and the logic should be run now. A little complicated to follow perhaps but it works. I will try to come up with a more clean strategy.

**Comment by skypjack** [comment]
Can I ask you why these types refer to each other when destructing them?
Maybe more details on the use case can help to find out a better solution.

**Comment by xissburg** [comment]
Essentially, B needs one bit of information that's contained in A when being cleaned up. That bit of information could be also added to B, but that'd require extra maintenance to keep everything in sync and in many cases this information is not needed by an entity that holds a B, because not all of them hold an A as well.

I think the solution described above is still the best I could come up with for now. It gets the job done and allows the entity to be destroyed using `registry.destroy(entity)` instead of needing a specialized function to be called.
