### ISSUE TITLE
Would it be reasonable to get the shared_ptr from a resource_handle?

### ISSUE THREAD

**Issue by Net5F** [skypjack/entt#679]
Hello, I've been using the resource management classes and they've been great, but I ran into an issue as I've started to build out my project's accompanying UI library.

I would like this UI lib to not enforce an entt dependency on the consumer (especially not a requirement that they use an entt::resource_cache), but I would like to continue using it in my own project. Unfortunately, there's no way that I can see to get the underlying shared_ptr from a resource_handle, so I don't seem to have a good way to pass lifetime responsibilities along to the UI objects that will be using the resources.

My question is: would it be reasonable to add a way to get the shared_ptr from a resource_handle? Or is there some complication that I'm not seeing?

**Comment by skypjack** [comment]
Technically speaking, it's trivial.
On the other side, I always wanted to remove the constraint on the shared pointer and have stateless loaders that manage their own memory. In this case, your suggestion would break the design.

Since caches are defined on a per-type basis, we could make the handle sfinae-friendly and allow user customizations. This would solve your issue. Actually, it's already possible in fact.
Another approach is that your library exports its own handle type to callers rather than the EnTT one. Overall, it would also make it easier to modify your engine internals without affecting other libraries, at least as long as the API of your handle doesn't change. As a first implementation, it can just be an alias for the EnTT handle.

**Comment by Net5F** [comment]
Good ideas, I went with the specialization approach for now and it's working just fine. Thanks!

**Comment by skypjack** [comment]
Please, leave this issue open. It made me think and I can achieve my goal with a few changes.
Briefly, if the loader returned a handle rather than a shared pointer, I could allow for specializations that don't rely on shared pointers anymore while still offering a default that works as it does nowadays.
A breaking change in the API, but also an easy one to manage, so I don't really care about it.
