### ISSUE TITLE
How to disable/deactivate components?

### ISSUE THREAD

**Issue by exilief** [skypjack/entt#69]
Hello! First I want to say, this is great! I'm glad I found this ECS implementation.
Even though I don't understand much of the C++14 template magic I can still use it quite easily.
But I have some problems finding the best way to do things. It might be a noob question, so I'm sorry if this is the wrong place to ask this.

So, I want to have a way to disable components, but store them for later. Is there an easy/obvious way to do this? I want to do this for different purposes, but mostly to hide parts of a GUI.

I can think of 3 possible ways, but none of them seem optimal:
1. Add a 'bool visible' to every Component that has something to be rendered. 
1. Add an empty component 'Visible' that entities must have to be rendered.
1. Keep a storage for components where I move disabled ones temporarily (in this case maybe a PositionComponent).

1 and 2 feel like a "hack" and if I want to do this for other Components, like disabling an Animation, I have to add a bool there as well, or invent another component 'Animating' which isn't very clean.
Option 3 could be reused for all types of components and in theory it sounds like the best solution, but can it be done efficiently? It looks like a feature that should be part of the Registry class to make it efficient, but there is probably a good reason to not add it, right? Could adding a `Registry::deactivate<Comp>(ent)` function (together with `activate`), that creates a new storage space only if needed, work?

If I do it in my own code, outside of the Registry class, would it work if I std::move it into my own container and then remove the component from the entity or would that be undefined behaviour? And if it does work, is it much slower than using option 1 or 2 above (for bigger components)?

I'm fine with using the 'Visible' component option for now, but I wanted to know if someone already found a more general way to do it.

**Comment by skypjack** [comment]
Hi @exilief 

I'm glad you like `EnTT`. Really appreciated.
Welcome and thank you for participating.

There is no way to _deactivate_ a component actually. I wouldn't make it part of the registry, mainly because I don't see a way to make it efficient both in terms of performance and memory usage. It seems to me that the sole viable solution is to create a sort of _secondary pool_ for each component where to store deactivated components, but... isn't it as if you defined a `MyDeactivatedType` component and use it instead?
Because of this, I prefer to keep it off the registry. I'm trying not to put in uncommon features that can easily implemented user side if required.

As a side note, I did something similar more than once. The _component-way_ of doing it is to create a dedicated component and attach or remove it when needed, thus what you mentioned in your second bullet.

There are plenty of cases where deactivating a component isn't desired. As an example, if you have one of your systems (rendering?) that gets the entities that have both `Sprite` and `Visible`, you can easily make an entity invisible by removing `Visible`, right? Ok, let's consider you don't use the `Visible` component and the registry lets you deactivate `Sprite`. Same result? Almost.
What about the other systems that don't care at all about `Visible` and would have touched instead the entities only because of `Sprite`? What would you expect from them? Should they ignore those entities as well or what else?  
If you deactivate a component, you are deactivating all the systems that somehow are interested in it, no matter if they were interested also in some other components or not. However, to obtain this you can just remove the component. To obtain the other result around you can attach and remove an auxiliary component like `Visible`, so that you get to disable only some systems.

I strongly suggest you to go along the _component-way_ if possible. It's far easier to reason on and to keep your codebase well organized. My two cents

---

I'm closing the issue for it's not properly an issue. Feel free to continue discussing here anyway if you have other questions.

**Comment by exilief** [comment]
Thank you for responding! It's great to see you so active here :) But you're right it's not really an issue, sorry about that.

Okay, yes I agree, doing it with the empty auxiliary component works well in this case and I'm doing it this way now. I saw you mention it in the discussion about Spaces as well, but I just thought it's only a dirty trick until we have a better way. I thought this because, as I said in my first post, if you have many components that can be deactivated in this sense the list of components gets very long and I thought this could be a (performance) problem.
But it probably isn't really now that I think about it... The code just gets a little ugly.

For the Animation case I still think it would be nice to deactivate it, as in "freezing" it. An animation isn't really used by any system other than the one that updates the animations. But it's not really worth the trouble I guess.

Alright, I'll keep learning and trying to figure stuff out myself. Thanks again!

**Comment by skypjack** [comment]
In case of animations, probably I would remove the components instead of freezing them.  
What kind of animations are you talking about exactly? If you can provide me with more details, maybe I can try to give you some hints.

---

Unfortunately, because of how `EnTT` works internally, there isn't a clean way to _deactivate_ a component. An entity has an instance or it doesn't have it. A pool then exports a packed array of entities that have that component.  
Introducing another pool for deactivated components would be a great waste of memory, trust me.  
The other way around could be to mark the entities with a bool in each pool. What's the drawback? Quite easy: when a view iterate components, it must check that bool before to return the entity. it means branches, `if`s all around your codebase that slow down the whole thing!!  
Using a dedicated component doesn't affect performance instead and doesn't waste more memory than any other solution. So... :-)
