### ISSUE TITLE
Assertion failed related to std::vector<bool> in 3.7.1

### ISSUE THREAD

**Issue by hls333555** [skypjack/entt#693]
When I'm trying to get value from a registered std::vector<bool> variable via reflection, an assertion occurs. I know STL has a special implementation for std::vector<bool>, but is there any solution to get bool element value correctly? Here's the test code: https://godbolt.org/z/Mb1P153dn, you can see the program rises an assertion when it tries to cast the element value to bool.
Thanks a lot!

**Comment by skypjack** [comment]
Ah, that's because of the infamous vector of bools. I guess something like this works probably:
```
auto boolVal = elementInstance.cast<typename std::vector<bool>::reference>();
```
Though, I see how it isn't convenient. Did it work with v3.6 using `bool` as far as you know?

**Comment by hls333555** [comment]
> <typename std::vector<bool>::reference>();

Thanks! That works perfectly!
However, I have not tried it on 3.6 sorry.

**Comment by hls333555** [comment]
> Ah, that's because of the infamous vector of bools. I guess something like this works probably:
> 
> ```
> auto boolVal = elementInstance.cast<typename std::vector<bool>::reference>();
> ```
> 
> Though, I see how it isn't convenient. Does it work with v3.6 using `bool` as far as you know?

Thanks! That works perfectly!
However, I have not tried it on 3.6 sorry.

**Comment by skypjack** [comment]
Another way around it is to register also this conversion:
```
entt::meta<typename std::vector<bool>::reference>().conv<bool>();
```
Then force the conversion before casting like:
```
if(elementInstance.allow_cast<bool>()) {
    auto boolVal = elementInstance.cast<bool>();
}
```
What happens here is roughly speaking that `allow_cast` invokes the conversion operator on the wrapper and returns you the boolean value.
Unfortunately, `std::vector<bool>` is such a mess that it's already impressive that fact that it can work in meta. 😄 

I'm closing the issue because I don't think there is anything I can do to get around the broken design of `std::vector<bool>`. 🤷‍♂️
