### ISSUE TITLE
Ordered Rendering by Systems

### ISSUE THREAD

**Issue by MonkeyToiletLadder** [skypjack/entt#698]
Is there a way to sort the systems so when they render will be in the correct order?  For example my entity has a grid component a core component and a background component.  While another entity must be render between the grid and the background.  Is it possible with your current implementation to sort systems based on rendering order?

**Comment by MonkeyToiletLadder** [comment]
Either i will have to sort the systems or make a rednering manager that stores references to components groups and sort those.

**Comment by MonkeyToiletLadder** [comment]
ah i have read the documentation and realized that there are no systems.  hmm.

**Comment by skypjack** [comment]
Hi, yeah, `EnTT` doesn't take over your systems. It's designed as a _container_ that you can use as you would use a vector or anything else.
So, you can sort your systems the way you prefer. If you want to sort entities and components instead, pools offer an in-place sorting functionality.
Let me know if you need more details. 👍

**Comment by MonkeyToiletLadder** [comment]
Would i sort the components from the register or would i have to make a sparse_set of components?  Would it be more efficient to have a seperate manager that stores and renders renderable components instead of sorting the components every draw call?

**Comment by MonkeyToiletLadder** [comment]
Another option would be to have multiple pools of components that way i dont need to sort them assuming your system allows this.
Sorry for the questions im a noob and reading through all the code is daunting.

**Comment by skypjack** [comment]
> Would i sort the components from the register or would i have to make a sparse_set of components?

You can sort pools directly from the registry as `reg.sort<T>(comparator)`, but you can also create your own storage class externally and sort it if you prefer.

> Would it be more efficient to have a seperate manager that stores and renders renderable components instead of sorting the components every draw call?

Yeah, maybe. It would also be more efficient to use for example insertion sort as an algorithm with the sorting functionality if you know that only a couple of elements are to be moved. The main problem I see with a separate manager is that you can't easily mix it with other views (it's possible, though more cumbersome), but maybe you don't even need to do that, so...
In any case, I'd rather go with what is easier to work with initially, then measure and eventually change approach if needed. I wouldn't try to optimize in advance just because. 🙂

**Comment by MonkeyToiletLadder** [comment]
I have one more question.  How are you able to store any structure as components without them having to inherit from a base component class?

**Comment by skypjack** [comment]
> How are you able to store any structure as components without them having to inherit from a base component class?

Type erasure, nothing special. All pool types are unknown even to the registry.
This approach has its pros and cons. This one is definetely a pro. 🙂
