### ISSUE TITLE
poly_storage not compatible with empty type optimization

### ISSUE THREAD

**Issue by cmartel** [skypjack/entt#699]
Following my comments in a different poly_storage question, I've isolated a working/compiling example of poly storage and dropped it back into my working codebase. But because I have a couple of empty components, empty type optimization suppresses the underlying pool storage (I think?) and the `get` or `raw` functions fail to compile when used within poly_storage. 

This can easily be reproduced in the `poly_storage` test file by adding an empty component and then emplacing it onto an entity in one of the test cases. 

#defining `ENTT_NO_ETO` fixes the compilation error, but I'm wondering if it'd be possible to exclude empty types for consideration in polymorphic storage altogether (as it arguably would make no sense anyway?), or other compile time fixes.

**Comment by skypjack** [comment]
Currently, you can  `if constexpr` on the storage type directly within the poly object.
Probably, we can make it more flexible by adding the type to the `poly_storage` trait, so that this becomes possible:
```
template<typename Entity, typename Type>
struct poly_storage_traits<Entity, Type, std::enable_if_t<!std::is_empty_v<Type>>> {
    using storage_type = poly<Storage<Entity>>;
};
```
I don't feel the need honestly, but it's viable and it takes something like 5 minutes to do, so... 🙂 

---

> the get or raw functions

By the way, `raw` is about to disappear.

**Comment by cmartel** [comment]
Good to know that `if constexpr` can easily bypass problematic template instantiations altogether, I was worried it'd require heavy-handed SFINAE hoops. I'll do that for now, thank you! :)

**Comment by skypjack** [comment]
> Probably, we can make it more flexible by adding the type to the poly_storage trait

Of course, I was wrong. 😄 This isn't possible since the poly storage cannot depend on the component type. It's... I mean, more or less the reason for which it exists. 🤷‍♂️ 
However, you can bounce your poly interface to a class that has a specialization for empty types. Or use `if constexpr` directly.
