### ISSUE TITLE
Just two questions 

### ISSUE THREAD

**Issue by Sonolil** [skypjack/entt#705]
Hi, relative newcomer here. I really like entt so far. 

I debated myself on opening an "issue" since I've never done that before and I don't exactly have "problems"...
But I can't really find anywhere else to ask really trivial (and possibly stupid) questions, so here goes. 
(Discord and the like not an option, sorry)

1. Is there a way to iterate through all the components attached to a single entity? It's not super evident in the wiki. There must be a way since snapshots are a thing and entities can correctly identify their components from potentially changing pools.

2. This is the default way to get a componnent... 

> if (reg.has<T>(e)) { return reg.get\<T\>(e); }      // 3.5.2

- I'm wondering if there is a way to safely store and use components directly. I'm already aware pointers are a bad option, but maybe a handle?
- If there isn't, what is the time complexity of get\<T\>() ? Do the pools being sparse sets imply it's O(1) ?
- I'm asking this because I come from a Unity background and the recommended usage there is store the components and use them directly to save lookup time - O(logN) -  and also for convenience. I can make a wrapper for convenience, but is the performance of component lookup via an entity a non-issue?

I somehow have a bad feeling that these two questions imply one of them is impossible. 
And I don't think I can find any issue that answers them. 

Thank you.

**Comment by skypjack** [comment]
> I debated myself on opening an "issue" since I've never done that before and I don't exactly have "problems"...

No worries. Wanna convert this issue in a discussione? Maybe it's a better choice.

> Is there a way to iterate through all the components attached to a single entity? It's not super evident in the wiki. There must be a way since snapshots are a thing and entities can correctly identify their components from potentially changing pools.

Yes, it is. [Here](https://github.com/skypjack/entt/discussions/684) it is a discussion about reasons behind the choice of EnTT. It also contains some links to examples and whatnot. [This](https://github.com/skypjack/entt/issues/696) is a more recent issue instead that also contains an updated example and a few insights.

> I'm wondering if there is a way to safely store and use components directly. I'm already aware pointers are a bad option, but maybe a handle?

The current stable release suffers from pointer invalidation when adding and removing components, you're right. It's possible to define a custom pool to have fully stable pointers or you can use entities to retrieve components. Another option is that of defining a handle, it's not that hard but there isn't a built-in one since getting a component from an entity is very cheap with EnTT.
That being said, `experimental` contains already some changes that make pointers stable when adding components. I'm working on a few others that will do the same when removing components (under certain conditions at least). So, another option is also to wait for the next stable release. 🙂 

> If there isn't, what is the time complexity of get<T>() ? Do the pools being sparse sets imply it's O(1) ?

As I said, there are other options. In any case, the complexity is O(1), correct.

> I'm asking this because I come from a Unity background and the recommended usage there is store the components and use them directly to save lookup time - O(logN) - and also for convenienc

Unity _old_ component model has stable pointers but isn't properly an ECS. The new model instead is a full featured entity component system afaik and its underlying model isn't stable pointer friendly at all for many reasons.
EnTT uses a completely different approach with its pros and cons. One of the pros is that its slightly more stable pointer friendly. I'll write about it in my [_ECS back and forth_ series](https://skypjack.github.io/2019-02-14-ecs-baf-part-1/) sooner or later, if you're interested.

**Comment by Sonolil** [comment]
Thank you for the response. I'm not a native speaker/writer so I can't thrive in a convo environment... but this really answers the question nicely. Stable pointer is not an issue if the performance cost of retrieval from entity is negligible. I can already make my components inherit a custom class to simulate Unity style lingo but I'm not sure if it's efficient (8 bytes more per instance). It would be nice if there is a built-in one since the only issue left right now for ECS imo is the "convenience" part. 

I'm so glad they both work, I will gladly continue using entt in the future. Keep up the great work! I'm sure there are many of us silently using this ECS library for their personal projects. I'll bookmark the series.

**Comment by skypjack** [comment]
The only way to have a handle that doesn't rely on pointer stability is to pay some memory for it, so 8 bytes seems reasonable.
Bythe way, can I close the issue or do you have any other question on the topic? 🙂

**Comment by Innokentiy-Alaytsev** [comment]
> I can already make my components inherit a custom class to simulate Unity style lingo but I'm not sure if it's efficient (8 bytes more per instance).

Keep in mind that if you have base component `A` and derived components `B` and `C` the view `registry.view< A >()` will not include entities with components `B` and `C`.

**Comment by Sonolil** [comment]
You may close the issue. Thank you both for the help :D

**Comment by skypjack** [comment]
> > I can already make my components inherit a custom class to simulate Unity style lingo but I'm not sure if it's efficient (8 bytes more per instance).
> 
> Keep in mind that if you have base component `A` and derived components `B` and `C`, the view `registry.view< A >()` will not include entities with components `B` and `C`.

It would work with a poly component probably, though you've the opposite problem in this case.
