### ISSUE TITLE
Entity: Best method/optimizations to delete lots of entities at once

### ISSUE THREAD

**Issue by growlitheharpo** [skypjack/entt#707]
*What version of entt are you using?* 3.6.0

### The Background Context:
I have "bundles" of entities that I store together in a `std::vector<entt::entity>`. A bundle is a logically related group of entities that are created and destroyed together; a particular game level may be a single bundle and the level next to it is a separate bundle. The entities do not have identical components. As an example: 100% of the entities in a level will have a `PositionComponent`, but 85% will have a `WallComponent`, and only 5% will have a `DamageZoneComponent`, etc. There are around 40 component types that could be present on the entities in a bundle, and around 300 pools total in the registry. The entities are always all created at the same time in the order they are stored in the `vector`, but the components are sometimes created later, or in a different order.

### The Issue:
For complex levels, these bundles contain thousands of entities. When a level is deleted, I do the following:
```C++
for (entt::entity e : bundle.entities)
    registry.destroy(e);
```

For around 6000 entities, this can take around 37.5ms in entt code (not including `on_destroy` signals). Inlining makes it hard to identify exactly where the time is spent, but I would assume the main culprits are cache misses and time spent moving around components, many of which are just going to be deleted in a few iterations anyway.

### The Questions:
1. Are there any optimizations I can/should take advantage of here to improve the destroy time? I know there is a range-destroy function, but it is functionally equivalent to what I am doing here (i.e. it is just a `for`-loop that calls `destroy` anyway). Perhaps I should be deleting ranges of the more common components first, or something like that?

2. Are there any recommendations in general for the bundle pattern that I've described? For example, are there other optimizations I could take advantage of if I used some sort of runtime tag to identify the entities that are part of a particular level instead of putting them in a `vector`? Of course, very few operations are performed on the list of entities in the bundle; `view`s and `group`s of the potential components are used almost always outside of the create/destroy steps.

**Comment by skypjack** [comment]
> For around 6000 entities, this can take around 37.5ms in entt code (not including on_destroy signals).

These numbers seem odd. I'm facing a similar optimization in a project that has a thousand pools and we are talking to save ~1ms or so. I guess it depends on the hw, but still ~40ms seems very high.

> I know there is a range-destroy function, but it is functionally equivalent to what I am doing here (i.e. it is just a for-loop that calls destroy anyway).

A review of the range destroy is in my pipeline, but it requires to split view iterators from views before proceeding.
Long story short, it works like that now because I wanted to also support view iterators. In this case, you can't cleanup a pool at a time because the view would appear as empty as soon as you reset one of its types. However, pools already support the range-remove and it's ofc optimized. So, the goal is to unwrap the iterators and use the optimized path when they don't belong to a view.

> Are there any optimizations I can/should take advantage of here to improve the destroy time?
> Are there any recommendations in general for the bundle pattern that I've described?

There are many, from cleaning up pools in parallel and force-destroying entities to using a pool mixin that tracks assigned components (for example with a bloom filter or such) and touches only a few storage classes on destruction and so on. The _best one_ depends on your mt requirements, that is, if you want to remove components/destroy entities in parallel or not.
The other option is to wait until I come up with and publish an update upstream because I'm working on this specific aspect, so it's probably only a matter of time to have something built-in.

**Comment by growlitheharpo** [comment]
> I guess it depends on the hw, but still ~40ms seems very high.

That 37.5ms number was averaged from captures on older hardware. On new hardware, the same code span still takes ~9ms. These numbers are from optimized (`/O2`) code with assertions and iterator debug checks disabled.

> There are many, from cleaning up pools in parallel and force-destroying entities to using a pool mixin that tracks assigned components (for example with a bloom filter or such) and touches only a few storage classes on destruction and so on. The best one depends on your mt requirements, that is, if you want to remove components/destroy entities in parallel or not.

I do have a thread pool available, so parallelization is an option. I'm curious what you would recommend here since not every component will be on every entity.

My primary alternative is some sort of throttling, i.e. moving the contents of the bundle to a `pendingDeletion` list and draining some smaller number of entities from that every frame.

> The other option is to wait until I come up with and publish an update upstream because I'm working on this specific aspect, so it's probably only a matter of time to have something built-in.

Due to API changes since 3.6.0, it's not certain I will be able to update to a new version but I will try to keep this option open if you think it will be soon.

**Comment by skypjack** [comment]
> since not every component will be on every entity

Upstream `remove` checks if the component exists before removing it and doesn't assert. It also exists a range version for it.

> i.e. moving the contents of the bundle to a pendingDeletion list and draining some smaller number of entities from that every frame.

Yeah, this is yet another option actually. What does a bundle contain?

> Due to API changes since 3.6.0, it's not certain I will be able to update to a new version but I will try to keep this option open if you think it will be soon.

Oh, it should be very easy anyway. As for the schedule, it's one of the things I've in the pipeline for work, so whether or not it's _soon_ depends only on your definition of soon. 🙂

**Comment by growlitheharpo** [comment]
> What does a bundle contain?

A bundle is basically just a `std::vector<entt::entity>`, there is no other "metadata" attached to it. It is just used to group logically related entities that are created and destroyed together, for example the entities that make up Level 1 would be one bundle, Level 2 is another bundle, Level 3 is another, etc. As you progress into Level 2, you no longer need Level 1, so I want to destroy all of its entities. This is done "seamlessly" (i.e. there's no load screen or anything) which is why it is important that it doesn't take too long.

**Comment by skypjack** [comment]
I see. Have you thought of using different registries for different levels, so as to discard one as a whole when needed?
Anyway, let me know if you want to investigate further one of the possible solutions or if you'll just wait me to push upstream the required changes to have something built-in. 🙂 
In both cases, please, don't close the issue, so that we can track all progresses here.

**Comment by skypjack** [comment]
I made a quick and dirty test: 100k entities with 1k components each. Deleting them with an optimized path takes ~30% of the time if compared to the current implementation. That is, less than half of the time.
I'm trying to figure out how to implement it properly but it should be available upstream (and fully documented) soon.

**Comment by skypjack** [comment]
Branch `wip` contains some general purpose optimizations for the `destroy` function that also work for the single entity version.
Moreover, it offers that _non-`EnTT` iterators optimization_ for the range-`destroy`. It would be great if you could give it a try and let me know.
