### ISSUE TITLE
"error C2066: cast to function type is illegal" on VS 2017

### ISSUE THREAD

**Issue by liquidnode** [skypjack/entt#713]
I get a C2066 error in this line

https://github.com/skypjack/entt/blob/0b3e3fd19adbb8b56b92908493559a7eda7ce644/src/entt/entity/organizer.hpp#L128

in VS 2017 Version 15.9.36. The error can be resolved by either dropping the /permissive- flag or by replacing the line with
`using dependency_type = std::size_t;`

**Comment by skypjack** [comment]
I don't think that replacing this:
```
using dependency_type = std::size_t(const bool, type_info *, const std::size_t);
```
With this:
```
using dependency_type = std::size_t;
```
Is the right thing to do. The former is a function type, the latter is an integral type, they are very different beasts.
It's unlikely that this change won't break existing code.

From what I can tell, this isn't the first time that the `permissive-` flag caused problems. See [this comment](https://github.com/skypjack/entt/issues/434#issuecomment-613090233) for example.
Literally all times it was due to a compiler issue and disabling the flag or updating the compiler solved the problem. So, I kindly suggest to do avoid `permissive-` or to use the most recent version of the last toolset (v142).

**Comment by skypjack** [comment]
Closing as _won't fix_. I can't really do anything in this case. I'm sorry. 🙂
