### ISSUE TITLE
[Question] Cache the result of the `get()` function?

### ISSUE THREAD

**Issue by neo-mashiro** [skypjack/entt#753]
Sorry for the basic question from a beginner, but I'd like to know about the price of calling `registry.get<T>()`. I have a `Entity` class like this:

```c++
class Entity {
  private:
    std::string name = "";
    entt::entity id = entt::null;
    entt::registry* registry;

  public:
    Entity(const std::string& name, entt::entity id, entt::registry* registry);
    ~Entity() {}

    template<typename T>
    T& GetComponent() {
        CORE_ASERT(registry->all_of<T>(id), "Component T not found in {0}!", name);
        return registry->get<T>(id);
    }
}
```

Since I come from Unity, whose `GetComponent()` method is known to be slow and not supposed to be invoked every frame, I'm thinking about caching the result of `registry->get<T>()` so that subsequent calls won't need to query the registry again. While caching is easy outside the class (on caller's side), it's a bit difficult to cache inside the class with generics (I'm still new to C++), and I wonder if this is at all necessary......

Can you tell me a bit more about the `get()` function? Does it check `registry->all_of<T>()` automatically? Is it costly? Also, I don't understand why the documentation says `get_or_emplace()` is slightly faster. Thank you~!

**Comment by skypjack** [comment]
The underlying pool in EnTT is based on sparse sets and getting an element is a O(1) lookup.
Caching would be still faster, granted, though pointers aren't stable unless you enable pointer stability on all pools (available since 3.8.x). Also, I confirm that `get` uses `all_of` (well, sort of actually, but let's assume this is the case) under the hood to assert in case the entity doesn't own the component.
`get_or_emplace` is faster than the following:
```cpp
if(registry.all_of<T>(e)) {
    return registry.get<T>(e);
} else {
    return registry.emplace<T>(e);
}
```
This is due to the fact that the pool lookup takes place only once. Probably not something you'll ever be able to measure but technically speaking it's slightly faster.

**Comment by neo-mashiro** [comment]
Thanks for clearing things up. Glad to hear that it's a O(1) operation, that's amazing. I think I won't cache then since the performance gain is negligible, but easy stability is definitely my first concern.
Thanks for sharing such a great open source library. I hope I could get a better understanding of it by reading your ECS back and forth series, cheers! 😄

**Comment by skypjack** [comment]
You're welcome. Feel free to join gitter or discord if you have any question. Usually easier than chatting on GH. Also, you can find many other devs there (by far more skilled than me) that can help you. 😉
