### ISSUE TITLE
Is there any way to extend meta_type generation currently?

### ISSUE THREAD

**Issue by SoftwareEngIsArt** [skypjack/entt#756]
Hello

I have seen that a way to extend `meta_type` generation is planned, but is there a proper work around to do it iin the current version?
I want to add a special property to all types that are children of some base class automatically, without the need to individually set the property for all of them. I have tried to hook a custom extension function into `type_seq`, however that causes a recursive initialization exception when the extension function attempts to call `meta<T>()` to set the property. 

The code looks somewhat like this:
```
namespace entt
{
	template<typename T>
	inline void extend_meta_type()
	{
        	meta<T>()	// Recursive init exception occurs here
			.prop("my property"_hs);
	}

	template<typename T>
	struct type_seq<T>
	{
        	static id_type value() noexcept 
        	{
        		static const id_type value = (extend_meta_type<T>(), internal::type_seq<T>::next());
			return value;
        	}
	}
}
```

**Comment by skypjack** [comment]
> I want to add a special property to all types that are children of some base class automatically, without the need to individually set the property for all of them.

You can set the property on the base class if it's registered with the meta system. Properties are looked up in the whole hierarchy when you query them.

**Comment by SoftwareEngIsArt** [comment]
I see, but what i would like to do is type-dependent. The property is generated individually for each type, that's why i wanted to extend meta generation. Sorry, i forgot to include it in the original message.

**Comment by skypjack** [comment]
Oh, sorry, didn't get it. 👍 
The current version doesn't allow to hook into the meta type generation, you're right. I'm struggling to find the best way for that at the moment, so as to provide something similar with the next version (there exists an open issue too).
Unfortunately, it's not that easy. At least, not as easy as I thought initially. The main issue is that customization points should run on meta types during initialization and before they get returned. Therefore, you can't expect to use a meta factory in your customization function, mainly because the latter wants a properly initialized meta type and aims at extending it.
So, the TL;DR version of it is that hook points require users to dig into the underlying representation of meta types (i.e. `meta_type_node` rather than the `meta_type` utility wrapper). This makes it a little more complex to use than simply invoking `.prop("my property"_hs);`.
I'm still trying to figure out if there exists an alternative solution that doesn't require me to add a second static variable for all types (this is something to avoid from my point of view). Any feedback or suggestions is appreciated ofc. 🙂

**Comment by skypjack** [comment]
> A quick idea i had could be to initialize the static variable with a lambda

So, I thought about this. The main issue is that I can't pass a `meta_factory`, because of an include hell.
However, we could look up a function that is invocable with a `meta_type_node *` object and you could have a meta factory in the user code. That would by-pass the issue entirely.
The other problem remains instead. If you reflect A and indirectly reflect it again in the hook, the runtime will enter a lock. I've no idea about how to get around this honestly.

**Comment by SoftwareEngIsArt** [comment]
Yeah, i currently do not see a valid thread-safe and compiler & platform independent solution that does not use a second static variable.

The only way i can think of to make it a little bit better is to put the second static inside an `if constexpr` so that the static variable would exist only for types that have meta extension, while the types that do not extend meta would only have 1 static variable.

**Comment by skypjack** [comment]
Be aware that using two statics would turn it immediately in a non-thread-safe initialization process.

**Comment by skypjack** [comment]
I close this since #735 already contains the same request in the list of additions to meta. Feel free to continue the discussion either here or in the other issue. :+1:
