### ISSUE TITLE
Changelog for EnTT

### ISSUE THREAD

**Issue by DJuego** [skypjack/entt#76]
Congrats for the last update!! Thank you very much for your hard work, @skypjack ! At times like these I miss a change log and a number version upgrade. :-}

DJuego

P.S. Serioulsy, Very happy! My only fear is that EnTT gets too big and slow. :-}

**Comment by skypjack** [comment]
I'm closing the issue because... This isn't an issue? :-)  
Kept note of the request for a changelog along with the next release. I'm lazy, but I'll do my best to write it.

In the meantime, because there isn't a new release yet, just a few notes about the merge on `master`:

* Added signals on construction/destruction for components and tags
* Added `Prototype` class to ease writing sort of templates to use to create new entities.
* Highly improved multi component standard views (still a work in progress, more has yet to come)
* Added custom sort function to use to sort pools of entities
* Moved everything towards a model based on tag dispatching to disambiguate overloads
* Added `dependency` utility
* `noexcept` is now `ENTT_NOEXCEPT` and exception handling can be fully disabled whether required (ie with UE4)
* Removed extra create functions from the registry as discussed a while ago
* bug fixing and minor changes all around

Everything is documented both in the code and in the README file, as usual.  
Feedback are appreciated.
