### ISSUE TITLE
How to access key-only associative container's values with meta?

### ISSUE THREAD

**Issue by SoftwareEngIsArt** [skypjack/entt#762]
Hi!

I am having issues accessing values of an `std::set` that is stored in a `meta_any` object.
How i understand it, when iterating over an associative container i get a `pair` where the first item is the key, and the second one is the value.
When iterating over a set (which is not empty, i have checked with a debugger) which is a key only type, the returned key has the correct type (`std::string` in this case) but the try_cast returns a nullptr. Am i doing something wrong?

**Comment by SoftwareEngIsArt** [comment]
In fact even for key-value containers, casting the key to it's type returns nullptr

**Comment by skypjack** [comment]
Keys in a set are read-only and so are the meta keys returned by an associative container that wraps a set.
Therefore, what you want is probably:
```cpp
pair.first.try_cast<const std::string>()
```
Using the non-const counterpart returns a null pointer instead.
It works the same with `cast` if you use reference types:
```cpp
pair.first.cast<const std::string &>()
```
Otherwise, you can use `cast` with a non-reference type which creates a copy of the contained element:
```cpp
pair.first.cast<std::string>()
```
Let me know if it works. :+1:

**Comment by SoftwareEngIsArt** [comment]
Thanks, that fixed it!
