### ISSUE TITLE
A question regarding the delegate implementation

### ISSUE THREAD

**Issue by zeyangl** [skypjack/entt#778]
Hello, 

This is not an issue regarding a bug or feature, just curious about the implementation of the delegate described in your article https://skypjack.github.io/2019-01-25-delegate-revised/

First of all thanks for writing an article in such detail, definitely very high quality C++ stuff. I am just curious how this is different from std::function. I've gone through the entire article and read the section talking about std::function. But as far as I know, most std::function implementations do not do alloc if there is no capture. Does that make it largely equivalent to this delegate concept, in which case we may consider std::function a superset of delegate, if ignoring the api difference for a moment?  

Thanks

**Comment by skypjack** [comment]
Actually, that implementation is very old and [the one currently available in EnTT](https://github.com/skypjack/entt/blob/master/src/entt/signal/delegate.hpp) is slightly different.
Among the other things, it supports currying on the first argument when dealing with free functions and decayed non-caputing lambads now.
Anyway, the delegate class isn't meant as a drop-in replacement for an `std::function` and it will never be. You're right in saying that in the vast majority of cases both are fine. However, I wouldn't call the `std::function` a superset of the delegate, since each of them offers some feature that aren't available in the counterpart.

**Comment by skypjack** [comment]
My gut feeling is that we can close this issue as _asnwered_. Feel free to continue the discussion here if this isn't the case.
