### ISSUE TITLE
Possible solution for recursive initialization lockup in user type extention hooks

### ISSUE THREAD

**Issue by switch-blade-stuff** [skypjack/entt#791]
Hello!

I have thought for a while on how to solve the issue of user hooks into the type generation requiring the type recursively, and here is what i came up with.
I have looked at how different compilers implement static locals (for example, GCC's `__cxa_guard_acquire` and `__cxa_guard_release`), and what they seem to do is to have a global recursive mutex and in addition, a guard object created alongside the variable storage. When the initialization occurs, it checks with the flags if it is already "initialized" and if not, locks the recursive mutex, then checks if it is already "in use" and if so throws an exception.

From what i understand, if a type hook would need it's own type recursively, it is only to get a pointer to it, thus here is my idea:

Have a custom static local-like implementation, that would return a pointer-like "handle" instead of locking up or throwing an exception, the handle would only contain a reference to the guard object and variable storage (could be a single pointer). If it is needed to only store a pointer to the type, this handle could be stored instead. When the user wants to actually dereference the handle, it would check if it is "initialized" and not "in use" and simple return nullptr otherwise, as the object is not safe to access.

This does allow to recursively call the function, however it is definitely uglier than static locals (would require a global static storage for the function, etc.).

Other than that, i don't see an efficient solution to the recursive initialization problem.

**Comment by skypjack** [comment]
Uhm... I must admit that I don't remember what's _the issue of user hooks into the type generation requiring the type recursively_. 😅 
Can I ask you to give me some context? I guess I'm missing something that you know instead. 🙂

**Comment by SoftwareEngIsArt** [comment]
From what i remember, if the user wants to hook into type generation, and lets say attenpts to register a function that has the type as it's argument it woul recursively require this type, but because it isnt finished initializing yet it would throw an exception.

I think you have mentioned it in #756, that either the extension code would need to use the type system on a low level or multiple statics would be needed to keep track of initialization.

So thats what ive been thinking about lately, as I've ran into the same problem in some of my code.

**Comment by skypjack** [comment]
Starving thread. Closed. Feel free to reopen it if you have an alternative proposal. Thanks!
