### ISSUE TITLE
Is it possible to create an unmanaged pointer to an object using only an entt::meta_type?

### ISSUE THREAD

**Issue by MatthewLoveday** [skypjack/entt#837]
I'm currently testing out switching from [RTTR ](https://www.rttr.org/)to using entt::meta and it's going great so far but I've hit this roadblock and I'm not sure how to continue.

I've got a very basic resource manager which is capable of loading a resource given only it's type as a string ID. Since this resource manager is using shared pointers for managing the lifetime of the resource I have to use the entt meta system to construct a shared pointer which I can extract from the meta_any to put into the resource pool. The code looks roughly like this:

```cpp
jsonStream.Serialize("type", resourceType);

entt::meta_type resourceTy = entt::resolve(entt::hashed_string{ resourceType.c_str() });

if (resourceTy)
{
    Resource* resourcePtr = nullptr;
    entt::meta_any resourceVariant = resourceTy.construct();

    resourcePtr = resourceVariant.data();

    if(resourcePtr)
    {
        resource.reset(resourcePtr);
        // cont...
    }
 }
```

The problem is of course that the meta_type::construct method does not create an unmanaged object that lives beyond the lifetime of the meta_any variable, and thus the resource shared pointer will soon point to garbage.

In RTTR the solution here is to use the `as_shared_ptr` [constructor policy](https://www.rttr.org/doc/master/structrttr_1_1policy_1_1ctor.html), which means that the construct call will return a shared ptr that I could immediately insert into the resource pool. The RTTR code for doing that would look like this:
```cpp
     registration::class_<Foo>("Foo")
                  .constructor<>()
                   (
                       policy::ctor::as_std_shared_ptr
                   );
```

I noticed that entt has an `as_ref` policy for factory functions which returns references, but I'm not sure if I can utilise that for what I need here. 

My only other idea is to reflect a static template function for all resource types which does the allocation and returns the pointer, but I was hoping there would be some way for me to use the construct method for this as otherwise I need to use the same hashed string to invoke the pointer constructor everywhere. It's not too much of a burden, but I thought it would be worth asking before proceeding down that route!

**Comment by skypjack** [comment]
> In RTTR the solution here is to use the as_shared_ptr [constructor policy](https://www.rttr.org/doc/master/structrttr_1_1policy_1_1ctor.html), which means that the construct call will return a shared ptr that I could immediately insert into the resource pool.

This is something that I try to avoid usually. Why should I construct an object and then insert it into a manager when I can construct it directly into the manager?
This is where the `entt::as_ref_t` helps for example. Imagine a meta constructor that accepts an id and a reference to a manager, constructs the object into the manager and returns a reference to the newly created instance so that you can fill it.
That is, something like [this](https://godbolt.org/z/4YKz79ohY). The tests also contain another example of the same technique if you're interested. [Here](https://github.com/skypjack/entt/blob/master/test/entt/meta/meta_ctor.cpp#L62) I register a function of the registry as a constructor for a component, then I use it [here](https://github.com/skypjack/entt/blob/master/test/entt/meta/meta_ctor.cpp#L181) to do the same things I've described above.
Note that, if your manager already offers a member function that you can use as a constructor, you can even exploit this kind of late binding to achieve the same result (just flip the arguments to the constructor and you're done).

I'm pretty sure that both meta and EnTT are missing many features.
However, sometimes I want to believe that getting used to other tools shouldn't be an excuse to replicate their functions, especially if we can have something better. 🙂 
Hopefully, this is your case. Let's see. I'll have some lag during the weekend but let me know if something is unclear. 👍

**Comment by MatthewLoveday** [comment]
Yeah this should work for my case, and I suppose since it's possible to extend the reflection data then even if something outside of this library needs to construct a resource outside the manager it should be possible to extend this logic. Thanks!
