### ISSUE TITLE
Petition for snapshot backwards compatibility

### ISSUE THREAD

**Issue by Sedomanai** [skypjack/entt#857]
The current snapshot (serialization) feature requires template parameters for all the components. This is fine, except whenever I introduce a new component type, which happens fairly regularly, I get errors loading binaries that were saved before the addition. Due to the tests I'm doing, I cannot afford to rebuild the registry/scene everytime I add a new type. Also, I have to do a full capture of components since I serialize various entity values as well, so unless I'm mistaken continous snapshot is not an option. I'm hoping there's a workaround to this.

edit: Nope sorry, did a few more tests and the problem persists. Also the order of component template parameters matter as well... which is somewhat error prone.

**Comment by skypjack** [comment]
Mmm interesting. I'd say that one can easily achieve it with a bit of reflection and without the snapshot stuff probably. Do you have any suggestions instead?

**Comment by Sedomanai** [comment]
Do you mean serializing the registry without using snapshots? That's not impossible but that would mean manually maintaining serialized data and rebuilding each entity and component one by one on my part. Unless I'm mistaken, I cannot (de)serialize the data containters i.e. sparse sets directly. I really like the built in snapshot system because it does that for me and I only have to send the archive (I use cereal) and target component type parameters. It's just that it fails when the in and out type args list is incompatible. 

It would be really nice if the snapshots can be deserialized in a way where the order doesn't matter or at the least where it can ignore types it cannot find in the binary. For example if the out snapshot captured <Position> and the in snapshot expects <Position, Velocity> but cannot find Velocity storage, it would be nice if it just ignored the Velocity parameter, order regardless. An empty component storage is fine, as long as it doesn't throw a runtime error. It might require additional trailing data of a hash of existing types at most... and markers indicating the beginning and end of the registry if there aren't already. (I also serialize other data outside of registry scope in the same archive). 

I'm afraid I cannot offer any more suggestions because I don't really know the specifics of how the snapshot actually de/serializes components and their types at the moment.

**Comment by LeonFretter** [comment]
@Sedomanai  In a project of mine I've built a snapshot and snapshot-loader for entt  which should tick the boxes you mention above.
The principle is as follows: Serialization doesn't occur on a "component-major" order, but rather on an entity-major order (less efficient than entt-inbuilt-solution but that wasn't my primary concern). 
For every entity, obtain a sequence of its components (you can create a `handle h`, call `h.visit` on it, obtain the `meta_type` and in the callback push a component-reference-wrapper to a vector of `Any` (which should be a small wrapper around `meta_any` which implements `serialize` for cereal)).
 Every of the reflected components needs to have a type-identifier stored with it, so that it may later be attached correctly when de-serializing. As I register my types with human-readable identifiers I use exactly those identifiers for that purpose. Without such identifiers you are forced to rely on serialization-order, which, as you've noted, creates incompatibilities.
So when de-serializing this vector of components, you can read its type, and then `emplace` (or `emplace_or_replace`) it to the entity (the entity you have already deserialized at that point using: 
```
auto e = entt::entity{};
archive(e);
reg.create(e); // entity-identifier is preserved
```
Side-note: I have no variadic templates in any of my serialization, and instead allow passing a `ShouldSerializePredicate` 
which is just a function returning a `bool` for a `const char*` (again, my component-types are reflected with a string).

I hope I could give a general overview, I realize that for all of the details I would need pages.

If anyone's interested let me know, and I might actually upload my implementation - again, disclaimer that it's not optimized.

Here's a snippet from a registry serialized to json:
```
{
    "e_count": 2,
    "0": {
        "e": 0,
        "components": [
            {
                "has_any": true,
                "type": "arch",
                "arch": {
                    "name": "cube"
                }
            },
            {
                "has_any": true,
                "type": "color",
                "color": {
                    "color": {
                        "x": 0.6000000238418579,
                        "y": 0.6000000238418579,
                        "z": 0.6000000238418579,
                        "w": 1.0
                    }
                }
            },
            {
                "has_any": true,
                "type": "mesh",
                "mesh": {
                    "name": "cube"
                }
            }
        ]
    },
    "1": {
        "e": 1,
        "components": [
            {
                "has_any": true,
                "type": "arch",
                "arch": {
                    "name": "food"
                }
            },
            {
                "has_any": true,
                "type": "consumable",
                "consumable": {
                    "nutrition": 0.5
                }
            }
        ]
    }
}

```

**Comment by LeonFretter** [comment]
I've uploaded my implementation to https://github.com/LeonFretter/entt_snapshot - hope it might be helpful to someone :)

**Comment by Sedomanai** [comment]
Thank you very much LeonFretter. I'll look into it and see if I can apply it to my project but in any case I'm grateful to you for sharing your precedent work

**Comment by skypjack** [comment]
@Sedomanai I'm looking into the issues that are still open. I must admit that I don't know exactly what the request is here.
Can I ask you to be more explicit? For example, with a proposed solution or api. As it stands, it's a little vague at the moment. Thanks.

**Comment by skypjack** [comment]
Closing this because it has been inactive for a couple of weeks now and I've not enough details.
