### ISSUE TITLE
Registry context, dense map and noexcept policy

### ISSUE THREAD

**Issue by skypjack** [skypjack/entt#867]
### Discussed in https://github.com/skypjack/entt/discussions/866

Registry context can copy its values when reallocated due to an emplace with exceptions disabled.
Please, refer to the linked discussion for further details.

**Comment by dpunsetAGS** [comment]
Thank you.

I did a small test case with latest from master to show the different behavior of dense_map.

```
#if !defined(__cpp_exceptions)
#define _HAS_EXCEPTIONS 0
#endif

#include <memory>
#include <cassert>

#include "entt/entt.hpp"

struct TestA
{
};

struct TestB
{
    std::unique_ptr<char> Test;
};

int main()
{
    entt::registry reg;

    reg.ctx().emplace<TestB>();

    {
        TestB* v = reg.ctx().find<TestB>();
        assert(v != nullptr);
    }

    reg.ctx().emplace<TestA>();

    {
        TestB* v = reg.ctx().find<TestB>();
        assert(v != nullptr);
    }
}
```

I'm using MSVC 14.29.30133. With exceptions enabled (/EHsc)  it works as expected. With exceptions disabled (no /EHsc) it asserts at the end.

**Comment by dpunsetAGS** [comment]
Apart from this problem I think it would be good to at least have a runtime check when basic_any is trying to copy a non-copyable type, just in case it gets to a situation like this (in basic_vtable when op == operation::copy)

**Comment by skypjack** [comment]
I think you're @dpunsetAGS right in saying that `ENTT_NOEXCEPT` shouldn't depend on whether exceptions are enabled or not.
That is, by default is should be `noexcept` no matter what. I don't even know if it makes sense to be able to _disable_ the `noexcept` keyword. It's not that it causes troubles when you disable the exceptions. Quite the opposite in fact as it works right now in `EnTT`.
Can you confirm that you can compile an UE4 project with `ENTT_NOEXCEPT` equal to `noexcept`? I wonder what the problem was [here](https://github.com/skypjack/entt/issues/61#issue-308566000) since it sounds like it wasn't the `noexcept`. 🤔

**Comment by dpunsetAGS** [comment]
Yes sure, we changed it ourselves for the time being, otherwise it would crash when playing outside of the editor. Having always noexcept hasn't shown any problem in any target (with exceptions or without). Clang seems to be ok with it too.

I don't know what was the exact problem in the link you wrote :( The build tool is mentioned, but does it mean UBT? (Unreal Build Tool) The tool that invokes the compiler? For sure in Unreal 4.27 this don't seem to cause any issue at all, and noexcept is used in many places without checking if exceptions are enabled. I could find on Google some old post with people complaining about warning C4577 being triggered, but I think it's been disabled for quite a few years. Maybe that was the issue?

**Comment by dpunsetAGS** [comment]
Correct me if I'm wrong, I'm just trying to confirm with myself the situation, but the problem seems to be that the way the dense_map works it relies on the fact that things will always move. The data in node is copiable, but the real data it is holding may not be (the only code that knows this is the vtable template instantiation), so it can't ever try to copy. A move constructor can't throw, because it could leave the moved object in a broken state, so it has to be marked with noexcept.

If ENTT_NOEXCEPT is allowed to exist it can give the impression that you can remove noexcept, but ultimately you can't do that, because dense_map relies on this feature to make sure the nodes are always moved.

What I don't understand is why this has any effect when compiling without exceptions. If exceptions are disabled exceptions won't trigger, so shouldn't it always choose move? Why is it choosing copy?

**Comment by skypjack** [comment]
Technically speaking, it's more about the `std::vector` than the `entt::dense_map`.
The vector decides whether to copy or move when reallocating based on the following condition:
```cpp
is_nothrow_move_constructible_v<_Ty> || !is_copy_constructible_v<_Ty>
```
An `any` has both a copy and move constructor that also are always available. We cannot make them conditionally enabled since the type of the contained object is erased. Therefore, `!is_copy_constructible_v<_Ty>` is always false.
On the other hand, `is_nothrow_move_constructible_v` looks into the move constructor to know if it's `noexcept`. It doesn't matter whether exceptions are enabled or not. I've tested the three major compilers and this trait returns false for a non-`noexcept` constructor in all cases when exceptions are disabled.
In your case, it fails because exceptions are disabled and this triggers the suppression of `ENTT_NOEXCEPT` (see `config.h`). This is an error in my opinion. That is, `ENTT_NOEXCEPT` shouldn't depend on exceptions (actually, it shouldn't even exist probably but let's ignore this aspect for the time being).

> If ENTT_NOEXCEPT is allowed to exist it can give the impression that you can remove noexcept, but ultimately you can't do that, because dense_map relies on this feature to make sure the nodes are always moved.

Uhm, yes and no. The context doesn't rely on this feature. It relies on the fact that it can reallocate the underlying vector of a map. This is possible in all cases when either your variables are copyable or `ENTT_NOEXCEPTION` isn't suppressed.

> What I don't understand is why this has any effect when compiling without exceptions. If exceptions are disabled exceptions won't trigger, so shouldn't it always choose move? Why is it choosing copy?

See above. This happens because `ENTT_NOEXCEPT` is cleared when you disable exceptions (and I agree that this is likely an error). As a consequence, the move constructor of `any` (which is `ENTT_NOEXCEPT`) is now a non-`noexcept` one. Therefore, `is_nothrow_move_constructible_v<any>` is false and since `any` also is copyable, the `std::vector` decides to copy its elements rather than moving them.
A very tricky issue that I wouldn't have noticed easily if it wasn't thanks to you. Really a good catch.

**Comment by dpunsetAGS** [comment]
Alright, thanks a lot for the fix and the nice explanation.

**Comment by dpunsetAGS** [comment]
One last thing about the commited fix... are you sure it's ok to still give the users the opportunity to clear ENTT_NOEXCEPT? If someone does the bug will come back.
