### ISSUE TITLE
Is it possible to decay an entt::meta_type which is a pointer?

### ISSUE THREAD

**Issue by MatthewLoveday** [skypjack/entt#878]
For example, say I have the following code:

```
int* myInt = nullptr;
entt::meta_any meta = myInt;
```

How could I get the meta_type for `int` (no pointer) using just the `meta_any` which has a type of `int*`? In versions before 3.10.0 it was possible to do this slightly hacky workaround:

```
entt::meta_type wrappedType = (*meta).type();
```

however this broke in 3.10.0 if the meta_any has a null value. Is there a supported way to do this?

**Comment by skypjack** [comment]
> In versions before 3.10.0 it was possible to do this slightly hacky workaround

Yeah, this was kinda UB I guess. Sort of _safe_ one since you weren't going to use the value but still risky at least.

> Is there a supported way to do this?

I guess no (but take this with a grain of salt). However, I think we can make `(*meta).type();` really _safe_ to do.
The other way around is to add a `remove_pointer` trait or similar but:
* I don't want to add yet another erased function (and thus instantiation) we don't really need most of the times
* It can still be implemented in terms of `(*meta).type();` under the hood and this would be _for free_ (kind of)

Let me figure it out. I plan to create a v3.10.1 with a couple of small fixes and this one could enter it as well.
