### ISSUE TITLE
What are entity versions used for aside from marking tombstones?

### ISSUE THREAD

**Issue by switch-blade-stuff** [skypjack/entt#886]
I have been reading through the documentation and the source for entities and i am a bit confused on what are entity versions used for except for marking tombstones. What i understand is that tombstone entities are identified by a special version number, and that when an entity is removed from a registry the version is incremented (or set explicitly). 

What are other possible uses for entity versions (both within the library and in general)?

**Comment by skypjack** [comment]
Identifiers are recycled in `EnTT` since day 0. That is, when you destroy an entity, its version is increased by 1.
Imagine to store identifiers aside for some reasons now. For example, in a quad tree. How do you know if that specific entity is still the same or a _recycled_ version with a completely different set of components?
The version helps with it. You can compare versions and find that the two identifers are not the same element, even though their entity part is the same.

**Comment by switch-blade-stuff** [comment]
I see, thank you! 
Which is why i guess most data-driven systems have entity versions. 
Completely missed that fact, need to get more sleep and less caffeine :D
