### ISSUE TITLE
Redefinition of operator[] in basic_view

### ISSUE THREAD

**Issue by THolding** [skypjack/entt#894]
Version: EnTT 3.10.1

Compilation error due to interpretation of `basic_view:: operator[](const entity_type) const` as being a redefinition of `basic_view:: operator[](const size_type) const` when `entity_type` is the same as `size_type`. 

Reproduction here (or see code below):
https://godbolt.org/z/1n4Ma3v6x

```C++
#include "entt/entt.hpp"

struct Comp {};
int main() {
    entt::basic_registry<uint64_t> registry;
    auto entity = registry.create();
    registry.emplace<Comp>(entity);
    auto v = registry.view<Comp>();

    return 0;
}

```

**Comment by skypjack** [comment]
The entity type should not be a plain, integral type. That is why the default one is defined as an enum.
However, let's assume that all integral types are also accepted. What would be the expected behavior in this case? It goes without saying that we can't have both the accessors, therefore we need to suppress one of them.

**Comment by THolding** [comment]
> The entity type should not be a plain, integral type
I think this is the key info I missed. I'd better go back and read the docs ;)
