### ISSUE TITLE
Is entt::emitter supported across DLL boundaries?

### ISSUE THREAD

**Issue by gamagan** [skypjack/entt#902]
`entt::emitter` crashes when I try it. I also tried the storage thing for the Event types (just in case): https://github.com/skypjack/entt/tree/master/test/lib/registry_plugin
and that doesn't present crashing.

**To Reproduce**
    Create the emitter in the EXE.
    Pass an emitter pointer to DLL.
    Use emitter::on() in DLL to subscribe to an event
    Use emitter::clear() in EXE during shutdown.
    Program crashes.

**Build**
    compiler: MSVC
    Version: 2022
    Link type: merged source
    Any specific flags: no

**Context**
This particular usecase is an EXE that dynamically loads DLLs. The EXE provides the DLLs pointers to the emitter so the DLLs can subscribe to and send events.

**Comment by gamagan** [comment]
Also, about event thread safety:

Is subscribing/unsubscribing, /sending/receiving event thread safe?

**Comment by skypjack** [comment]
Sorry for being late. Weekend out. I see that you've closed the issue. Did you solve it?

**Comment by gamagan** [comment]
Hi. I ended up going with a different event/signals library, so the problem is no longer applicable.

**Comment by skypjack** [comment]
Ok, no problems. Answering anyway for future readers, in case someone has the same question.

The emitter class works across boundaries, yeah. There also is a test under the lib directory (it uses [cr](https://github.com/fungos/cr.git) for the purpose).
Without a repro nor a library version on use, it's hard to say what your problem is. However, since it's related to the clear function, I can try to guess: maybe you're using different runtimes for the main executable and the plugin?

As for the thread safety of subscribing and whatever: no, they aren't thread safe.
It would be a waste of cpu cycles in the vast majority of (single threaded) cases and one can easily add up to achieve thread safety. That's more or less the ratio. 🤷‍♂️
