### ISSUE TITLE
Is there a way to listen to ctx updates?

### ISSUE THREAD

**Issue by grimaldini** [skypjack/entt#907]
Hi,
Is there a way to connect/disconnect to context variable updates? similar to how we can subscribe to component updates through `registry.on_construct/on_destruct`?
Thanks

**Comment by skypjack** [comment]
Hi, no, there is no built-in way, but you can still attach an observable object to the context and achieve your goal, no?

**Comment by grimaldini** [comment]
do you have a sample or blog on how to achieve this with an observer object? I'm assuming you are referring to the observer in the Reactive System section of the wiki... however, the description and usage is a bit unclear, if you could point me to a sample, it might help, thanks

**Comment by skypjack** [comment]
No, sorry. I got the covid and I replied/am replying in a bit of a hurry because I'm left behind with some things at the moment. 🙁 
I'm not referring to the observer class. Quite the opposite. I mean that you can just turn or wrap your type `T` into an observable class that also emits signals, then attach the latter to the context.

**Comment by grimaldini** [comment]
oh no, feel better!

**Comment by skypjack** [comment]
I think we can close this issue. Feel free to reopen it or create a new one if there are still doubts. Thank you.
