### ISSUE TITLE
Do you have any plan to make dense_multimap container ?

### ISSUE THREAD

**Issue by gamephysics** [skypjack/entt#910]
Hello!

entt has only dense_map, dense_set.

Do you have any plan to make dense_multimap container ?

**Comment by skypjack** [comment]
I don't but it might be an option actually. Should be easy to adapt the dense map. Do you want to give it a try?

**Comment by gamephysics** [comment]
I am trying to make hash grid map for collision, so I need to use dense multi-map for the performance.

**Comment by skypjack** [comment]
> Should be easy to adapt the dense map.

I tried to implement this and it basically turned out that the underlying data structure (technically, a glorified sparse set) isn't a good fit to support multiple elements in a bucket based dense map.
This is true unless one is willing to make a lot of compromises in terms of performance and functionalities. This would make it a niche implementation in turn and I don't want to maintain something that is pretty much useless.
Therefore, the answer is no. A corresponding dense multi-map will not be implemented. I'm sorry.

I'll close the issue soon if there are no comments, contribution proposals or suggestions on alternative approaches.

**Comment by exuvo** [comment]
@gamephysics take a look at https://github.com/greg7mdp/gtl 's flat_hash_map or parallel_flat_hash_map if those fit your needs.
