### ISSUE TITLE
entt::meta_type construct().data(), gives back a already destructed object.

### ISSUE THREAD

**Issue by valaphee** [skypjack/entt#915]
Hey,

currently I'm working on the network serialization part, and I already found a workaround. I'm using entt::meta for dynamic component creation:

```
struct SSectorMap {
  std::map<Location, entt::entity> sectors;
  std::queue<Location> sector_requests;

  void ReadFrom(const Utility::Buffer& buffer);
  void WriteTo(Utility::Buffer& buffer) const;
};
...
if (auto component_meta = entt::resolve(component_id)) {
  void* component_data = component_meta.construct().data();
  // gives back an already destructed struct
}
...
```

And I know that the only safe solution would be that construct(), etc. directly returns a pointer, or that meta_any doesn't manages its object, which could have memory-leaks,

But in the perspective that component_meta.construct() can be seen as equivalent to new SSectorMap() in this example, it would be logical

Currently I have a "constructor" prop where I return an unmanaged pointer, or is there any better method?

Kind regards
Valaphee.

**Comment by skypjack** [comment]
At first glance, the culprit is this line of code:
```cpp
void* component_data = component_meta.construct().data();
```
It's no different than doing this in C++:
```cpp
void* component_data = []() { my_type my_object{}; return &my_object; }();
```
That is, you construct an object, get its address and discard it immediately. What you've now is a dangling pointer. That is likely the reasons of your problems then.

Just to be clear, you **do not have** to return a pointer from a meta constructor. What you're doing is perfectly fine (well, it depends on the purpose actually, but still).
The problem is that you're taking the address of an object that you also throw away in the same expression.

**Comment by valaphee** [comment]
Thanks for your quick response!

This means I would just have to have meta_any in my scope, and copy the data, before going out of scope?

**Comment by skypjack** [comment]
You're welcome. 🙂
