### ISSUE TITLE
Nested emplace to context leads to apparent UB

### ISSUE THREAD

**Issue by xissburg** [skypjack/entt#916]
Emplacing a type to the registry context which in turn emplaces another entry to the context in its constructor leads to undefined behavior. Not sure if this would be a bug or an unsupported use case. Test case (see on godbolt https://godbolt.org/z/xTroqj95o):

```cpp
struct S {
    void bar() {}
};

struct A {
    A(entt::registry &registry) : m_registry(&registry) {
        registry.ctx().emplace<S>();
    }
    entt::registry *m_registry;

    void foo() {
        m_registry->ctx().get<S>().bar();
    }
};

int main() {
    entt::registry registry;
    registry.ctx().emplace<A>(registry);
    auto &a = registry.ctx().get<A>();
    a.foo();
}
```

**Comment by skypjack** [comment]
This is the expected behavior actually. Under the hood, context variables are stored in a hash map. The latter constructs the object in-place and triggers a rehash step if needed. It's not meant to support this kind of recursive access patterns, I'm sorry. I would be surprised if `std::unordered_map` (of which the dense map is a sort of drop-in replacement) supported this behavior.

**Comment by xissburg** [comment]
Ok, not a problem at all. I have since modified my code to avoid this situation. Thanks for the explanation!
