### ISSUE TITLE
Replace deprecated `std::aligned_storage_t`.

### ISSUE THREAD

**Issue by LucidSigma** [skypjack/entt#919]
Firstly, let me thank you for all the effort you have put into making this library. :)

[`std::aligned_storage_t` is being deprecated in C++23.](https://en.cppreference.com/w/cpp/types/aligned_storage)  Some compilers (such as MSVC) have now started emitting warnings when `std::aligned_storage(_t)` is used.

[This StackOverflow post](https://stackoverflow.com/questions/71828288/why-is-stdaligned-storage-to-be-deprecated-in-c23-and-what-to-use-instead) and [this section on cppreference](https://en.cppreference.com/w/cpp/types/aligned_storage#Possible_implementation) suggest some potential replacements.

Apologies in advance if this is a duplicate issue. I've checked and could find any mention of it, so I created this one.

**Comment by skypjack** [comment]
Interesting. I didn't even know it was deprecated.
I'll try to address this one soon but 1) I'm on vacation, so don't expect a fast fix 🙂 and 2) it's kinda low prio since the library is still stuck on C++17 (because the gamedev world is stuck on that version of the standard at the moment and I won't mention consoles here just for the sake of mentioning the root cause 😅).
That said, I'm definitely not opposed to anticipating porting issues, so this one is welcome. Thanks for pointing it out! 👍

**Comment by skypjack** [comment]
Looking into this issue. My only concern is that `entt::any` is currently defined as:
```cpp
template<std::size_t Len = sizeof(double[2]), std::size_t Align = alignof(typename std::aligned_storage_t<Len + !Len>)>
class basic_any;
```
I'm not that sure about how to replace `alignof(typename std::aligned_storage_t<Len + !Len>)`.
Actually, I'm not even sure if I want to stick with this definition since the `Len` and `Align` pair feels _odd_ now that I've read the paper. 😅 
Any suggestion?

**Comment by LucidSigma** [comment]
I may be overlooking something, but is there anything wrong with creating a constexpr function to round a number to the nearest power of two and giving `Len + !Len` to it, and setting that to the alignment?  

Rough example:  
```cpp
template<std::size_t Len = sizeof(double[2]), std::size_t Align = nearest_power_of_two<Len + !Len>()>
class basic_any;
```

However, I am definitely not the best person to ask and there most likely exists a much cleaner/more correct solution.

**Comment by LucidSigma** [comment]
I played around with alignments on compiler explorer for a bit and I have come up with an idea.

`alignof(std::max_align_t)` is the largest that `alignof(std::aligned_storage_t<Size>)` can be (tried on a few compilers).

So, we could set the default `Align` to be the minimum of `alignof(std::max_align_t)` and `Len + !Len`.

However, there is the chance that `Len + !Len` could not be a power of two, so we can create a constexpr function to round it up to the nearest power of two.

Rough example:
```cpp
template<std::size_t Len = sizeof(double[2]), std::size_t Align = std::min(alignof(std::max_align_t), nearest_power_of_two<Len + !Len>())>
class basic_any;
```

However, I am definitely not the best person to ask about this subject and there most likely exists a much cleaner/more correct solution.

**Comment by skypjack** [comment]
Not sure the max between `alignof(std::max_align_t)` and `Len + !Len` is the right approach to be honest.
My plan was actually to get rid of the second parameter (the alignment) and to turn the remaining one into a _type from which you want to extract these information_ or even a _size of `double[N]`_ since this is what we're going to use under the hood in any case.
Consider that we're talking about a replacement for the template parameter list of `entt::any` where you don't have a _value type_ after all.

**Comment by LucidSigma** [comment]
That's definitely a much better approach. Thanks for resolving this issue so quickly! 😃

**Comment by skypjack** [comment]
Actually, I think the current implementation doesn't work as expected.
I'm testing it on a 32 system and it triggers a warning that wasn't there before.
