### ISSUE TITLE
reverse-iterate meta_range

### ISSUE THREAD

**Issue by harukumo** [skypjack/entt#927]
There is a way to reverse-iterate basic_view like this:

`auto view = registry.view<Component>();
for (auto entity : view | std::views::reverse)
{
    //...
}
`

But I didn't figure out how to reverse-iterate meta_range, I want something like this:

`
for (auto data : entt::resolve<Component>().data() | std::views::reverse)
{
    //...
}
`

Is there any way to do it?

**Comment by skypjack** [comment]
That's funny because I'm (heavily) reworking meta and this is easy to add now.
Briefly, the current implementation doesn't allow a reverse iteration. It's literally a single linked list of static objects (as in a templated `static T variable`). We can add a back link in theory but it's a lot of overhead for a corner case.
The _new_ implementation removes all the `static`-ness and stores meta objects in a (dense) map. The iterators of the latter are bidirectional by design. It goes without saying that we can have what you mentioned for free then.

**Comment by harukumo** [comment]
That's great. I'm looking forward to your update~

**Comment by skypjack** [comment]
Most of the changes are already on a branch, `meta`. If you want to give it a look and give me a feedback, you're welcome. 🙂
