### ISSUE TITLE
About copying registry's signals

### ISSUE THREAD

**Issue by hls333555** [skypjack/entt#950]
Is there a way I can copy one registry's bound signals (on_construct, on_update, on_destroy) to another? Thanks a lot!

**Comment by skypjack** [comment]
There is not actually 🤔 I'm sorry. Out of curiosity, what's the use case?

**Comment by hls333555** [comment]
> There is not actually 🤔 I'm sorry. Out of curiosity, what's the use case?

In my case, I have a scene which inherited from registry, when my game plays in editor, the scene will make a copy of itself so that any runtime changes will not affect the original editor scene. I added some registry signals on construction of scene, when my scene gets copied, I want to copy those already registered callbacks so that I do not need to register them again.

**Comment by hls333555** [comment]
> > There is not actually 🤔 I'm sorry. Out of curiosity, what's the use case?
> 
> In my case, I have a scene which inherited from registry, when my game plays in editor, the scene will make a copy of itself so that any runtime changes will not affect the original editor scene. I added some registry signals on construction of scene, when my scene gets copied, I want to copy those already registered callbacks so that I do not need to register them again because those callbacks also need to work in the runtime copied scene.

**Comment by skypjack** [comment]
I see. No, I'm sorry, there is no way to copy signals over to a different storage.
Since signals are part of a mixin, I don't even think it's easily feasible  from a reference to an erased instance.
You still have to `static_cast` the storage to the mixin type or to get it with the right component type and rely on the `storage_type` for the rest. However, I guess you want to copy them from a plain `sparse_set &storage` reference, is it?

**Comment by skypjack** [comment]
I assume this was answered. Closing it. Feel free to continue the discussion here if you have any other doubts. Thanks. 👍
