### ISSUE TITLE
Crash when disconnecting a listener in a component's destructor

### ISSUE THREAD

**Issue by phisko** [skypjack/entt#958]
Hi 👋 

First of all I'd like to say thanks and congrats on this great implementation of an ECS. I'm in the process of replacing the core implementation of [kengine](https://github.com/phisko/kengine) with `entt`, since I recently realized I'd ended up with a very similar API to yours, except you've gone far beyond my implementation!

However, I've stumbled upon a potential segmentation fault that occurs when disconnecting a listener in a component's destructor. Here's a short piece of code reproducing the issue:

```cpp
#include <entt/entity/registry.hpp>

struct listener {
    listener(entt::registry & r)
        : r(r)
    {
        r.on_construct<int>().connect<callback>();
    }

    ~listener() noexcept {
        r.on_construct<int>().disconnect<callback>();
    }

    static void callback() noexcept {}

    entt::registry & r;
};

int main() {
    entt::registry r;

    const auto e = r.create();
    r.emplace<int>(e);
    r.emplace<listener>(e, r);

    return 0;
}
```

As you can see, my `listener` component simply adds a listener in its ctor, and removes it in its dtor. The point of this being to have dynamic systems that will react to the construction/destruction/update of other components, while still being attached to an entity which could be removed at some point.

However, when `listener` is destroyed due to the `registry` going out of scope, it attempts to remove its callback from the storage for `int`. That storage has apparently already been destroyed, since [cpool](https://github.com/skypjack/entt/blob/master/src/entt/entity/registry.hpp/#L321) is non-null, but points to garbage.

Interestingly, inverting the calls to `r.emplace<int>(e)` and `r.emplace<listener>(e, r)` fixes the issue. I'm guessing that's because constructing the `listener` first results in the storage for `int` not having been initialized yet, so we're connecting the callback to a placeholder?

I haven't found any existing issues discussing this. Is this a known limitation? If so, what would your recommendations be to avoid hitting it?

One potential fix would be to set `pools[id]` to `nullptr` after destroying a pool, but that might require making some destructors non-trivial.

Thanks in advance,
phisko

**Comment by skypjack** [comment]
Yeah, pools are discarded in random order and this could even change in future, no guarantees.
Disconnecting upon component destruction as the result of pool destruction is a recipe for troubles. 😅 
A possible solution is to invoke `registry::clear` before destroying the registry. This should solve the issue since it forces the deletion of all components and entities without ever destroying the pools.

**Comment by phisko** [comment]
Hm, I see, that isn't ideal but should work. Is this something you'd like to improve on in the future? I feel like this should perhaps be documented somewhere

**Comment by skypjack** [comment]
I always like to improve but I don't really see how to approach it in this case.

EnTT offers the possibility to customize your pool types using mixins. Signal support is just a mixin in fact, you can easily strip it out if you like.
So, roughly speaking, the registry knows nothing about the actual pool type most of the times nor it cares about it actually. Everything just works anyway.

Fast forward to the registry destructor now: how would you solve your specific issue?
The only way I see is to force the destruction order (actually, this could work and is kinda possible already) or to use a mixin for one pool that says - _ehy, wait, let's empty the other pool first_.
Both things are very application specific. The registry cannot _check if a listener exists on a pool_ because it doesn't even know if the pools support signals and this isn't mandatory at all! That is, it's not its duty.

I'm more than willing to improve and please feel free to drop your suggestions here if any, but I feel like it ain't easy in this case.

**Comment by phisko** [comment]
I was thinking about something less application-specific, without trying to enforce a particular order. The main issue here is the dangling pointers in `pools` during component destruction. One solution would be for the `storage` destructor to set `pools[my_id]` to `nullptr`, but that implies that the `storage` keep a reference to its "parent" map, as well as its id. I haven't taken the time to see if that's the case currently. Alternatively, simply calling `clear` in the `registry` destructor could already be a fix for this.

However, I suppose this all goes against the "only pay for what you use" philosophy. I agree with you that there's no silver bullet here and these kind of edge cases are hard to find a one-size-fits-all solution to.

The best solution might simply be to document this behavior and suggest, as you did, clearing the `registry` before its destruction

**Comment by skypjack** [comment]
Yup, documenting it makes perfectly sense.
As for clearing in the destructor, I wouldn't add it _by default_ in EnTT since it's not strictly required and could be annoying in some cases. However, it's easy to achieve if you consider that the registry class isn't `final`. 🙂

**Comment by skypjack** [comment]
About the storage, no, they have no pointer back to the map nor to the registry in general.
You can create your own storage, manage them externally and combine them in a view with the storage from a registry.
So, there isn't a _parent map_ in all cases and I **do want** to support more and more the registry-less model over time.
I'm not going to drop the registry though, I just want to offer the choice between the two models. 👍

**Comment by phisko** [comment]
It isn't, but it also doesn't have any `virtual` members so deriving from it and overriding the destructor would be opening the door to it not being called when `delete`-ing a `registry *` that actually points to a `self_clearing_registry` (™ on that name 🙃)

Thanks for your time clearing all this up! Would you like me to open a pull request to document this behavior? Or do you prefer taking care of it on your side?

**Comment by skypjack** [comment]
Oh, yeah, if you destroy from the base it's a problem for sure. 👍 
As for the doc, I can update it on my own, no worries. Just leave the issue open so that I don't forget about it. 🙂 
Also thanks for pointing this out!! Really appreciated.
