### ISSUE TITLE
Question about sequence view iterator

### ISSUE THREAD

**Issue by hls333555** [skypjack/entt#975]
Is there a way that I can pass entt::meta_sequence_container::iterator to std algorithms so that I can manipulate vectors easily?
Actually, I want to call std::rotate to move vector element from one index to another using sequence container iterator.
Thanks a lot!

**Comment by skypjack** [comment]
Meta sequence container iterators model a bidirectional iterator **but** their tag category is `std::input_iterator_tag`.
This is due to some idiosyncrasies of the C++ language and cannot be otherwise unfortunately.
On the other hand, `std::rotate` wants a forward iterator. So, in theory it would work. In practice, it won't if the standard implementation checks the category at compile time.
In the second case, you can still implement your own version of `std::rotate` by following [these hints](https://en.cppreference.com/w/cpp/algorithm/rotate) and use it with the meta iterators. 🤷‍♂️ 
It's a shame because they are designed to work with this kind of algorithms but the standard implementation sets some requirements for historical reasons that don't make much sense anymore in 2023.
