### ISSUE TITLE
Need help with hot reloading through loading shared library at runtime

### ISSUE THREAD

**Issue by DaedieGit** [skypjack/entt#989]
So here is a quick overview of what i'm trying to do right now:
I have a main application (editor) that runs 2 registries, one that is is used while editing and one is used in play mode. At runtime, the user can create C++ files that contain components, which can be attached to an entity. These get picked up and compiled into a plugin at runtime (.so or .dll), the currently loaded plugin gets unloaded and the new one takes it's place.

My problem is the following: In this context, I have a bunch of Types that are only known to the plugin, so I've been trying to have the plugin attach these components to existing entities. The problem that arises here is that the plugin ends up allocating new pools in the registry, which seems to lead to double free-ing behavior on the corresponding shared_ptrs in the registry. I'm actually not entirely sure why this is happening, not have I been able to come up with an alternative solution so far.

**Comment by zaucy** [comment]
I couldn't speak to the double freeing you're experiencing, but are you using the named storage API? That might help you here if you aren't.

Relevant part of wiki doc: https://skypjack.github.io/entt/md_docs_md_entity.html

> EnTT is strongly based on types and has always allowed to create only one storage of a certain type within a registry.
However, this doesn't work well for users who want to create multiple storage of the same type associated with different names, such as for interacting with a scripting system.
> 
> Nowadays, the library has solved this problem and offers the possibility of associating a type with a name (or rather, a numeric identifier):
> 
> ```cpp
> using namespace entt::literals;
> auto &&storage = registry.storage<velocity>("second pool"_hs);
> ```
> If a name isn't provided, the default storage associated with the given type is always returned.
Since the storage are also self-contained, the registry doesn't try in any way to duplicate its API and offer parallel functionalities for storage discovered by name.
However, there is still no limit to the possibilities of use. For example:
> 
> ```cpp
> auto &&other = registry.storage<velocity>("other"_hs);
> 
> registry.emplace<velocity>(entity);
> storage.emplace(entity);
> ```

**Comment by Green-Sky** [comment]
this section would also be of interest: https://github.com/skypjack/entt/wiki/Push-EnTT-across-boundaries#memory-management

**Comment by skypjack** [comment]
Sorry for the late reply. I was out this week and also managed to get a flu 😅 just because.
I'm glad you solved your issue. Also thanks @Green-Sky @zaucy for helping. 🙏
